'(progn
  (configure-parser
   ((:accidental sh0 :sharp 0)
    (:accidental sh1 :sharp 1)
    (:accidental sh2 :sharp 2)
    (:accidental sh3 :sharp 3)
    (:accidental sh4 :sharp 4)
    (:accidental sh5 :sharp 5)
    (:accidental sh6 :sharp 6)
    (:accidental sh7 :sharp 7)
    (:accidental sh8 :sharp 8)
    (:accidental sh9 :sharp 9)
    (:accidental sh10 :sharp 10)
    (:accidental fl0 :flat 0)
    (:accidental fl1 :flat 1)
    (:accidental fl2 :flat 2)
    (:accidental fl3 :flat 3)
    (:accidental fl4 :flat 4)
    (:accidental fl5 :flat 5)
    (:accidental fl6 :flat 6)
    (:accidental fl7 :flat 7)
    (:accidental fl8 :flat 8)
    (:accidental fl9 :flat 9)
    (:accidental fl10 :flat 10)
    (:accidental nat0 :natural 0)
    (:accidental nat1 :natural 1)
    (:accidental nat2 :natural 2)
    (:accidental nat3 :natural 3)
    (:accidental nat4 :natural 4)
    (:accidental nat5 :natural 5)
    (:accidental nat6 :natural 6)
    (:accidental nat7 :natural 7)
    (:accidental nat8 :natural 8)
    (:accidental nat9 :natural 9)
    (:accidental nat10 :natura 10)
    (:clef cclef1 :c 1)
    (:clef cclef3 :c 3)
    (:clef cclef5 :c 5)
    (:clef cclef7 :c 7)
    (:clef cclef9 :c 9)
    (:clef fclef1 :f 1)
    (:clef fclef3 :f 3)
    (:clef fclef5 :f 5)
    (:clef fclef7 :f 7)
    (:clef fclef9 :f 9)
    (:note max6 :maxima 6)
    (:note max7 :maxima 7)
    (:note longa5 :longa 5)
    (:note br0 :brevis 0)
    (:note br1 :brevis 1)
    (:note br2 :brevis 2)
    (:note br3 :brevis 3)
    (:note br4 :brevis 4)
    (:note br5 :brevis 5)
    (:note br6 :brevis 6)
    (:note br7 :brevis 7)
    (:note br8 :brevis 8)
    (:note br9 :brevis 9)
    (:note br10 :brevis 10)
    (:note brd0 :brevis 0 :dot)
    (:note brd1 :brevis 1 :dot)
    (:note brd2 :brevis 2 :dot)
    (:note brd3 :brevis 3 :dot)
    (:note brd4 :brevis 4 :dot)
    (:note brd5 :brevis 5 :dot)
    (:note brd6 :brevis 6 :dot)
    (:note brd7 :brevis 7 :dot)
    (:note brd8 :brevis 8 :dot)
    (:note brd9 :brevis 9 :dot)
    (:note brd10 :brevis 10 :dot)
    (:note sb0 :semibrevis 0)
    (:note sb1 :semibrevis 1)
    (:note sb2 :semibrevis 2)
    (:note sb3 :semibrevis 3)
    (:note sb4 :semibrevis 4)
    (:note sb5 :semibrevis 5)
    (:note sb6 :semibrevis 6)
    (:note sb7 :semibrevis 7)
    (:note sb8 :semibrevis 8)
    (:note sb9 :semibrevis 9)
    (:note sb10 :semibrevis 10)
    (:note sbd0 :semibrevis 0 :dot)
    (:note sbd1 :semibrevis 1 :dot)
    (:note sbd2 :semibrevis 2 :dot)
    (:note sbd3 :semibrevis 3 :dot)
    (:note sbd4 :semibrevis 4 :dot)
    (:note sbd5 :semibrevis 5 :dot)
    (:note sbd6 :semibrevis 6 :dot)
    (:note sbd7 :semibrevis 7 :dot)
    (:note sbd8 :semibrevis 8 :dot)
    (:note sbd9 :semibrevis 9 :dot)
    (:note sbd10 :semibrevis 10 :dot)
    (:note sbc0 :semibrevis 0 :comma)
    (:note sbc1 :semibrevis 1 :comma)
    (:note sbc2 :semibrevis 2 :comma)
    (:note sbc3 :semibrevis 3 :comma)
    (:note sbc4 :semibrevis 4 :comma)
    (:note sbc5 :semibrevis 5 :comma)
    (:note sbc6 :semibrevis 6 :comma)
    (:note sbc7 :semibrevis 7 :comma)
    (:note sbc8 :semibrevis 8 :comma)
    (:note sbc9 :semibrevis 9 :comma)
    (:note sbc10 :semibrevis 10 :comma)
    (:note m0 :minima 0)
    (:note m1 :minima 1)
    (:note m2 :minima 2)
    (:note m3 :minima 3)
    (:note m4 :minima 4)
    (:note m5 :minima 5)
    (:note m6 :minima 6)
    (:note m7 :minima 7)
    (:note m8 :minima 8)
    (:note m9 :minima 9)
    (:note m10 :minima 10)
    (:note md0 :minima 0 :dot)
    (:note md1 :minima 1 :dot)
    (:note md2 :minima 2 :dot)
    (:note md3 :minima 3 :dot)
    (:note md4 :minima 4 :dot)
    (:note md5 :minima 5 :dot)
    (:note md6 :minima 6 :dot)
    (:note md7 :minima 7 :dot)
    (:note md8 :minima 8 :dot)
    (:note md9 :minima 9 :dot)
    (:note md10 :minima 10 :dot)
    (:note sm0 :semiminima 0)
    (:note sm1 :semiminima 1)
    (:note sm2 :semiminima 2)
    (:note sm3 :semiminima 3)
    (:note sm4 :semiminima 4)
    (:note sm5 :semiminima 5)
    (:note sm6 :semiminima 6)
    (:note sm7 :semiminima 7)
    (:note sm8 :semiminima 8)
    (:note sm9 :semiminima 9)
    (:note sm10 :semiminima 10)
    (:note smd0 :semiminima 0 :dot)
    (:note smd1 :semiminima 1 :dot)
    (:note smd2 :semiminima 2 :dot)
    (:note smd3 :semiminima 3 :dot)
    (:note smd4 :semiminima 4 :dot)
    (:note smd5 :semiminima 5 :dot)
    (:note smd6 :semiminima 6 :dot)
    (:note smd7 :semiminima 7 :dot)
    (:note smd8 :semiminima 8 :dot)
    (:note smd9 :semiminima 9 :dot)
    (:note smd10 :semiminima 10 :dot)
    ))

  (defparameter *list-of-notes*
    '(sb0 sb1 sb2 sb3 sb4 sb5 sb6 sb7 sb8 sb9 sb10)
    "This is used in the function to determine whether a note has a dotted duration value. Any glyph that can represent a dotted note should be member of this list.")

  (defparameter *list-of-duration-dots*
    '(dot2 dot4 dot6 dot8)
    "This is used in the function looking ahead to detect rhythmic dots. All glyphs used to represent rhythmic dots should be member of this list.")

  (defparameter *f-clef-triggers*
    '(fclef7)
    "This is used to determine when the definition of an compound f-clef is done and normal glyph parsing can be switched back on. All glyphs that complete an f-clef complex should be member of this list."))
