`(
 (glyph-blind :s1008 "space-1008" "black" 1008 ,*glyph-height*)
 (glyph-blind :s1080 "space-1080" "black" 1080 ,*glyph-height*)
 (glyph-blind :s720 "space-720" "black" 720 ,*glyph-height*)
 (glyph-blind :s41 "space-41" "black" 41 ,*glyph-height*)
 (glyph-blind :s0 "space-0" "black" 1 ,*glyph-height*)
 (glyph-staff :b13 "blank-13" "black" "stave" 13 ,*glyph-height*)
 (glyph-staff :b22 "blank-22" "black" "stave" 22 ,*glyph-height*)
 (glyph-staff :b27 "blank-27" "black" "stave" 27 ,*glyph-height*)
 (glyph-staff :b38 "blank-38" "black" "stave" 38 ,*glyph-height*)
 (glyph-staff :b56 "blank-56" "black" "stave" 56 ,*glyph-height*)
 (glyph-staff :b70 "blank-70" "black" "stave" 70 ,*glyph-height*)
 (glyph-staff :b118 "blank-118" "black" "stave" 118 ,*glyph-height*)
 (glyph-staff :b125 "blank-125" "black" "stave" 125 ,*glyph-height*)
 (glyph-staff :b245 "blank-245" "black" "stave" 245 ,*glyph-height*)
 (glyph-staff :b430 "blank-430" "black" "stave" 430 ,*glyph-height*)
 (glyph-staff :b677 "blank-677" "black" "stave" 677 ,*glyph-height*)
 (glyph-staff :b848 "blank-848" "black" "stave" 848 ,*glyph-height*)
 (glyph-custos :custos1 "custos-1" "black" "stave" "standard-custos" 38 ,*glyph-height* 1)
 (glyph-custos :custos2 "custos-2" "black" "stave" "standard-custos" 38 ,*glyph-height* 2)
 (glyph-custos :custos3 "custos-3" "black" "stave" "standard-custos" 38 ,*glyph-height* 3)
 (glyph-custos :custos4 "custos-4" "black" "stave" "standard-custos" 38 ,*glyph-height* 4)
 (glyph-custos :custos5 "custos-5" "black" "stave" "standard-custos" 38 ,*glyph-height* 5)
 (glyph-custos :custos6 "custos-6" "black" "stave" "standard-custos" 38 ,*glyph-height* 6)
 (glyph-custos :custos7 "custos-7" "black" "stave" "standard-custos" 38 ,*glyph-height* 7)
 (glyph-custos :custos8 "custos-8" "black" "stave" "standard-custos" 38 ,*glyph-height* 8)
 (glyph-custos :custos9 "custos-9" "black" "stave" "standard-custos" 38 ,*glyph-height* 9)
 (glyph-barline :bl "simple-barline" "black" "stave" "barline" "" 44 ,*glyph-height* 0 0 0 nil)
 (glyph-barline :blblue "simple-barline-blue" "blue" "stave" "barline" "" 44 ,*glyph-height* 0 0 0 nil)
 (glyph-barline :blbl "double-barline" "black" "stave" "barline" "" 44 ,*glyph-height* 30 0 0 nil)
 (glyph-barline :bl4-4 "barline-4-dots-both" "black" "stave" "barline" "enharmonic-dot" 95 ,*glyph-height* 0 30 4 :both)
 (glyph-flat :fl0 "flat-0" "black" "stave" "flat-normal" 30 ,*glyph-height* 0 nil nil)
 (glyph-flat :fl1 "flat-1" "black" "stave" "flat-normal" 30 ,*glyph-height* 1 nil nil)
 (glyph-flat :fl2 "flat-2" "black" "stave" "flat-normal" 30 ,*glyph-height* 2 nil nil)
 (glyph-flat :fl3 "flat-3" "black" "stave" "flat-normal" 30 ,*glyph-height* 3 nil nil)
 (glyph-flat :fl4 "flat-4" "black" "stave" "flat-normal" 30 ,*glyph-height* 4 nil nil)
 (glyph-flat :fl5 "flat-5" "black" "stave" "flat-normal" 30 ,*glyph-height* 5 nil nil)
 (glyph-flat :fl6 "flat-6" "black" "stave" "flat-short" 30 ,*glyph-height* 6 nil nil)
 (glyph-flat :fl7 "flat-7" "black" "stave" "flat-short" 30 ,*glyph-height* 7 nil nil)
 (glyph-flat :fl8 "flat-8" "black" "stave" "flat-short" 30 ,*glyph-height* 8 nil nil)
 (glyph-flat :fl8blue "flat-8-blue" "blue" "stave" "flat-short" 30 ,*glyph-height* 8 nil nil)
 (glyph-flat :fl9 "flat-9" "black" "stave" "flat-very-short" 30 ,*glyph-height* 9 nil nil)
 (glyph-flat :fl10 "flat-10" "black" "stave" "flat-very-short" 30 ,*glyph-height* 10 nil nil)
 (glyph-flat :fl11 "flat-11" "black" "stave" "flat-very-short" 30 ,*glyph-height* 11 nil nil)
 (glyph-flat :flrev4 "flat-reverse-4" "black" "stave" "flat-normal" 30 ,*glyph-height* 4 nil t)
 (glyph-flat :fl310 "flat-3-flat-10" "black" "stave" "flat-short" 30 ,*glyph-height* 3 10)
 (glyph-flat :fl29 "flat-2-flat-9" "black" "stave" "flat-short" 30 ,*glyph-height* 2 9)
 (glyph-flat :fl18 "flat-1-flat-8" "black" "stave" "flat-short" 30 ,*glyph-height* 1 8)
 (glyph-flat :fl07 "flat-0-flat-7" "black" "stave" "flat-short" 30 ,*glyph-height* 0 7)
 (glyph-bequadro :nat2 "bequadro-2" "black" "stave" "bequadro" 47 ,*glyph-height* 2)
 (glyph-bequadro :nat3 "bequadro-3" "black" "stave" "bequadro" 47 ,*glyph-height* 3)
 (glyph-bequadro :nat4 "bequadro-4" "black" "stave" "bequadro" 47 ,*glyph-height* 4)
 (glyph-bequadro :nat5 "bequadro-5" "black" "stave" "bequadro" 47 ,*glyph-height* 5)
 (glyph-bequadro :nat6 "bequadro-6" "black" "stave" "bequadro" 47 ,*glyph-height* 6)
 (glyph-bequadro :nat7 "bequadro-7" "black" "stave" "bequadro" 47 ,*glyph-height* 7)
 (glyph-bequadro :nat9 "bequadro-9" "black" "stave" "bequadro" 47 ,*glyph-height* 9)
 (glyph-notehead-stem :max7 "maxima-7" "black" "stave" "notehead-brevis" "" "stem-minima" 68 ,*glyph-height* 7 :down nil nil nil)
 (glyph-notehead-stem :max9 "maxima-9" "black" "stave" "notehead-brevis" "" "stem-minima" 68 ,*glyph-height* 9 :down nil nil nil)
 (glyph-notehead-stem :max5 "maxima-5" "black" "stave" "notehead-brevis" "" "stem-minima" 68 ,*glyph-height* 5 :down nil nil nil)
 (glyph-notehead-stem :max6 "maxima-6" "black" "stave" "notehead-maxima" "" "stem-minima" 111 ,*glyph-height* 6 :down nil nil nil)
 (glyph-notehead-stem :longa1 "longa-1" "black" "stave" "notehead-longa" "" "stem-minima" 64 ,*glyph-height* 1 :up nil nil nil)
 ;; longa3 ist "black nur für eine Idealisierung in b3-c32-m4 notwendi "blackg
 (glyph-notehead-stem :longa3 "longa-3" "black" "stave" "notehead-longa" "" "stem-minima" 64 ,*glyph-height* 3 :up nil nil nil)
 (glyph-notehead-stem :longa4 "longa-4" "black" "stave" "notehead-longa" "" "stem-minima" 64 ,*glyph-height* 4 :up nil nil nil)
 (glyph-notehead-stem :longa5 "longa-5" "black" "stave" "notehead-longa" "" "stem-minima" 64 ,*glyph-height* 5 :down nil nil nil)
 (glyph-notehead-stem :longa7 "longa-7" "black" "stave" "notehead-longa" "" "stem-minima" 64 ,*glyph-height* 7 :down nil nil nil)
 (glyph-notehead-stem :longa8 "longa-8" "black" "stave" "notehead-longa" "" "stem-minima" 64 ,*glyph-height* 8 :down nil nil nil)
 (glyph-notehead-stem :longa9 "longa-9" "black" "stave" "notehead-longa" "" "stem-minima" 64 ,*glyph-height* 9 :down nil nil nil)

 (glyph-notehead :br-1 "brevis--1" "black" "stave" "notehead-brevis" 45 ,*glyph-height* -1)
 (glyph-notehead :br0 "brevis-0" "black" "stave" "notehead-brevis" 45 ,*glyph-height* 0)
 (glyph-notehead :br1 "brevis-1" "black" "stave" "notehead-brevis" 45 ,*glyph-height* 1)
 (glyph-notehead :br2 "brevis-2" "black" "stave" "notehead-brevis" 45 ,*glyph-height* 2)
 (glyph-notehead :br3 "brevis-3" "black" "stave" "notehead-brevis" 45 ,*glyph-height* 3)
 (glyph-notehead :br4 "brevis-4" "black" "stave" "notehead-brevis" 45 ,*glyph-height* 4)
 (glyph-notehead :br5 "brevis-5" "black" "stave" "notehead-brevis" 45 ,*glyph-height* 5)
 (glyph-notehead :br6 "brevis-6" "black" "stave" "notehead-brevis" 45 ,*glyph-height* 6)
 (glyph-notehead :br7 "brevis-7" "black" "stave" "notehead-brevis" 45 ,*glyph-height* 7)
 (glyph-notehead :br8 "brevis-8" "black" "stave" "notehead-brevis" 45 ,*glyph-height* 8)
 (glyph-notehead :br9 "brevis-9" "black" "stave" "notehead-brevis" 45 ,*glyph-height* 9)
 (glyph-notehead :br10 "brevis-10" "black" "stave" "notehead-brevis" 45 ,*glyph-height* 10)
 (glyph-notehead :brbl1 "brevis-black-1" "black" "stave" "notehead-brevis-black" 45 ,*glyph-height* 1)
 (glyph-notehead :brbl2 "brevis-black-2" "black" "stave" "notehead-brevis-black" 45 ,*glyph-height* 2)
 (glyph-notehead :brbl3 "brevis-black-3" "black" "stave" "notehead-brevis-black" 45 ,*glyph-height* 3)
 (glyph-notehead :brbl4 "brevis-black-4" "black" "stave" "notehead-brevis-black" 45 ,*glyph-height* 4)
 (glyph-notehead :brbl5 "brevis-black-5" "black" "stave" "notehead-brevis-black" 45 ,*glyph-height* 5)
 (glyph-notehead :brbl6 "brevis-black-6" "black" "stave" "notehead-brevis-black" 45 ,*glyph-height* 6)
 (glyph-notehead :brbl7 "brevis-black-7" "black" "stave" "notehead-brevis-black" 45 ,*glyph-height* 7)
 (glyph-notehead :brbl8 "brevis-black-8" "black" "stave" "notehead-brevis-black" 45 ,*glyph-height* 8)
 (glyph-notehead :brbl9 "brevis-black-9" "black" "stave" "notehead-brevis-black" 45 ,*glyph-height* 9)
 (glyph-notehead :brbl10 "brevis-black-10" "black" "stave" "notehead-brevis-black" 45 ,*glyph-height* 10)
 (glyph-notehead-dot :brd2 "brevis-dot-2" "black" "stave" "notehead-brevis" "enharmonic-dot" 67 ,*glyph-height* 2)
 (glyph-notehead-dot :brd3 "brevis-dot-3" "black" "stave" "notehead-brevis" "enharmonic-dot" 67 ,*glyph-height* 3)
 (glyph-notehead-dot :brd4 "brevis-dot-4" "black" "stave" "notehead-brevis" "enharmonic-dot" 67 ,*glyph-height* 4)
 (glyph-notehead-dot :brd5 "brevis-dot-5" "black" "stave" "notehead-brevis" "enharmonic-dot" 67 ,*glyph-height* 5)
 (glyph-notehead-dot :brd6 "brevis-dot-6" "black" "stave" "notehead-brevis" "enharmonic-dot" 67 ,*glyph-height* 6)
 (glyph-notehead-dot :brd7 "brevis-dot-7" "black" "stave" "notehead-brevis" "enharmonic-dot" 67 ,*glyph-height* 7)
 (glyph-notehead-dot :brd10 "brevis-dot-10" "black" "stave" "notehead-brevis" "enharmonic-dot" 67 ,*glyph-height* 10)
 (glyph-notehead-dot :brdl5 "brevis-dot-left-5" "black" "stave" "notehead-brevis" "enharmonic-dot" 71 ,*glyph-height* 5 nil nil :left)
 (glyph-notehead-dot :brdr5 "brevis-dot-right-5" "black" "stave" "notehead-brevis" "enharmonic-dot" 51 ,*glyph-height* 5 nil nil :right)
 (glyph-notehead-dot :brc7 "brevis-comma-7" "black" "stave" "notehead-brevis" "comma" 53 ,*glyph-height* 7 t 1 :center nil)
 (glyph-notehead-dot :brc8 "brevis-comma-8" "black" "stave" "notehead-brevis" "comma" 53 ,*glyph-height* 8 t 1 :center nil)
 (glyph-notehead :sb0 "semibrevis-0" "black" "stave" "notehead-semibrevis" 53 ,*glyph-height* 0)
 (glyph-notehead :sb1 "semibrevis-1" "black" "stave" "notehead-semibrevis" 53 ,*glyph-height* 1)
 (glyph-notehead :sb2 "semibrevis-2" "black" "stave" "notehead-semibrevis" 53 ,*glyph-height* 2)
 (glyph-notehead :sb3 "semibrevis-3" "black" "stave" "notehead-semibrevis" 53 ,*glyph-height* 3)
 (glyph-notehead :sb4 "semibrevis-4" "black" "stave" "notehead-semibrevis" 53 ,*glyph-height* 4)
 (glyph-notehead :sb5 "semibrevis-5" "black" "stave" "notehead-semibrevis" 53 ,*glyph-height* 5)
 (glyph-notehead :sb6 "semibrevis-6" "black" "stave" "notehead-semibrevis" 53 ,*glyph-height* 6)
 (glyph-notehead :sb7 "semibrevis-7" "black" "stave" "notehead-semibrevis" 53 ,*glyph-height* 7)
 (glyph-notehead :sb7blue "semibrevis-7-blue" "blue" "stave" "notehead-semibrevis" 53 ,*glyph-height* 7)
 (glyph-notehead :sb8 "semibrevis-8" "black" "stave" "notehead-semibrevis" 53 ,*glyph-height* 8)
 (glyph-notehead :sb8blue "semibrevis-8-blue" "blue" "stave" "notehead-semibrevis" 53 ,*glyph-height* 8)
 (glyph-notehead :sb9 "semibrevis-9" "black" "stave" "notehead-semibrevis" 53 ,*glyph-height* 9)
 (glyph-notehead :sb10 "semibrevis-10" "black" "stave" "notehead-semibrevis" 53 ,*glyph-height* 10)
 (glyph-notehead :sb11 "semibrevis-11" "black" "stave" "notehead-semibrevis" 84 ,*glyph-height* 11)
 (glyph-notehead :sbbl0 "semibrevis-black-0" "black" "stave" "notehead-semibrevis-black" 53 ,*glyph-height* 0)
 (glyph-notehead :sbbl1 "semibrevis-black-1" "black" "stave" "notehead-semibrevis-black" 53 ,*glyph-height* 1)
 (glyph-notehead :sbbl2 "semibrevis-black-2" "black" "stave" "notehead-semibrevis-black" 53 ,*glyph-height* 2)
 (glyph-notehead :sbbl3 "semibrevis-black-3" "black" "stave" "notehead-semibrevis-black" 53 ,*glyph-height* 3)
 (glyph-notehead :sbbl4 "semibrevis-black-4" "black" "stave" "notehead-semibrevis-black" 53 ,*glyph-height* 4)
 (glyph-notehead :sbbl5 "semibrevis-black-5" "black" "stave" "notehead-semibrevis-black" 53 ,*glyph-height* 5)
 (glyph-notehead :sbbl6 "semibrevis-black-6" "black" "stave" "notehead-semibrevis-black" 53 ,*glyph-height* 6)
 (glyph-notehead :sbbl7 "semibrevis-black-7" "black" "stave" "notehead-semibrevis-black" 53 ,*glyph-height* 7)
 (glyph-notehead :sbbl8 "semibrevis-black-8" "black" "stave" "notehead-semibrevis-black" 53 ,*glyph-height* 8)
 (glyph-notehead-stem :m-1 "minima--1" "black" "stave" "notehead-semibrevis" "" "stem-minima" 84 ,*glyph-height* -1 :up)
 (glyph-notehead-stem :m0 "minima-0" "black" "stave" "notehead-semibrevis" "" "stem-minima" 48 ,*glyph-height* 0 :up)
 (glyph-notehead-stem :m1 "minima-1" "black" "stave" "notehead-semibrevis" "" "stem-minima" 48 ,*glyph-height* 1 :up)
 (glyph-notehead-stem :m2 "minima-2" "black" "stave" "notehead-semibrevis" "" "stem-minima" 48 ,*glyph-height* 2 :up)
 (glyph-notehead-stem :m3 "minima-3" "black" "stave" "notehead-semibrevis" "" "stem-minima" 48 ,*glyph-height* 3 :up)
 (glyph-notehead-stem :m4 "minima-4" "black" "stave" "notehead-semibrevis" "" "stem-minima" 48 ,*glyph-height* 4 :up)
 (glyph-notehead-stem :m5 "minima-5-up" "black" "stave" "notehead-semibrevis" "" "stem-minima" 48 ,*glyph-height* 5 :up)
 (glyph-notehead-stem :m5d "minima-5-down" "black" "stave" "notehead-semibrevis" "" "stem-minima" 48 ,*glyph-height* 5 :down)
 (glyph-notehead-stem :m6 "minima-6" "black" "stave" "notehead-semibrevis" "" "stem-minima" 48 ,*glyph-height* 6 :down)
 (glyph-notehead-stem :m7 "minima-7" "black" "stave" "notehead-semibrevis" "" "stem-minima" 48 ,*glyph-height* 7 :down)
 (glyph-notehead-stem :m8 "minima-8" "black" "stave" "notehead-semibrevis" "" "stem-minima" 48 ,*glyph-height* 8 :down)
 (glyph-notehead-stem :m9 "minima-9" "black" "stave" "notehead-semibrevis" "" "stem-minima" 48 ,*glyph-height* 9 :down)
 (glyph-notehead-stem :m10 "minima-10" "black" "stave" "notehead-semibrevis" "" "stem-minima" 48 ,*glyph-height* 10 :down)
 (glyph-notehead-stem :sm0 "semiminima-0" "black" "stave" "notehead-semibrevis-black" "" "stem-minima" 48 ,*glyph-height* 0 :up)
 (glyph-notehead-stem :sm1 "semiminima-1" "black" "stave" "notehead-semibrevis-black" "" "stem-minima" 48 ,*glyph-height* 1 :up)
 (glyph-notehead-stem :sm2 "semiminima-2" "black" "stave" "notehead-semibrevis-black" "" "stem-minima" 48 ,*glyph-height* 2 :up)
 (glyph-notehead-stem :sm3 "semiminima-3" "black" "stave" "notehead-semibrevis-black" "" "stem-minima" 48 ,*glyph-height* 3 :up)
 (glyph-notehead-stem :sm4 "semiminima-4" "black" "stave" "notehead-semibrevis-black" "" "stem-minima" 48 ,*glyph-height* 4 :up)
 (glyph-notehead-stem :sm5 "semiminima-5-up" "black" "stave" "notehead-semibrevis-black" "" "stem-minima" 48 ,*glyph-height* 5 :up)
 (glyph-notehead-stem :sm5d "semiminima-5-down" "black" "stave" "notehead-semibrevis-black" "" "stem-minima" 48 ,*glyph-height* 5 :down)
 (glyph-notehead-stem :sm6 "semiminima-6" "black" "stave" "notehead-semibrevis-black" "" "stem-minima" 48 ,*glyph-height* 6 :down)
 (glyph-notehead-stem :sm7 "semiminima-7" "black" "stave" "notehead-semibrevis-black" "" "stem-minima" 48 ,*glyph-height* 7 :down)
 (glyph-notehead-stem :sm8 "semiminima-8" "black" "stave" "notehead-semibrevis-black" "" "stem-minima" 48 ,*glyph-height* 8 :down)
 (glyph-notehead-stem :sm9 "semiminima-9" "black" "stave" "notehead-semibrevis-black" "" "stem-minima" 48 ,*glyph-height* 9 :down)
 (glyph-notehead-stem :sm10 "semiminima-10" "black" "stave" "notehead-semibrevis-black" "" "stem-minima" 48 ,*glyph-height* 10 :down)
 (glyph-f-clef-part :fclef9 "f-clef-part-9" "black" "stave" "notehead-semibrevis" "stem-minima" 45 ,*glyph-height* 9)
 (glyph-f-clef-part :fclef7 "f-clef-part-7" "black" "stave" "notehead-semibrevis" "stem-minima" 45 ,*glyph-height* 7)
 (glyph-f-clef-part :fclef5 "f-clef-part-5" "black" "stave" "notehead-semibrevis" "stem-minima" 45 ,*glyph-height* 5)
 (glyph-sharp :sh0 "sharp-0" "black" "stave" "sharp-large" 48 ,*glyph-height* 0)
 (glyph-sharp :sh1 "sharp-1" "black" "stave" "sharp-small" 48 ,*glyph-height* 1)
 (glyph-sharp :sh2 "sharp-2" "black" "stave" "sharp-large" 48 ,*glyph-height* 2)
 (glyph-sharp :sh3 "sharp-3" "black" "stave" "sharp-small" 48 ,*glyph-height* 3)
 (glyph-sharp :sinsh3 "single-sharp-3" "black" "stave" "single-sharp" 48 ,*glyph-height* 3)
 (glyph-sharp :sh4 "sharp-4" "black" "stave" "sharp-large" 48 ,*glyph-height* 4)
 (glyph-sharp :sh5 "sharp-5" "black" "stave" "sharp-small" 48 ,*glyph-height* 5)
 (glyph-sharp :sinsh5 "single-sharp-5" "black" "stave" "single-sharp" 48 ,*glyph-height* 5)
 (glyph-sharp :sh6 "sharp-6" "black" "stave" "sharp-large" 48 ,*glyph-height* 6)
 (glyph-sharp :sh7 "sharp-7" "black" "stave" "sharp-small" 48 ,*glyph-height* 7)
 (glyph-sharp :sinsh7 "single-sharp-7" "black" "stave" "single-sharp" 48 ,*glyph-height* 7)
 (glyph-sharp :sh7blue "sharp-7-blue" "blue" "stave" "sharp-small" 48 ,*glyph-height* 7)
 (glyph-sharp :sh8 "sharp-8" "black" "stave" "sharp-large" 48 ,*glyph-height* 8)
 (glyph-sharp :sh9 "sharp-9" "black" "stave" "sharp-small" 48 ,*glyph-height* 9)
 (glyph-sharp :sh10 "sharp-10" "black" "stave" "sharp-large" 48 ,*glyph-height* 10)
 (glyph-notehead-dot :sbd0 "semibrevis-dot-0" "black" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 0)
 (glyph-notehead-dot :sbd1 "semibrevis-dot-1" "black" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 1)
 (glyph-notehead-dot :sbd2 "semibrevis-dot-2" "black" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 2)
 (glyph-notehead-dot :sbd3 "semibrevis-dot-3" "black" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 3)
 (glyph-notehead-dot :sbd4 "semibrevis-dot-4" "black" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 4)
 (glyph-notehead-dot :sbd5 "semibrevis-dot-5" "black" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 5)
 (glyph-notehead-dot :sbd6 "semibrevis-dot-6" "black" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 6)
 (glyph-notehead-dot :sbd7 "semibrevis-dot-7" "black" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 7)
 (glyph-notehead-dot :sbd7blue "semibrevis-dot-7-blue" "blue" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 7)
 (glyph-notehead-dot :sbd8 "semibrevis-dot-8" "black" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 8)
 (glyph-notehead-dot :sbd8blue "semibrevis-dot-8-blue" "blue" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 8)
 (glyph-notehead-dot :sbd9 "semibrevis-dot-9" "black" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 9)
 (glyph-notehead-dot :sbd10 "semibrevis-dot-10" "black" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 10)
 (glyph-notehead-dot :sbc1 "semibrevis-comma-1" "black" "stave" "notehead-semibrevis" "comma" 53 ,*glyph-height* 1 t 1 :center nil)
 (glyph-notehead-dot :sbc2 "semibrevis-comma-2" "black" "stave" "notehead-semibrevis" "comma" 53 ,*glyph-height* 2 t 1 :center nil)
 (glyph-notehead-dot :sbc3 "semibrevis-comma-3" "black" "stave" "notehead-semibrevis" "comma" 53 ,*glyph-height* 3 t 1 :center nil)
 (glyph-notehead-dot :sbc4 "semibrevis-comma-4" "black" "stave" "notehead-semibrevis" "comma" 53 ,*glyph-height* 4 t 1 :center nil)
 (glyph-notehead-dot :sbc5 "semibrevis-comma-5" "black" "stave" "notehead-semibrevis" "comma" 53 ,*glyph-height* 5 t 1 :center nil)
 (glyph-notehead-dot :sbc6 "semibrevis-comma-6" "black" "stave" "notehead-semibrevis" "comma" 53 ,*glyph-height* 6 t 1 :center nil)
 (glyph-notehead-dot :sbc7 "semibrevis-comma-7" "black" "stave" "notehead-semibrevis" "comma" 53 ,*glyph-height* 7 t 1 :center nil)
 (glyph-notehead-dot :sbc8 "semibrevis-comma-8" "black" "stave" "notehead-semibrevis" "comma" 53 ,*glyph-height* 8 t 0.8 :center nil)
 (glyph-notehead-dot :sbc9 "semibrevis-comma-9" "black" "stave" "notehead-semibrevis" "comma" 53 ,*glyph-height* 9 t 1 :center nil)
 (glyph-notehead-dot :sbc10 "semibrevis-comma-10" "black" "stave" "notehead-semibrevis" "comma" 53 ,*glyph-height* 10 t 2 :center)
 (glyph-notehead-dot-comma :sbdc5 "semibrevis-dot-comma-5" "black" "stave" "notehead-semibrevis" "enharmonic-dot" "comma" 53 ,*glyph-height* 5 nil 0 :center nil 0.6)
 (glyph-notehead-dot-comma :sbdc6 "semibrevis-dot-comma-6" "black" "stave" "notehead-semibrevis" "enharmonic-dot" "comma" 53 ,*glyph-height* 6 nil 0 :center nil 0.6)
 (glyph-notehead-dot :sbdl7 "semibrevis-dot-left-7" "black" "stave" "notehead-semibrevis" "enharmonic-dot" 76 ,*glyph-height* 7 nil nil :left -2)
 (glyph-notehead-dot :sbdr4 "semibrevis-dot-right-4" "black" "stave" "notehead-semibrevis" "enharmonic-dot" 72 ,*glyph-height* 4 nil nil :right nil)
 (glyph-notehead-stem :md0 "minima-dot-0" "black" "stave" "notehead-semibrevis" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 0 :up nil 0 1.2 :center)
 (glyph-notehead-stem :md1 "minima-dot-1" "black" "stave" "notehead-semibrevis" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 1 :up nil 0 0.8 :center)
 (glyph-notehead-stem :md2 "minima-dot-2" "black" "stave" "notehead-semibrevis" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 2 :up t 0 0 :center)
 (glyph-notehead-stem :md3 "minima-dot-3" "black" "stave" "notehead-semibrevis" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 3 :up nil 1 0.8 :center)
 (glyph-notehead-stem :md4 "minima-dot-4" "black" "stave" "notehead-semibrevis" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 4 :up nil 0 0.4 :center)
 (glyph-notehead-stem :md5 "minima-dot-5" "black" "stave" "notehead-semibrevis" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 5 :up nil 0 0.4 :center)
 (glyph-notehead-stem :md5d "minima-dot-5-down" "black" "stave" "notehead-semibrevis" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 5 :down nil 0 0.4 :center)
 (glyph-notehead-stem :md6 "minima-dot-6" "black" "stave" "notehead-semibrevis" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 6 :down nil 0 0.4 :center)
 (glyph-notehead-stem :md7 "minima-dot-7" "black" "stave" "notehead-semibrevis" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 7 :down nil 0 0.4 :center)
 (glyph-notehead-stem :md8 "minima-dot-8" "black" "stave" "notehead-semibrevis" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 8 :down nil 0 0.4 :center)
 (glyph-notehead-stem :md9 "minima-dot-9" "black" "stave" "notehead-semibrevis" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 9 :down nil 0 0.4 :center)
 (glyph-notehead-stem :mdl4 "minima-dot-left-4" "black" "stave" "notehead-semibrevis" "enharmonic-dot" "stem-minima" 68 ,*glyph-height* 4 :up t 0 0.8 :left)
 (glyph-notehead-stem :smdr3 "semiminima-dot-right-3" "black" "stave" "notehead-semibrevis-black" "enharmonic-dot" "stem-minima" 68 ,*glyph-height* 3 :up t -2 0.8 :right)
 (glyph-notehead-stem :smd1 "semiminima-dot-1" "black" "stave" "notehead-semibrevis-black" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 1 :up nil 0 0.8 :center)
 (glyph-notehead-stem :smd2 "semiminima-dot-2" "black" "stave" "notehead-semibrevis-black" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 2 :up nil 0 0.8 :center)
 (glyph-notehead-stem :smd5 "semiminima-dot-5" "black" "stave" "notehead-semibrevis-black" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 5 :up nil 0 0.4 :center)
 (glyph-notehead-stem :smd5d "semiminima-dot-5-down" "black" "stave" "notehead-semibrevis-black" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 5 :down nil 0 0.4 :center)
 (glyph-notehead-stem :smd7 "semiminima-dot-7" "black" "stave" "notehead-semibrevis-black" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 7 :down nil 0 0.4 :center)
 (glyph-notehead-stem :smd9 "semiminima-dot-9" "black" "stave" "notehead-semibrevis-black" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 9 :down nil 0 0.4 :center)
 (glyph-notehead-flag :cr1 "croma-1" "black" "stave" "notehead-semibrevis-black" nil "stem-croma" "flag-croma-right" 68 ,*glyph-height* 1 :up)
 (glyph-notehead-flag :cr2 "croma-2" "black" "stave" "notehead-semibrevis-black" nil "stem-croma" "flag-croma-right" 68 ,*glyph-height* 2 :up)
 (glyph-notehead-flag :cr3 "croma-3" "black" "stave" "notehead-semibrevis-black" nil "stem-croma" "flag-croma-right" 68 ,*glyph-height* 3 :up)
 (glyph-notehead-flag :cr4 "croma-4" "black" "stave" "notehead-semibrevis-black" nil "stem-croma" "flag-croma-right" 68 ,*glyph-height* 4 :up)
 (glyph-notehead-flag :cr5 "croma-5" "black" "stave" "notehead-semibrevis-black" nil "stem-croma" "flag-croma-right" 68 ,*glyph-height* 5 :up)
 (glyph-notehead-flag :cr5d "croma-5-down" "black" "stave" "notehead-semibrevis-black" nil "stem-croma" "flag-croma-left" 68 ,*glyph-height* 5 :down)
 (glyph-notehead-flag :cr6 "croma-6" "black" "stave" "notehead-semibrevis-black" nil "stem-croma" "flag-croma-left" 68 ,*glyph-height* 6 :down)
 (glyph-notehead-flag :cr7 "croma-7" "black" "stave" "notehead-semibrevis-black" nil "stem-croma" "flag-croma-left" 68 ,*glyph-height* 7 :down)
 (glyph-notehead-flag :cr8 "croma-8" "black" "stave" "notehead-semibrevis-black" nil "stem-croma" "flag-croma-left" 68 ,*glyph-height* 8 :down)
 (glyph-notehead-flag :cr9 "croma-9" "black" "stave" "notehead-semibrevis-black" nil "stem-croma" "flag-croma-left" 68 ,*glyph-height* 9 :down)
 (glyph-notehead-flag :crd7 "croma-dot-7" "black" "stave" "notehead-semibrevis-black" "enharmonic-dot" "stem-croma" "flag-croma-left" 68 ,*glyph-height* 7 :down nil 0 0.4 :center)
 (glyph-notehead-flag :scr3 "semicroma-3" "black" "stave" "notehead-semibrevis-black" nil "stem-croma" "flag-semicroma-right" 68 ,*glyph-height* 3 :up)
 (glyph-notehead-flag :scr4 "semicroma-4" "black" "stave" "notehead-semibrevis-black" nil "stem-croma" "flag-semicroma-right" 68 ,*glyph-height* 4 :up)
 (glyph-notehead-flag :scr5d "semicroma-5-down" "black" "stave" "notehead-semibrevis-black" nil "stem-croma" "flag-semicroma-right" 68 ,*glyph-height* 5 :down)
 (glyph-notehead-flag :scr6 "semicroma-6" "black" "stave" "notehead-semibrevis-black" nil "stem-croma" "flag-semicroma-right" 68 ,*glyph-height* 6 :down)
 (glyph-notehead-flag :scr7 "semicroma-7" "black" "stave" "notehead-semibrevis-black" nil "stem-croma" "flag-semicroma-right" 68 ,*glyph-height* 7 :down)
 (glyph-notehead-flag :scrd2 "semicroma-dot-2" "black" "stave" "notehead-semibrevis-black" "enharmonic-dot" "stem-croma" "flag-semicroma-right" 68 ,*glyph-height* 2 :up t)
 (glyph-c-clef :cclef1 "c-clef-1" "black" "stave" "c-clef-short" 66 ,*glyph-height* 1)
 (glyph-c-clef :cclef3 "c-clef-3" "black" "stave" "c-clef-short" 66 ,*glyph-height* 3)
 (glyph-c-clef :cclef5 "c-clef-5" "black" "stave" "c-clef" 66 ,*glyph-height* 5)
 (glyph-c-clef :cclef7 "c-clef-7" "black" "stave" "c-clef" 66 ,*glyph-height* 7)
 (glyph-g-clef :gclef3 "g-clef-3" "black" "stave" "g-clef" 80 ,*glyph-height* 3)
 (glyph-rest :mrest1 "minima-rest-1" "black" "stave" "minima-rest" 24 ,*glyph-height* 1 :up)
 (glyph-rest :mrest3 "minima-rest-3" "black" "stave" "minima-rest" 24 ,*glyph-height* 3 :up)
 (glyph-rest :mrest5 "minima-rest-5" "black" "stave" "minima-rest" 24 ,*glyph-height* 5 :up)
 (glyph-rest :mrest7 "minima-rest-7" "black" "stave" "minima-rest" 24 ,*glyph-height* 7 :up)
 (glyph-rest :smrest1 "semiminima-rest-1" "black" "stave" "semiminima-rest" 50 ,*glyph-height* 1 :up)
 (glyph-rest :smrest5 "semiminima-rest-5" "black" "stave" "semiminima-rest" 50 ,*glyph-height* 5 :up)
 (glyph-rest :smrest3 "semiminima-rest-3" "black" "stave" "semiminima-rest" 50 ,*glyph-height* 3 :up)
 (glyph-rest :smrest7 "semiminima-rest-7" "black" "stave" "semiminima-rest" 50 ,*glyph-height* 7 :up)
 (glyph-rest :sbrest3 "semibrevis-rest-3" "black" "stave" "minima-rest" 24 ,*glyph-height* 3 :down)
 (glyph-rest :sbrest5 "semibrevis-rest-5" "black" "stave" "minima-rest" 24 ,*glyph-height* 5 :down)
 (glyph-rest :sbrest7 "semibrevis-rest-7" "black" "stave" "minima-rest" 24 ,*glyph-height* 7 :down)
 (glyph-rest :sbrest9 "semibrevis-rest-9" "black" "stave" "minima-rest" 24 ,*glyph-height* 9 :down)
 (glyph-rest :brrest2 "brevis-rest-2" "black" "stave" "brevis-rest" 20 ,*glyph-height* 3 :down)
 (glyph-rest :brrest4 "brevis-rest-4" "black" "stave" "brevis-rest" 20 ,*glyph-height* 5 :down)
 (glyph-rest :brrest6 "brevis-rest-6" "black" "stave" "brevis-rest" 20 ,*glyph-height* 7 :down)
 (glyph-rest :brrest8 "brevis-rest-8" "black" "stave" "brevis-rest" 20 ,*glyph-height* 9 :down)
 (glyph-rest :lrest24 "longa-rest-2-4" "black" "stave" "longa-rest" 20 ,*glyph-height* 1 :up)
 (glyph-rest :lrest46 "longa-rest-4-6" "black" "stave" "longa-rest" 20 ,*glyph-height* 3 :up)
 (glyph-rest :lrest68 "longa-rest-6-8" "black" "stave" "longa-rest" 20 ,*glyph-height* 5 :up)
 (glyph-rest :maxrest246 "maxima-rest-2-4-6" "black" "stave" "maxima-rest" 42 ,*glyph-height* 1 :up)
 (glyph-meter :met-perf-min "meter-perfectum-minor" "black" "stave" "tempus-perfectum" nil nil 68 ,*glyph-height*)
 (glyph-meter :met-perf-maj "meter-perfectum-major" "black" "stave" "tempus-perfectum" "prolatio-major" nil 68 ,*glyph-height* 0)
 (glyph-meter :met-perf-min-dim "meter-perfectum-minor-diminutum" "black" "stave" "tempus-perfectum" nil "diminutum" 68 ,*glyph-height* 0 -0.1 -0.4)
 (glyph-meter :met-imperf-maj "meter-imperfectum-major" "black" "stave" "tempus-imperfectum" "prolatio-major" nil 68 ,*glyph-height* 0 -0.1 -0.4)
 (glyph-meter :met-imperf-min "meter-imperfectum-minor" "black" "stave" "tempus-imperfectum" nil nil 68 ,*glyph-height* 0 -0.1 -0.4)
 (glyph-meter :met-imperf-min-dim "meter-imperfectum-minor-diminutum" "black" "stave" "tempus-imperfectum" nil "diminutum" 68 ,*glyph-height* 0 -0.1 -0.4)
 (glyph-digit-arc :met-3-2 "meter-digits-3-2" "black" "stave" ("digit-arc-3" "digit-arc-3" "digit-arc-2") (5 5 1) (:up :down :up) 41 ,*glyph-height*)
 (glyph-digit-arc :met-3 "meter-digits-3" "black" "stave" ("digit-arc-3" "digit-arc-3") (5 5) (:up :down) 41 ,*glyph-height*)
 (glyph-dot :dot0 "dotted-0" "black" "stave" "enharmonic-dot" 43 ,*glyph-height* 0)
 (glyph-dot :dot2 "dotted-2" "black" "stave" "enharmonic-dot" 43 ,*glyph-height* 2)
 (glyph-dot :dot4 "dotted-4" "black" "stave" "enharmonic-dot" 43 ,*glyph-height* 4)
 (glyph-dot :dot6 "dotted-6" "black" "stave" "enharmonic-dot" 43 ,*glyph-height* 6)
 (glyph-dot :dot8 "dotted-8" "black" "stave" "enharmonic-dot" 43 ,*glyph-height* 8)
 (glyph-dot :dot10 "dotted-10" "black" "stave" "enharmonic-dot" 43 ,*glyph-height* 10)
 )
