`((glyph-staff                  b13     "blank-13"       "stave" 13 ,*glyph-height*)
  (glyph-staff                  b22     "blank-22"       "stave" 22 ,*glyph-height*)
  (glyph-staff                  b27     "blank-27"       "stave" 27 ,*glyph-height*)
  (glyph-staff                  b38     "blank-38"       "stave" 38 ,*glyph-height*)
  (glyph-staff                  b56     "blank-56"       "stave" 56 ,*glyph-height*)
  (glyph-staff                  b70     "blank-70"       "stave" 70 ,*glyph-height*)
  (glyph-staff                  b245     "blank-245"       "stave" 245 ,*glyph-height*)
  (glyph-staff                  b430    "blank-430"      "stave" 430 ,*glyph-height*)
  (glyph-staff                  b677    "blank-677"      "stave" 677 ,*glyph-height*)
  (glyph-staff                  b848    "blank-848"      "stave" 848 ,*glyph-height*)
  (glyph-barline                bl     "simple-barline" "stave" "barline" "" 44 ,*glyph-height* 0 0 0 nil)
  (glyph-flat                   fl1     "flat-1"        "stave" "flat-normal" 30 ,*glyph-height* 1 nil nil)
  (glyph-flat                   fl2     "flat-2"        "stave" "flat-normal" 30 ,*glyph-height* 2 nil nil)
  (glyph-flat                   fl3     "flat-3"        "stave" "flat-normal" 30 ,*glyph-height* 3 nil nil)
  (glyph-flat                   fl4     "flat-4"        "stave" "flat-normal" 30 ,*glyph-height* 4 nil nil)
  (glyph-flat                   fl5     "flat-5"        "stave" "flat-normal" 30 ,*glyph-height* 5 nil nil)
  (glyph-flat                   fl6     "flat-6"        "stave" "flat-short" 30 ,*glyph-height* 6 nil nil)
  (glyph-flat                   fl7     "flat-7"        "stave" "flat-short" 30 ,*glyph-height* 7 nil nil)
  (glyph-flat                   fl8     "flat-8"        "stave" "flat-short" 30 ,*glyph-height* 8 nil nil)
  (glyph-flat                   fl9     "flat-9"        "stave" "flat-very-short" 30 ,*glyph-height* 9 nil nil)
  (glyph-flat                   flrev4     "flat-reverse-4"        "stave" "flat-normal" 30 ,*glyph-height* 4 nil t)
  (glyph-bequadro               nat3   "bequadro-3"     "stave" "bequadro" 47 ,*glyph-height* 3)
  (glyph-bequadro               nat4   "bequadro-4"     "stave" "bequadro" 47 ,*glyph-height* 4)
  (glyph-bequadro               nat6   "bequadro-6"     "stave" "bequadro" 47 ,*glyph-height* 6)
  (glyph-notehead-stem          max7   "maxima-7"      "stave" "notehead-brevis"     "" "stem-minima" 68 ,*glyph-height* 7 :down nil nil nil)
  (glyph-notehead-stem          max6   "maxima-6"      "stave" "notehead-maxima"     "" "stem-minima" 111 ,*glyph-height* 6 :down nil nil nil)
  (glyph-notehead-stem          longa5   "longa-5"      "stave" "notehead-longa"     "" "stem-minima" 64 ,*glyph-height* 5 :down nil nil nil)

  (glyph-notehead               br4    "brevis-4"  "stave" "notehead-brevis" 45 ,*glyph-height* 4)
  (glyph-notehead               br5    "brevis-5"  "stave" "notehead-brevis" 45 ,*glyph-height* 5)
  (glyph-notehead               br6    "brevis-6"  "stave" "notehead-brevis" 45 ,*glyph-height* 6)
  (glyph-notehead-dot           brd4   "brevis-dot-4" "stave" "notehead-brevis" "enharmonic-dot" 67 ,*glyph-height* 4)
  (glyph-notehead-dot           brd5   "brevis-dot-5" "stave" "notehead-brevis" "enharmonic-dot" 67 ,*glyph-height* 5)
  (glyph-notehead-dot           brdl5   "brevis-dot-left-5" "stave" "notehead-brevis" "enharmonic-dot" 71 ,*glyph-height* 5 nil nil :left)
  (glyph-notehead-dot           brdr5   "brevis-dot-right-5" "stave" "notehead-brevis" "enharmonic-dot" 51 ,*glyph-height* 5 nil nil :right)
  (glyph-notehead               sb0    "semibrevis-0"  "stave" "notehead-semibrevis" 53 ,*glyph-height* 0)
  (glyph-notehead               sb1    "semibrevis-1"  "stave" "notehead-semibrevis" 53 ,*glyph-height* 1)
  (glyph-notehead               sb2    "semibrevis-2"  "stave" "notehead-semibrevis" 53 ,*glyph-height* 2)
  (glyph-notehead               sb3    "semibrevis-3"  "stave" "notehead-semibrevis" 53 ,*glyph-height* 3)
  (glyph-notehead               sb4    "semibrevis-4"  "stave" "notehead-semibrevis" 53 ,*glyph-height* 4)
  (glyph-notehead               sb5    "semibrevis-5"  "stave" "notehead-semibrevis" 53 ,*glyph-height* 5)
  (glyph-notehead               sb6    "semibrevis-6"  "stave" "notehead-semibrevis" 53 ,*glyph-height* 6)
  (glyph-notehead               sb7    "semibrevis-7"  "stave" "notehead-semibrevis" 53 ,*glyph-height* 7)
  (glyph-notehead               sb8    "semibrevis-8"  "stave" "notehead-semibrevis" 53 ,*glyph-height* 8)
  (glyph-notehead               sb9    "semibrevis-9"  "stave" "notehead-semibrevis" 53 ,*glyph-height* 9)
  (glyph-notehead               sb10    "semibrevis-10"  "stave" "notehead-semibrevis" 53 ,*glyph-height* 10)
  (glyph-notehead-stem          m7     "minima-7"      "stave" "notehead-semibrevis" "" "stem-minima" 53 ,*glyph-height* 7 :down)
  (glyph-notehead-stem          m6     "minima-6"      "stave" "notehead-semibrevis" "" "stem-minima" 53 ,*glyph-height* 6 :down)
  (glyph-f-clef-part            fclef7 "f-clef-part-7" "stave" "notehead-semibrevis" "stem-minima" 45 ,*glyph-height* 7)
  (glyph-sharp                  sh1    "sharp-1"       "stave" "sharp-large" 48 ,*glyph-height* 1)
  (glyph-sharp                  sh2    "sharp-2"       "stave" "sharp-large" 48 ,*glyph-height* 2)
  (glyph-sharp                  sh3    "sharp-3"       "stave" "sharp-small" 48 ,*glyph-height* 3)
  (glyph-sharp                  sh4    "sharp-4"       "stave" "sharp-large" 48 ,*glyph-height* 4)
  (glyph-sharp                  sh5    "sharp-5"       "stave" "sharp-small" 48 ,*glyph-height* 5)
  (glyph-sharp                  sh6    "sharp-6"       "stave" "sharp-large" 48 ,*glyph-height* 6)
  (glyph-sharp                  sh7    "sharp-7"       "stave" "sharp-small" 48 ,*glyph-height* 7)
  (glyph-sharp                  sh8    "sharp-8"       "stave" "sharp-large" 48 ,*glyph-height* 8)
  (glyph-notehead-dot           sbd1   "semibrevis-dot-1" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 1)
  (glyph-notehead-dot           sbd2   "semibrevis-dot-2" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 2)
  (glyph-notehead-dot           sbd3   "semibrevis-dot-3" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 3)
  (glyph-notehead-dot           sbd4   "semibrevis-dot-4" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 4)
  (glyph-notehead-dot           sbd5   "semibrevis-dot-5" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 5)
  (glyph-notehead-dot           sbd6   "semibrevis-dot-6" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 6)
  (glyph-notehead-dot           sbd7   "semibrevis-dot-7" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 7)
  (glyph-notehead-dot           sbd8   "semibrevis-dot-8" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 8)
  (glyph-notehead-dot           sbd9   "semibrevis-dot-9" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 9)
  (glyph-notehead-dot           sbd9   "semibrevis-dot-9" "stave" "notehead-semibrevis" "enharmonic-dot" 53 ,*glyph-height* 9)
  (glyph-notehead-dot           sbc7   "semibrevis-comma-7" "stave" "notehead-semibrevis" "comma" 53 ,*glyph-height* 7 t 1 :center nil)
  (glyph-notehead-dot           sbc8   "semibrevis-comma-8" "stave" "notehead-semibrevis" "comma" 53 ,*glyph-height* 8 t 1 :center nil)
  (glyph-notehead-dot           sbc9   "semibrevis-comma-9" "stave" "notehead-semibrevis" "comma" 53 ,*glyph-height* 9 t 1.5 :center nil)
  (glyph-notehead-dot           sbdl7   "semibrevis-dot-left-7" "stave" "notehead-semibrevis" "enharmonic-dot" 76 ,*glyph-height* 7 nil nil :left -2)
  (glyph-notehead-dot           sbdr4   "semibrevis-dot-right-4" "stave" "notehead-semibrevis" "enharmonic-dot" 72 ,*glyph-height* 4 nil nil :right nil)
  (glyph-notehead-stem          md4     "minima-dot-4" "stave" "notehead-semibrevis" "enharmonic-dot" "stem-minima" 55 ,*glyph-height* 4 :down nil 1 0.8 :center)
  (glyph-notehead-stem          mdl4     "minima-dot-left-4" "stave" "notehead-semibrevis" "enharmonic-dot" "stem-minima" 68 ,*glyph-height* 4 :up t 0 0.8 :left)
  (glyph-notehead-stem          smdr3     "semiminima-dot-right-3" "stave" "notehead-semibrevis-black" "enharmonic-dot" "stem-minima" 68 ,*glyph-height* 3 :up t -2 0.8 :right)
  (glyph-c-clef                 cclef7 "c-clef-7" "stave" "c-clef" 66 ,*glyph-height* 7)
  (glyph-c-clef                 cclef1 "c-clef-1" "stave" "c-clef-short" 66 ,*glyph-height* 1)
  (glyph-c-clef                 cclef5 "c-clef-5" "stave" "c-clef" 66 ,*glyph-height* 5)
  (glyph-rest mrest5 "minima-rest-5" "stave" "minima-rest" 23 ,*glyph-height* 5 :up)
  (glyph-rest mrest3 "minima-rest-3" "stave" "minima-rest" 23 ,*glyph-height* 3 :up)
  )
