
(defparameter *setzkasten-definition-components*
  '((component-staff-lines nil "5-stave" 5 100 12 8)
    (component-notehead nil "notehead-brevis" 0.3 0.95 28 16 nil nil)
    (component-notehead nil "notehead-brevis-black" 0.3 0.95 28 16 nil t)
    (component-notehead nil "notehead-semibrevis" 0.25 1.0 32 12 t nil)
    (component-notehead nil "notehead-semibrevis-black" 0.25 1.0 35 14 t t)
    (component-dot nil "enharmonic-dot" 0.4)
    (component-stem nil "minima-stem" 2.5 14 1.8)
    (component-stem nil "minima-stem-short-a" 2.1 14 1.8)
    (component-stem nil "minima-stem-short-b" 1.6 14 1.8)
    (component-flag nil "croma-flag" 15 9 0.35 0.7 nil 0.8 0.7)
    (component-flag nil "semicroma-flag" 11 11 0.2 0.5 t 0.8 0.7)
    (component-rest nil "minima-semibrevis-rest" 0.5 15 0 0)
    (component-rest nil "semiminima-rest" 0.5 15 -0.4 13)
    (component-rest nil "maxima-rest" 2 15 0 0)
    (component-sharp nil "double-sharp" 9 1 t 27)
    (component-sharp nil "single-sharp" 9 1 nil 0)
    (component-flat nil "flat" 9 8 1.2 2.8 1)
    ))

(defparameter *glyph-height* 800)

(defparameter *setzkasten-definition-glyphs*
  `((glyph-staff ba "blank-a" "5-stave" 50 ,*glyph-height*)
    (glyph-staff bb "blank-b" "5-stave" 150 ,*glyph-height*)
    (glyph-staff bc "blank-c" "5-stave" 450 ,*glyph-height*)
    (glyph-notehead br0 "brevis-a" "5-stave" "notehead-brevis" 205 ,*glyph-height* 0)
    (glyph-notehead br1 "brevis-b" "5-stave" "notehead-brevis" 205 ,*glyph-height* 1)
    (glyph-notehead br2 "brevis-c" "5-stave" "notehead-brevis" 205 ,*glyph-height* 2)
    (glyph-notehead br3 "brevis-d" "5-stave" "notehead-brevis" 205 ,*glyph-height* 3)
    (glyph-notehead br4 "brevis-e" "5-stave" "notehead-brevis" 205 ,*glyph-height* 4)
    (glyph-notehead br5 "brevis-f" "5-stave" "notehead-brevis" 205 ,*glyph-height* 5)
    (glyph-notehead sb0 "semibrevis-a" "5-stave" "notehead-semibrevis" 180 ,*glyph-height* 0)
    (glyph-notehead sb1 "semibrevis-b" "5-stave" "notehead-semibrevis" 180 ,*glyph-height* 1)
    (glyph-notehead sb2 "semibrevis-c" "5-stave" "notehead-semibrevis" 180 ,*glyph-height* 2)
    (glyph-notehead sb3 "semibrevis-d" "5-stave" "notehead-semibrevis" 180 ,*glyph-height* 3)
    (glyph-notehead sb4 "semibrevis-e" "5-stave" "notehead-semibrevis" 180 ,*glyph-height* 4)
    (glyph-notehead sb5 "semibrevis-f" "5-stave" "notehead-semibrevis" 180 ,*glyph-height* 5)
    (glyph-notehead sb6 "semibrevis-g" "5-stave" "notehead-semibrevis" 180 ,*glyph-height* 6)
    (glyph-notehead sb7 "semibrevis-h" "5-stave" "notehead-semibrevis" 180 ,*glyph-height* 7)
    (glyph-notehead sb8 "semibrevis-i" "5-stave" "notehead-semibrevis" 180 ,*glyph-height* 8)
    (glyph-notehead sb9 "semibrevis-j" "5-stave" "notehead-semibrevis" 180 ,*glyph-height* 9)
    (glyph-notehead sb10 "semibrevis-k" "5-stave" "notehead-semibrevis" 180 ,*glyph-height* 10)
    (glyph-notehead brb0 "brevis-a-black" "5-stave" "notehead-brevis-black" 205 ,*glyph-height* 0)
    (glyph-notehead brb1 "brevis-b-black" "5-stave" "notehead-brevis-black" 205 ,*glyph-height* 1)
    (glyph-notehead brb2 "brevis-c-black" "5-stave" "notehead-brevis-black" 205 ,*glyph-height* 2)
    (glyph-notehead brb3 "brevis-d-black" "5-stave" "notehead-brevis-black" 205 ,*glyph-height* 3)
    (glyph-notehead brb4 "brevis-e-black" "5-stave" "notehead-brevis-black" 205 ,*glyph-height* 4)
    (glyph-notehead brb5 "brevis-f-black" "5-stave" "notehead-brevis-black" 205 ,*glyph-height* 5)
    (glyph-notehead sbb0 "semibrevis-a-black" "5-stave" "notehead-semibrevis-black" 180 ,*glyph-height* 0)
    (glyph-notehead sbb1 "semibrevis-b-black" "5-stave" "notehead-semibrevis-black" 180 ,*glyph-height* 1)
    (glyph-notehead sbb2 "semibrevis-c-black" "5-stave" "notehead-semibrevis-black" 180 ,*glyph-height* 2)
    (glyph-notehead sbb3 "semibrevis-d-black" "5-stave" "notehead-semibrevis-black" 180 ,*glyph-height* 3)
    (glyph-notehead sbb4 "semibrevis-e-black" "5-stave" "notehead-semibrevis-black" 180 ,*glyph-height* 4)
    (glyph-notehead sbb5 "semibrevis-f-black" "5-stave" "notehead-semibrevis-black" 180 ,*glyph-height* 5)
    (glyph-notehead-dot brd0 "brevis-a-dot" "5-stave" "notehead-brevis" "enharmonic-dot" 205 ,*glyph-height* 0 t 1 :center)
    (glyph-notehead-dot brd1 "brevis-b-dot" "5-stave" "notehead-brevis" "enharmonic-dot" 205 ,*glyph-height* 1 t 1 :center)
    (glyph-notehead-dot brd2 "brevis-c-dot" "5-stave" "notehead-brevis" "enharmonic-dot" 205 ,*glyph-height* 2 t 1 :center)
    (glyph-notehead-dot brd3 "brevis-d-dot" "5-stave" "notehead-brevis" "enharmonic-dot" 205 ,*glyph-height* 3 t 1 :center)
    (glyph-notehead-dot brd4 "brevis-e-dot" "5-stave" "notehead-brevis" "enharmonic-dot" 205 ,*glyph-height* 4 t 1 :center)
    (glyph-notehead-dot brd5 "brevis-f-dot" "5-stave" "notehead-brevis" "enharmonic-dot" 205 ,*glyph-height* 5 t 1 :center)
    (glyph-notehead-dot brd6 "brevis-g-dot" "5-stave" "notehead-brevis" "enharmonic-dot" 205 ,*glyph-height* 6 t 1 :center)
    (glyph-notehead-dot brd7 "brevis-h-dot" "5-stave" "notehead-brevis" "enharmonic-dot" 205 ,*glyph-height* 7 t 1 :center)
    (glyph-notehead-dot brd8 "brevis-i-dot" "5-stave" "notehead-brevis" "enharmonic-dot" 205 ,*glyph-height* 8 t 1 :center)
    (glyph-notehead-dot brd9 "brevis-j-dot" "5-stave" "notehead-brevis" "enharmonic-dot" 205 ,*glyph-height* 9 t 1 :center)
    (glyph-notehead-dot brd10 "brevis-k-dot" "5-stave" "notehead-brevis" "enharmonic-dot" 205 ,*glyph-height* 10 t 2 :center)
    (glyph-notehead-dot sbd0 "semibrevis-a-dot" "5-stave" "notehead-semibrevis" "enharmonic-dot" 180 ,*glyph-height* 0 nil 0 :center)
    (glyph-notehead-dot sbd1 "semibrevis-b-dot" "5-stave" "notehead-semibrevis" "enharmonic-dot" 180 ,*glyph-height* 1 nil 0 :center)
    (glyph-notehead-dot sbd2 "semibrevis-c-dot" "5-stave" "notehead-semibrevis" "enharmonic-dot" 180 ,*glyph-height* 2 nil 0 :center)
    (glyph-notehead-dot sbd3 "semibrevis-d-dot" "5-stave" "notehead-semibrevis" "enharmonic-dot" 180 ,*glyph-height* 3 nil 0 :center)
    (glyph-notehead-dot sbd4 "semibrevis-e-dot" "5-stave" "notehead-semibrevis" "enharmonic-dot" 180 ,*glyph-height* 4 nil 0 :center)
    (glyph-notehead-dot sbd5 "semibrevis-f-dot" "5-stave" "notehead-semibrevis" "enharmonic-dot" 180 ,*glyph-height* 5 nil 0 :center)
    (glyph-notehead-dot sbd6 "semibrevis-g-dot" "5-stave" "notehead-semibrevis" "enharmonic-dot" 180 ,*glyph-height* 6 nil 0 :center)
    (glyph-notehead-dot sbd7 "semibrevis-h-dot" "5-stave" "notehead-semibrevis" "enharmonic-dot" 180 ,*glyph-height* 7 nil 0 :center)
    (glyph-notehead-dot sbd8 "semibrevis-i-dot" "5-stave" "notehead-semibrevis" "enharmonic-dot" 180 ,*glyph-height* 8 nil 0 :center)
    (glyph-notehead-dot sbd9 "semibrevis-j-dot" "5-stave" "notehead-semibrevis" "enharmonic-dot" 180 ,*glyph-height* 9 nil 0 :center)
    (glyph-notehead-dot sbd10 "semibrevis-k-dot" "5-stave" "notehead-semibrevis" "enharmonic-dot" 180 ,*glyph-height* 10 nil 0 :center)
    (glyph-notehead-stem m0 "minima-a" "5-stave" "notehead-semibrevis" "" "minima-stem" 180 ,*glyph-height* 0 :up nil 0 0.8)
    (glyph-notehead-stem m1 "minima-b" "5-stave" "notehead-semibrevis" "" "minima-stem" 180 ,*glyph-height* 1 :up nil 0 1.2)
    (glyph-notehead-stem m2 "minima-c" "5-stave" "notehead-semibrevis" "" "minima-stem" 180 ,*glyph-height* 2 :up nil 0 0.8)
    (glyph-notehead-stem m3 "minima-d" "5-stave" "notehead-semibrevis" "" "minima-stem" 180 ,*glyph-height* 3 :up nil 0 0.5)
    (glyph-notehead-stem m4 "minima-e" "5-stave" "notehead-semibrevis" "" "minima-stem" 180 ,*glyph-height* 4 :up nil 0 0.5)
    (glyph-notehead-stem m5 "minima-f" "5-stave" "notehead-semibrevis" "" "minima-stem" 180 ,*glyph-height* 5 :up nil 0 0.5)
    (glyph-notehead-stem m6 "minima-g" "5-stave" "notehead-semibrevis" "" "minima-stem" 180 ,*glyph-height* 6 :down nil 0 1)
    (glyph-notehead-stem m7 "minima-h" "5-stave" "notehead-semibrevis" "" "minima-stem" 180 ,*glyph-height* 7 :down nil 0)
    (glyph-notehead-stem m8 "minima-i" "5-stave" "notehead-semibrevis" "" "minima-stem" 180 ,*glyph-height* 8 :down nil 0)
    (glyph-notehead-stem m9 "minima-j" "5-stave" "notehead-semibrevis" "" "minima-stem" 180 ,*glyph-height* 9 :down nil 0)
    (glyph-notehead-stem m10 "minima-k" "5-stave" "notehead-semibrevis" "" "minima-stem" 180 ,*glyph-height* 10 :down nil 0)
    (glyph-notehead-stem sm0 "semiminima-a" "5-stave" "notehead-semibrevis-black" "" "minima-stem" 180 ,*glyph-height* 0 :up nil nil 0)
    (glyph-notehead-stem sm1 "semiminima-b" "5-stave" "notehead-semibrevis-black" "" "minima-stem" 180 ,*glyph-height* 1 :up nil nil 0)
    (glyph-notehead-stem sm2 "semiminima-c" "5-stave" "notehead-semibrevis-black" "" "minima-stem" 180 ,*glyph-height* 2 :up nil nil 0)
    (glyph-notehead-stem sm3 "semiminima-d" "5-stave" "notehead-semibrevis-black" "" "minima-stem" 180 ,*glyph-height* 3 :up nil nil 0)
    (glyph-notehead-stem sm4 "semiminima-e" "5-stave" "notehead-semibrevis-black" "" "minima-stem" 180 ,*glyph-height* 4 :up nil nil 0)
    (glyph-notehead-stem sm5 "semiminima-f" "5-stave" "notehead-semibrevis-black" "" "minima-stem" 180 ,*glyph-height* 5 :up nil nil 0)
    (glyph-notehead-stem sm6 "semiminima-g" "5-stave" "notehead-semibrevis-black" "" "minima-stem" 180 ,*glyph-height* 6 :down nil nil 0)
    (glyph-notehead-stem sm7 "semiminima-h" "5-stave" "notehead-semibrevis-black" "" "minima-stem" 180 ,*glyph-height* 7 :down nil nil 0)
    (glyph-notehead-stem sm8 "semiminima-i" "5-stave" "notehead-semibrevis-black" "" "minima-stem" 180 ,*glyph-height* 8 :down nil nil 0)
    (glyph-notehead-stem sm9 "semiminima-j" "5-stave" "notehead-semibrevis-black" "" "minima-stem" 180 ,*glyph-height* 9 :down nil nil 0)
    (glyph-notehead-stem sm10 "semiminima-k" "5-stave" "notehead-semibrevis-black" "" "minima-stem" 180 ,*glyph-height* 10 :down nil nil 0)
    (glyph-notehead-flag scr1u "semicroma-f-u" "5-stave" "notehead-semibrevis" "" "minima-stem" "semicroma-flag" 180 ,*glyph-height* 5 :up)
    (glyph-notehead-flag scr1d "semicroma-f-d" "5-stave" "notehead-semibrevis" "" "minima-stem" "semicroma-flag" 180 ,*glyph-height* 5 :down)
    (glyph-notehead-flag cr1u "croma-f-u" "5-stave" "notehead-semibrevis" "" "minima-stem" "croma-flag" 180 ,*glyph-height* 5 :up)
    (glyph-notehead-flag cr1d "croma-f-d" "5-stave" "notehead-semibrevis" "" "minima-stem" "croma-flag" 180 ,*glyph-height* 5 :down)
    (glyph-rest rm5 "rest-minima-c" "5-stave" "minima-semibrevis-rest" 150 ,*glyph-height* 5 :up)
    (glyph-rest rsm5 "rest-semiminima-c" "5-stave" "semiminima-rest" 150 ,*glyph-height* 5 :up)
    (glyph-rest rmaxima3 "rest-maxima-b" "5-stave" "maxima-rest" 80 ,*glyph-height* 3 :up)
    (glyph-sharp sh0 "sharp-0" "5-stave" "double-sharp" 120 ,*glyph-height* 0)
    (glyph-sharp sh1 "sharp-1" "5-stave" "double-sharp" 120 ,*glyph-height* 1)
    (glyph-sharp sh2 "sharp-2" "5-stave" "double-sharp" 120 ,*glyph-height* 2)
    (glyph-sharp sh3 "sharp-3" "5-stave" "double-sharp" 120 ,*glyph-height* 3)
    (glyph-sharp sh4 "sharp-4" "5-stave" "double-sharp" 120 ,*glyph-height* 4)
    (glyph-sharp sh5 "sharp-5" "5-stave" "double-sharp" 120 ,*glyph-height* 5)
    (glyph-sharp sh6 "sharp-6" "5-stave" "double-sharp" 120 ,*glyph-height* 6)
    (glyph-sharp sh7 "sharp-7" "5-stave" "double-sharp" 120 ,*glyph-height* 7)
    (glyph-sharp sh8 "sharp-8" "5-stave" "double-sharp" 120 ,*glyph-height* 8)
    (glyph-sharp sh9 "sharp-9" "5-stave" "double-sharp" 120 ,*glyph-height* 9)
    (glyph-sharp sh10 "sharp-10" "5-stave" "double-sharp" 120 ,*glyph-height* 10)
    (glyph-sharp ssh0 "single-sharp-0" "5-stave" "single-sharp" 120 ,*glyph-height* 0)
    (glyph-sharp ssh1 "single-sharp-1" "5-stave" "single-sharp" 120 ,*glyph-height* 1)
    (glyph-sharp ssh2 "single-sharp-2" "5-stave" "single-sharp" 120 ,*glyph-height* 2)
    (glyph-sharp ssh3 "single-sharp-3" "5-stave" "single-sharp" 120 ,*glyph-height* 3)
    (glyph-sharp ssh4 "single-sharp-4" "5-stave" "single-sharp" 120 ,*glyph-height* 4)
    (glyph-sharp ssh5 "single-sharp-5" "5-stave" "single-sharp" 120 ,*glyph-height* 5)
    (glyph-sharp ssh6 "single-sharp-6" "5-stave" "single-sharp" 120 ,*glyph-height* 6)
    (glyph-sharp ssh7 "single-sharp-7" "5-stave" "single-sharp" 120 ,*glyph-height* 7)
    (glyph-sharp ssh8 "single-sharp-8" "5-stave" "single-sharp" 120 ,*glyph-height* 8)
    (glyph-sharp ssh9 "single-sharp-9" "5-stave" "single-sharp" 120 ,*glyph-height* 9)
    (glyph-sharp ssh10 "single-sharp-10" "5-stave" "single-sharp" 120 ,*glyph-height* 10)
    (glyph-flat f5 "flat-5" "5-stave" "flat" 120 ,*glyph-height* 5 nil)
    (glyph-flat f2-9 "flat-2-9" "5-stave" "flat" 120 ,*glyph-height* 2 9)
    ))
