(defparameter *setzkasten-syntax* '((component-staff-lines
				     ((id "stave")
				      (number-of-lines 5)
				      (distance-between-lines 100)
				      (thickness 15)
				      (offset 10))
				     ((endings "round")))
				    (component-notehead
				     ((id "notehead")
				      (length-over-line 0.3)
				      (width 0.9)
				      (bold-stroke 27)
				      (light-stroke 13)
				      (oblique-p t)
				      (black nil))
				     ())
				    (component-dot
				     ((id "dot")
				      (size 0.2))
				     ())
				    (component-stem
				     ((id "stem")
				      (stem-length 2.3)
				      (width-head 1.8)
				      (width-tail 1.2))
				     ((dot-offset 0.5)))
				    (component-flag
				     ((id "flag")
				      (flag-thickness-bold 7)
				      (flag-thickness-light 4)
				      (flag-corner-level 0.25)
				      (flag-merge-level 0.6)
				      (flag-tail-p nil)
				      (flag-tail-level 0.8)
				      (flag-y-offset 0.5))
				     ())
				    (component-rest
				     ((id "rest")
				      (vertical-length 0.5)
				      (vertical-thickness 15)
				      (horizontal-length 0.3)
				      (horizontal-thickness 9)))
				    (component-sharp
				     ((id "sharp")
				      (thickness 3)
				      (size 1)
				      (double-p t)))
				    ;; more to add
				    (glyph-staff
				     ((id "glyph-staff")
				      (staff-component :instance)
				      (glyph-width 50)
				      (glyph-height 1500))
				     ((ink-color "black")))
				    (glyph-notehead
				     ((id "glyph-notehead")
				      (staff-component :instance)
				      (notehead-component :instance)
				      (glyph-width 50)
				      (glyph-height 1500)
				      (notehead-position 5))
				     ())
				    (glyph-notehead-dot
				     ((id "glyph-notehead-dot")
				      (staff-component :instance)
				      (notehead-component :instance)
				      (dot-component :instance)
				      (glyph-width 50)
				      (glyph-height 1500)
				      (notehead-position 5)
				      (dot-above-staff nil)
				      (dot-above-staff-offset 1)
				      (dot-alignment :center)))
				    (glyph-notehead-stem
				     ((id "glyph-notehead-stem")
				      (staff-component :instance)
				      (notehead-component :instance)
				      (dot-component :instance)
				      (stem-component :instance)
				      (glyph-width 50)
				      (glyph-height 1500)
				      (notehead-position 5)
				      (stem-direction :up)
				      (dot-above-staff nil)
				      (dot-above-staff-offset 1)
				      (dot-above-stem-offset 0.8))
				     ((dot-alignment :center)))
				    (glyph-notehead-flag
				     ((id "glyph-notehead-flag")
				      (staff-component :instance)
				      (notehead-component :instance)
				      (dot-component :instance)
				      (stem-component :instance)
				      (flag-component :instance)
				      (glyph-width 50)
				      (glyph-height 1500)
				      (notehead-position 5)
				      (stem-direction :up))
				     ((dot-above-staff nil)
				      (dot-above-staff-offset 0)
				      (dot-above-stem-offset 0)
				      (dot-alignment :center)))
				    (glyph-rest
				     ((id "glyph-rest")
				      (staff-component :instance)
				      (rest-component :instance)
				      (glyph-width 40)
				      (glyph-height 1500)
				      (rest-position 5)
				      (rest-direction :up)))
				    (glyph-sharp
				     ((id "glyph-sharp")
				      (staff-component :instance)
				      (sharp-component :instance)
				      (glyph-width 60)
				      (glyph-height 1500)
				      (sharp-position 5)))))


(defun print-setzkasten-syntax (syntax-definition)
  (mapc (lambda (el)
	  (format t "Element ~s:~&  Manually to define:~&~{    ~a~&~}~&  Predefined:~&~{    ~a~&~}~%"
		  (symbol-name (first el))
		  (mapcar (lambda (par)
			    (format nil "~a [~a]"
				    (symbol-name (first par))
				    (second par)))
			  (second el))
		  (mapcar (lambda (par)
			    (format nil "~a: ~s"
				    (symbol-name (first par))
				    (second par)))
			  (third el))))
	syntax-definition)
  nil)
