(defparameter *setzkasten-syntax* '((component-staff-lines
				     ((id "stave")
				      (number-of-lines 5)
				      (distance-between-lines 100)
				      (thickness 15)
				      (offset 10))
				     ((endings "round")))
				    (component-notehead
				     ((id "notehead")
				      (length-over-line 0.3)
				      (width 0.9)
				      (bold-stroke 27)
				      (light-stroke 13)
				      (oblique-p t)
				      (black nil))
				     ())
				    (component-dot
				     ((id "dot")
				      (size 0.2))
				     ())
				    (component-stem
				     ((id "stem")
				      (stem-length 2.3)
				      (width-head 1.8)
				      (width-tail 1.2))
				     ((dot-offset 0.5)))
				    (component-flag
				     ((id "flag")
				      (flag-thickness 7))
				     ())
				    ;; more to add
				    (glyph-staff
				     ((id "glyph-staff")
				      (staff-component :instance)
				      (glyph-width 50)
				      (glyph-height 1500))
				     ((ink-color "black")))
				    (glyph-notehead
				     ((id "glyph-notehead")
				      (staff-component :instance)
				      (notehead-component :instance)
				      (glyph-width 50)
				      (glyph-height 1500)
				      (notehead-position 5))
				     ())
				    (glyph-notehead-dot
				     ((id "glyph-notehead-dot")
				      (staff-component :instance)
				      (notehead-component :instance)
				      (dot-component :instance)
				      (glyph-width 50)
				      (glyph-height 1500)
				      (notehead-position 5)
				      (dot-above-staff nil)
				      (dot-above-staff-offset 1)
				      (dot-alignment :center)))
				    (glyph-notehead-stem
				     ((id "glyph-notehead-stem")
				      (staff-component :instance)
				      (notehead-component :instance)
				      (dot-component :instance)
				      (stem-component :instance)
				      (glyph-width 50)
				      (glyph-height 1500)
				      (notehead-position 5)
				      (stem-direction :up)
				      (dot-above-staff nil)
				      (dot-above-staff-offset 1)
				      (dot-above-stem-offset 0.8))
				     ((dot-alignment :center)))))
