`((:header
   (:filename "b1-c39-m1")
   (:alt-name "m1.048")
   (:comment "q021_s049, origin: 395")
   (:creator "Vicentino21 / Johannes Keller")
   (:title (:alt (:it "Essempio della quinta naturale incomposto")
                 (:de "")
                 (:en "")))
   (:section-headings
    (s1 (:alt (:it "prima quinta")
              (:de "")
              (:en "")))
    (s2 (:alt (:it "seconda quinta")
              (:de "")
              (:en "")))
    (s3 (:alt (:it "terza quinta")
              (:de "")
              (:en "")))
    (s4 (:alt (:it "quarta quinta")
              (:de "")
              (:en "")))
    (s5 (:alt (:it "prima quinta")
              (:de "")
              (:en "")))
    (s6 (:alt (:it "seconda quinta")
              (:de "")
              (:en "")))
    (s7 (:alt (:it "terza quinta")
              (:de "")
              (:en "")))
    (s8 (:alt (:it "quarta quinta")
              (:de "")
              (:en ""))))
   (:section-captions
    (s1 (:alt (:it "salto di quinta\\perfetta naturale\\incomposto")
              (:de "")
              (:en "")))
    (s2 (:alt (:it "salto di quinta\\perfetta naturale\\incomposto")
              (:de "")
              (:en "")))
    (s3 (:alt (:it "salto di quinta\\perfetta naturale\\incomposto")
              (:de "")
              (:en "")))
    (s4 (:alt (:it "salto di quinta\\perfetta naturale\\incomposto")
              (:de "")
              (:en "")))
    (s5 (:alt (:it "salto di quinta\\perfetta naturale\\incomposto")
              (:de "")
              (:en "")))
    (s6 (:alt (:it "salto di quinta\\perfetta naturale\\incomposto")
              (:de "")
              (:en "")))
    (s7 (:alt (:it "salto di quinta\\perfetta naturale\\incomposto")
              (:de "")
              (:en "")))
    (s8 (:alt (:it "salto di quinta\\perfetta naturale\\incomposto")
              (:de "")
              (:en "")))))
  (:data
   (:text 140 58
          (595 952 "ᴇſſempio della Quinta naturale incomp."))
   (:text 90 58
          (87 nil "prima 5.")
          (356 nil "ſeconda 5.")
          (655 nil "terza 5.")
          (925 nil "quarta 5.")
          (1248 nil "ʟe medeſime Ɋuinte diſcendenti."))
   (:music 2214
           (:voice v1)
           (:section s1)
           cclef7 b38 sb1 b38 b38 sb5 b38 bl
           (:section s2)
           b38 sb2 b38 b38 sb6 b38 bl
           (:section s3)
           b38 sb3 b38 b38 sb7 b38 bl
           (:section s4)
           b38 sb4 b38 b27 sb8 b38 bl
           (:section s5)
           (:newline)
           b38 sb8 b38 sb4 b38 bl
           (:section s6)
           b38 sb7 b38 sb3 b38 bl
           (:section s7)
           b38 sb6 b38 sb2 b38 bl
           (:section s8)
           b38 sb5 b38 sb1 b38 bl)
   (:text 70 58
          (96 nil "ſalto di 5.")
          (369 nil "ſalto di 5.")
          (653 nil "ſal. di quin.")
          (943 nil "ſalto di 5.")
          (1203 nil "ſal. di 5.")
          (1444 nil "ſal. di 5.")
          (1684 nil "ſalto di 5.")
          (1953 nil "ſalto di 5."))
   (:text 70 58
          (107 nil "ꝑfet. nat.")
          (368 nil "ꝑfet. nat.")
          (652 nil "perfet.nat.")
          (955 nil (:alt (:diplomatic "ꝑſet. nat.")
                         (:idealised "ꝑfet. nat.")
                         (:comment "") (:flag :draft) (:id 1)))
          (1228 nil "ꝑfet.na.")
          (1446 nil "ꝑfet.nat.")
          (1686 nil "ꝑfet. nat.")
          (1959 nil "ꝑfet.nat."))
   (:text 70 58
          (100 nil "incomp.")
          (368 nil "incomp.")
          (641 nil "incomp.")
          (955 nil "incomp.")
          (1216 nil "incomp.")
          (1439 nil "incomp.")
          (1684 nil "incomp.")
          (1962 nil "incomp."))))
