`((:header
   (:filename "b1-c05-m2")
   (:alt-name "m1.004")
   (:comment "q021_s022, origin: 1023")
   (:creator "Vicentino21 / Johannes Keller")
   (:title (:alt (:it "Dimostratione della mano cromatica, ascendente, con li semitoni minore,\\e con l'essempio")
                 (:de "Darstellung der chromatischen Hand, aufsteigend, mit den semitoni minori,\\und mit dem Beispiel")
                 (:en "Illustration of the ascending chromatic hand, with the semitoni minori, and with an example")))
   (:section-headings
    (s1 (:alt (:it "Alamire")
              (:de "Alamire")
              (:en "Alamire")))
    (s2 (:alt (:it "Bmi")
              (:de "Bmi")
              (:en "Bmi")))
    (s3 (:alt (:it "Csolfaut")
              (:de "Csolfaut")
              (:en "Csolfaut")))
    (s4 (:alt (:it "Dlasolre")
              (:de "Dlasolre")
              (:en "Dlasolre")))
    (s5 (:alt (:it "Elami")
              (:de "Elami")
              (:en "Elami")))
    (s6 (:alt (:it "Ffaut")
              (:de "Ffaut")
              (:en "Ffaut")))
    (s7 (:alt (:it "Gsolreut")
              (:de "Gsolreut")
              (:en "Gsolreut")))))
  (:preamble-lilypond
   (:lyrics
    (s1 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per n:\" } la [la]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per n:\" } la [la]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in n:\" } la [la]")))
    (s1 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } mi [mi]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } mi [mi]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } mi [mi]")))
    (s1 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } re [re]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } re [re]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } re [re]")))

    (s2 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } mi [mi]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } mi [mi]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } mi [mi]")))

    (s3 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per n:\" } ut [ut]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per n:\" } ut [ut]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in n:\" } ut [ut]")))
    (s3 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } sol [sol]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } sol [sol]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } sol [sol]")))
    (s3 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } fa [fa]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } fa [fa]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } fa [fa]")))

    (s4 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } la [la]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } la [la]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } la [la]")))
    (s4 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } sol [sol]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } sol [sol]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } sol [sol]")))
    (s4 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per n:\" } re [re]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per n:\" } re [re]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in n:\" } re [re]")))

    (s5 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } la [la]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } la [la]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } la [la]")))
    (s5 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per n:\" } mi [mi]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per n:\" } mi [mi]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in n:\" } mi [mi]")))

    (s6 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per n:\" } fa [fa]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per n:\" } fa [fa]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in n:\" } fa [fa]")))
    (s6 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } ut [ut]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } ut [ut]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } ut [ut]")))

    (s7 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per n:\" } sol [sol]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per n:\" } sol [sol]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in n:\" } sol [sol]")))
    (s7 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } re [re]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } re [re]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } re [re]")))
    (s7 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } ut [ut]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } ut [ut]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } ut [ut]")))
    ))
  (:data
   (:text 70 58
     (90 1974 "ᴅimoſtratione della ᴍano ᴄromatica, aſcendente, con li ꜱemitoni minori, e con l'eſſempio."))
   (:text 100 58
     (41 nil "ᴀ lamire")
     (366 nil "ʙ mi")
     (680 nil "ᴄ ſolfaut")
     (1002 nil "ᴅ laſolre")
     (1301 nil "ᴇ lami")
     (1613 nil "ꜰ faut")
     (1919 nil "ɢ ſolreut"))
   (:music 2193
           (:voice v1)
           (:section s1)
           b22 (:f-clef) max7 fclef7 b22 sb2 sh2 b22 sb2 b22 bl
           (:section s2)
           b22 sb3 b22 sh3 b22 sb3 b22 bl
           (:section s3)
           b22 sb4 b22 sh4 b22 sb4 b22 bl
           (:section s4)
           b22 sb5 b38 sh5 b38 sb5 b22 bl
           (:section s5)
           b22 sb6 b38 sh6 b38 sb6 b22 bl
           (:section s6)
           b22 sb7 b38 sh7 b38 sb7 b22 bl
           (:section s7)
           b22 sb8 b22 sh8 b22 sb8 b22 bl b38)
   (:text 60 58
     (43 nil "la") (121 nil "mi") (206 nil "re")
     (345 nil "mi")
     ;; Korrektur Anne: "per natura: ut, per ♭: sol und per ♮: fa"
     ;;
     ;; DONE
     (653 nil
          (:alt (:diplomatic "ſol")
                (:critical "ut")
                (:coord-barre "TZ3 TE3")
                (:coord-norm "G3 US")
                (:comment "Original erste Silbe: »ſol [fa ut]«.")
                (:flag :ready) (:id 1)))
     (740 nil
          (:alt (:diplomatic "fa")
                (:critical "sol")
                (:coord-barre "TZ3 TE3")
                (:coord-norm "G3 US")
                (:comment "Original zweite Silbe: »[ſol] fa [ut]«.")
                (:flag :ready) (:id 2)))
     (835 nil
          (:alt (:diplomatic "ut")
                (:critical "fa")
                (:coord-barre "TZ3 TE3")
                (:coord-norm "G3 US")
                (:comment "Original dritte Silbe: »[ſol fa] ut«.")
                (:flag :ready) (:id 3)))
     (959 nil "la") (1044 nil "ſol") (1141 nil "re")
     (1279 nil "la") (1363 nil "mi")
     (1567 nil "fa") (1676 nil "ut")
     (1902 nil "ſol") (1999 nil "re") (2075 nil "ut"))
   (:text 100 58
     (0 nil "per nat.ꝑ ♭.ꝑ ♮.")
     (431 nil "per ♮.")
     (569 nil "per n. ꝑ ♭. ꝑ ♮")
     (959 nil "ꝑ ♭. ꝑ ♮. ꝑ n.")
     (1309 nil "ꝑ ♮. ꝑ nat.")
     (1554 nil "per nat.ꝑ ♭.")
     (1855 nil "ꝑ n. ꝑ ♭. ꝑ ♮."))))
