`((:header
   (:filename "b1-c10-m2")
   (:alt-name "m1.017")
   (:comment "q021_s030, origin: 999")
   (:creator "Vicentino21 / Johannes Keller")
   (:section-captions
    (s1 (:alt (:it "spetie cromatica\\semitono cromatico")
              (:de "")
              (:en "chromatic species\\chromatic semitono")))
    (s2 (:alt (:it "spetie cromatica\\tono cromatico")
              (:de "")
              (:en "chromatic species\\chromatic tono")))
    (s3 (:alt (:it "spetie cromatica\\semitono cromatico")
              (:de "")
              (:en "chromatic species\\chromatic semitono")))
    (s4 (:alt (:it "spetie cromatica\\semitono cromatico")
              (:de "")
              (:en "chromatic species\\chromatic semitono")))
    (s5 (:alt (:it "spetie cromatica\\semitono cromatico")
              (:de "")
              (:en "chromatic species\\chromatic semitono")))
    (s6 (:alt (:it "spetie cromatica\\tono cromatico")
              (:de "")
              (:en "chromatic species\\chromatic tono")))
    (s7 (:alt (:it "spetie cromatica\\semitono cromatico")
              (:de "")
              (:en "chromatic species\\chromatic semitono")))
    (s8 (:alt (:it "spetie cromatica\\semitono cromatico")
              (:de "")
              (:en "chromatic species\\chromatic semitono")))
    (s9 (:alt (:it "spetie cromatica\\tono cromatico")
              (:de "")
              (:en "chromatic species\\chromatic tono")))))
  (:data
   (:music 2214
           (:voice v1)
           (:section s1)
           cclef7 b22 sb1 b38 fl2 b22 sb2 bl
           (:section s2)
           sb2 b22 sh3 b22 sb3 bl
           (:section s3)
           sb3 b22 fl4 b22 sb4 bl
           (:section s4)
           sb4 b22 fl5 b22 sb5 bl
           (:section s5)
           (:alt (:diplomatic sb5 b22 sh4 b22 sb4)
                 (:critical sb5 b22 fl6 b22 sb6)
                 (:coord-barre "N9-N10")
                 (:coord-norm "G5 N1-N2")
                 (:comment "Original A–G♯. Redundanz zu Section 7.")
                 (:flag :ready) (:id 1))
           bl
           (:section s6)
           (:newline)
           b22 sb7 b22 fl6 b22 sb6 bl
           (:section s7)
           sb5 b22 sh4 b22 sb4 bl
           (:section s8)
           sb4 b22 sh3 b22 sb3 bl
           (:section s9)
           sb3 b22 fl2 b22 sb2 bl)
   (:text 70 58
          (30 nil "ſpetie cro.")
          (300 nil "ſpet. cro.")
          (542 nil "ſpet.cro.")
          (746 nil "ſpet. cro.")
          (986 nil "ſpet.cro.")
          (1224 nil "ſpet. cro.")
          (1468 nil "ſpet. cro.")
          (1700 nil "ſpet. cro.")
          (1950 nil "ſpet.cro."))
   (:text 70 58
          (44 nil (:alt (:diplomatic "tono cro.")
                        (:critical "ſe.tono cro.")
                        (:coord-barre "TZ2 TE1")
                        (:coord-norm "G1 US Z2")
                        (:comment "Original: »tono cro.«, im Notentext wird jedoch ein /semitono cromatico/ gezeigt.")
                        (:flag :ready) (:id 2)))
          (316 nil "to. crom.")
          (550 nil "ſem.cro.")
          (750 nil "ſem. cro.")
          (998 nil "ſem.cro.")
          (1228 nil "tono cro.")
          (1468 nil "ſem. cro.")
          (1704 nil "ſem. cro.")
          (1956 nil "tono cro."))))
