`((:header
   (:filename "b1-c11-m2")
   (:alt-name "m1.019")
   (:comment "q021_s031, origin: 1273")
   (:creator "Vicentino21 / Johannes Keller")
   (:section-headings
    (s1 (:alt (:it "tono diviso in 4 parti\\ascendenti")
              (:de "")
              (:en "tono divided in 4\\ascending parts")))
    (s2 (:alt (:it "tono diviso in 4 parti\\ascendenti")
              (:de "")
              (:en "tone divided in 4\\ascending parts"))))
   (:section-captions
    (s1 (:alt (:it "per ♮: ut-re-mi-fa-re")
              (:de "")
              (:en "per ♮: ut-re-mi-fa-re")
              (:comment "»per ♮:« analog zu b1-c11-m1 ergänzt.")
              (:flag :redundant) (:id 5)))
    (s2 (:alt (:it "per ♭: re-mi-fa-re-mi")
              (:de "")
              (:en "per ♭: re-mi-fa-re-mi")
              (:comment "»per ♭:« analog zu b1-c11-m1 ergänzt.")
              (:flag :redundant) (:id 6)))))
  (:data
   (:text 90 58
          (36 691 "Tono diuiſo in 4. parti aſcen.")
          (754 650 "To.diuiſo in 4. parti aſcen."))
   (:music 1400
           (:voice v1)
           (:section s1)
           cclef7 b38 sb4 b38 sbd4 b22 sh4 b22
           (:alt (:diplomatic sbd4)
                 (:idealised sb4)
                 (:coordinate-a-b "3. N")
                 (:coordinate-c "S1, 3.N")
                 (:comment "Original: Ġ♯. Begründungen: Vicentino notiert diese Tonhöhe stets als A♭. Darüber hinaus wurde die Ganztonteilung mit A♭ bereits im vorhergehenden Beispiel (b1-c11-m1) behandelt.")
                 (:flag :ready) (:id 1))
           b38 fl5 b38 sbd5 b38 sb5 b38
           (:section s2)
           cclef7
           (:alt (:diplomatic b38)
                 (:idealised fl6 (:key-signature nil nil nil nil nil nil :flat))
                 (:coordinate-a-b "Schlüssel vor 6. N")
                 (:coordinate-c "Schlüssel in S2")
                 (:comment "♭-Vorzeichnung ergänzt, analog zu b1-c11-m1.")
                 (:flag :ready) (:id 2))
           sb4 b38 sbd4 b38 sh4 b22 sb4 b38 fl5 b38 sbd5 b38 sb5 bl)
   (:text 90 58
          (:alt (:diplomatic)
                (:idealised (0 nil "ꝑ ♮."))
                (:coordinate-a-b "TE unter NZ, Beginn")
                (:coordinate-c "Beginn Unterschrift S1")
                (:comment "»ꝑ ♮.« bzw. »per ♮« ergänzt, um die inhaltlich naheliegende Symmetrie zu b1-c11-m1 herzustellen.")
                (:flag :ready) (:id 3))
          (113 nil "ut")
          (203 nil "re")
          (344 nil "mi")
          (517 nil "fa")
          (604 nil "re")
          (:alt (:diplomatic)
                (:idealised (700 nil "ꝑ ♭."))
                (:coordinate-a-b "TE unter NZ, vor 3. »re«")
                (:coordinate-c "Beginn Unterschrift S2")
                (:comment "»ꝑ ♭.« bzw. »per ♭« ergänzt, um die inhaltlich naheliegende Symmetrie zu b1-c11-m1 herzustellen.")
                (:flag :ready) (:id 4))
          (801 nil "re")
          (890 nil "mi")
          (1058 nil "fa")
          (1206 nil "re")
          (1295 nil "mi"))))
