`((:header
   (:filename "b1-c15-m1")
   (:alt-name "m1.023")
   (:comment "q021_s035, origin: 377")
   (:creator "Vicentino21 / Johannes Keller")
   (:title (:alt (:it "Essempio delli gradi delli diesis minori enarmonici, ascendenti et discendenti.")
                 (:de "Beispiel der Tonschritte der diesis minori enarmonici, aufsteigend und absteigend.")
                 (:en "Example of the steps of the diesis minori enarmonici, ascending and descending")))
   (:section-captions
    (s1 (:alt (:it "diesis minore")
              (:de "diesis minore")
              (:en "diesis minore")))
    (s2 (:alt (:it "diesis minore")
              (:de "diesis minore")
              (:en "diesis minore")))
    (s3 (:alt (:it "diesis minore")
              (:de "diesis minore")
              (:en "diesis minore")))
    (s4 (:alt (:it "diesis minore")
              (:de "diesis minore")
              (:en "diesis minore")))
    (s5 (:alt (:it "diesis minore")
              (:de "diesis minore")
              (:en "diesis minore")))
    (s6 (:alt (:it "diesis minore")
              (:de "diesis minore")
              (:en "diesis minore")))
    (s7 (:alt (:it "diesis minore")
              (:de "diesis minore")
              (:en "diesis minore")))
    (s8 (:alt (:it "diesis minore")
              (:de "diesis minore")
              (:en "diesis minore")))))
  (:data
   (:text 90 58
          (212 1795 "ᴇſſempio delli gradi,delli ᴅieſis minori ᴇnarmonici, aſcendenti & diſcendenti."))
   (:music 2207
           (:voice v1)
           (:section s1)
           cclef7 b38 sb4 b27 b38 b27 sbd4 b38 b27 b22 bl
           (:section s2)
           b38 sb6 b38 sbd6 b22 b22 bl
           (:section s3)
           b38 sb7 b38 sbd7 b38 bl
           (:section s4)
           b38 sb8 b38 sbd8 b38 bl
           (:section s5)
           b38
           (:alt (:diplomatic sb5 b38 sbd5)
                 (:critical sbd5 b38 sb5)
                 (:coord-barre "N9-10")
                 (:coord-norm "G5")
                 (:comment "Original: A–Ȧ.")
                 (:flag :ready) (:id 1))
           b38 bl
           (:section s6)
           b38 b22
           (:alt (:diplomatic sb4 b38 sbd4)
                 (:critical sbd4 b38 sb4)
                 (:coord-barre "N11-12")
                 (:coord-norm "G6")
                 (:comment "Original: G–Ġ.")
                 (:flag :ready) (:id 2))
           b38 bl
           (:section s7)
           b38
           (:alt (:diplomatic sb3 b38 sbd3)
                 (:critical sbd3 b38 sb3)
                 (:coord-barre "N13-14")
                 (:coord-norm "G7")
                 (:comment "Original: F–Ḟ.")
                 (:flag :ready) (:id 3))
           b22 bl
           (:section s8)
           b22
           (:alt (:diplomatic sb2 b38 sbd2)
                 (:critical sbd2 b38 sb2)
                 (:coord-barre "N15-16")
                 (:coord-norm "G8")
                 (:comment "Original: E–Ė.")
                 (:flag :ready) (:id 4))
           b38 bl)
   (:text 70 58
          (46 nil "ᴅieſis minore")
          (412 nil "ᴅi.min.")
          (664 nil "ᴅi.min.")
          (916 nil "ᴅi. min.")
          (1171 nil "ᴅi. min.")
          (1421 nil "ᴅi. min.")
          (1703 nil "ᴅi. min.")
          (1943 nil "ᴅi.min."))))
