;; JK: Luigi möchte die Silben in einer einzigen vertikalen Kolonne mit sechs Zeilen sehen, Anne
;; möchte die zweizeilige Anordnung der Silben (wie im Original gedruckt) aufrecht erhalten. Zur
;; Zeit besteht kein Konsens.
;;
;; OPEN

`((:header
   (:filename "b1-c05-m3")
   (:alt-name "m1.005")
   (:comment "q021_s023, origin: 378")
   (:creator "Vicentino21 / Johannes Keller")
   (:title (:alt (:it "Dimostratione della mano cromatica con li semitoni maggiori ascendenti")
                 (:de "Darstellung der chromatischen Hand mit den aufsteigenden semitoni maggiori")
                 (:en "Illustration of the chromatic hand with the ascending semitoni maggiori")))
   (:section-headings
    (s1 (:alt (:it "Alamire")
              (:de "Alamire")
              (:en "Alamire")))
    (s2 (:alt (:it "Bfabmi")
              (:de "Bfabmi")
              (:en "Bfabmi")))
    (s3 (:alt (:it "B et C")
              (:de "B und C")
              (:en "B and C")))
    (s4 (:alt (:it "Csolfaut")
              (:de "Csolfaut")
              (:en "Csolfaut")))
    (s5 (:alt (:it "Dlasolre")
              (:de "Dlasolre")
              (:en "Dlasolre")))
    (s6 (:alt (:it "Elami")
              (:de "Elami")
              (:en "Elami")))
    (s7 (:alt (:it "Ffaut")
              (:de "Ffaut")
              (:en "Ffaut")))))
  (:preamble-lilypond
   (:lyrics
    (s1 v1 (:alt (:it "\\set stanza = \\markup{ \\column { \\vspace #1.23 \\line { \\normal-text \"per ɴ,\" } \\line { \\normal-text \"per ♭,\" } \\line { \\normal-text \"per ♮:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } la")
                 (:de "\\set stanza = \\markup{ \\column { \\vspace #1.23 \\line { \\normal-text \"per ɴ,\" } \\line { \\normal-text \"per ♭,\" } \\line { \\normal-text \"per ♮:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } la")
                 (:en "\\set stanza = \\markup{ \\column { \\vspace #1.23 \\line { \\normal-text \"in ɴ,\" } \\line { \\normal-text \"in ♭,\" } \\line { \\normal-text \"in ♮:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } la")))
    (s1 v1 "mi")
    (s1 v1 "re")
    (s1 v1 "ut")
    (s1 v1 "fa")
    (s1 v1 "sol")

    (s2 v1 (:alt (:it "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"per ♭,\" } \\line { \\normal-text \"per ɴ:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } fa")
                 (:de "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"per ♭,\" } \\line { \\normal-text \"per ɴ:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } fa")
                 (:en "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"in ♭,\" } \\line { \\normal-text \"in ɴ:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } fa")))
    (s2 v1 "mi")
    (s2 v1 "la")
    (s2 v1 "sol")
    (s2 v1 "re")
    (s2 v1 "ut")

    (s3 v1 (:alt (:it "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"per ♮,\" } \\line { \\normal-text \"per ɴ:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } mi")
                 (:de "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"per ♮,\" } \\line { \\normal-text \"per ɴ:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } mi")
                 (:en "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"in ♮,\" } \\line { \\normal-text \"in ɴ:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } mi")))
    (s3 v1 "fa")
    (s3 v1 "sol")
    (s3 v1 "la")
    (s3 v1 "re")
    (s3 v1 "ut")

    (s4 v1 (:alt (:it "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"per ɴ,\" } \\line { \\normal-text \"per ♭:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } sol")
                 (:de "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"per ɴ,\" } \\line { \\normal-text \"per ♭:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } sol")
                 (:en "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"in ɴ,\" } \\line { \\normal-text \"in ♭:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } sol")))
    (s4 v1 "fa")
    (s4 v1 "ut")
    (s4 v1 "re")
    (s4 v1 "mi")
    (s4 v1 "la")

    (s5 v1 (:alt (:it "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"per ɴ,\" } \\line { \\normal-text \"per ♭:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } la")
                 (:de "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"per ɴ,\" } \\line { \\normal-text \"per ♭:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } la")
                 (:en "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"in ɴ,\" } \\line { \\normal-text \"in ♭:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } la")))
    (s5 v1 "sol")
    (s5 v1 "re")
    (s5 v1 "fa")
    (s5 v1 "mi")
    (s5 v1 "ut")

    (s6 v1 (:alt (:it "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"per ɴ,\" } \\line { \\normal-text \"per ♮:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } la")
                 (:de "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"per ɴ,\" } \\line { \\normal-text \"per ♮:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } la")
                 (:en "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"in ɴ,\" } \\line { \\normal-text \"in ♮:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } la")))
    (s6 v1 "mi")
    (s6 v1 "fa")
    (s6 v1 "ut")
    (s6 v1 "re")
    (s6 v1 "sol")

    (s7 v1 (:alt (:it "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"per ɴ,\" } \\line { \\normal-text \"per ♭:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } fa")
                 (:de "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"per ɴ,\" } \\line { \\normal-text \"per ♭:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } fa")
                 (:en "\\set stanza = \\markup{ \\column { \\vspace #1.83 \\line { \\normal-text \"in ɴ,\" } \\line { \\normal-text \"in ♭:\" } } \\lower #6.2 \\override #'(font-encoding . fetaBraces) \\lookup \"brace210\" } fa")))
    (s7 v1 "ut")
    (s7 v1 "re")
    (s7 v1 "mi")
    (s7 v1 "sol")
    (s7 v1 "la")
    ))
  (:data
   (:text 70 58 (231 1648 "ᴅimoſtratione della ᴍano ᴄromatica con li ſemitoni maggiori aſcendenti."))
   (:text 100 58
     (42 nil "ᴀ la mire")
     (287 nil "ʙ fa ♭ mi")
     (622 nil "ʙ et ᴄ")
     (866 nil "ᴄ ſol fa ut")
     (1202 nil "ᴅ la ſol re")
     (1527 nil "ᴇ la mi")
     (1778 nil "ꜰ fa ut"))
   (:music 2200
           (:voice v1)
           (:section s1)
           b38 (:f-clef) max7 fclef7 b38 sb2 b38 bl
           (:section s2)
           fl3 b38 sb3 b38 nat3 b38 sbd3 bl
           (:section s3)
           b38 sb3 b38 sb4 b38 bl
           (:section s4)
           b38 sb4 b38 fl5 b38 sb5 b38 bl
           (:section s5)
           b38 sb5 b38 fl6 b38 sb6 b38 bl
           (:section s6)
           b38 sb6 b38 sb7 b38 bl
           (:section s7)
           b38 sb7 b38 fl8 b38 sb8 b38 bl b70)
   (:text 70 58
     (:alt (:diplomatic)
           (:critical)
           (:coord-barre "allg.")
           (:coord-norm "allg.")
           (:comment "Das Zeichen ɴ wird als Abkürzung für _natura_ verwendet.")
           (:flag :ready) (:id 1))
     (43 nil "la") (126 nil "mi re")
     (288 nil "fa") (391 nil "mi")
     (619 nil "mi fa ſol")
     (872 nil "ſol fa ut")
     (1204 nil "la ſol re")
     (1541 nil "la mi fa")
     (1794 nil "fa ut re"))
   (:text 70 58
     (43 nil "ut fa ſol")
     (295 nil "la ſol re ut")
     (635 nil "la re ut")
     (883 nil "re mi la")
     (1195 nil "fa mi ut")
     (1542 nil "ut re ſol")
     (1799 nil "mi ſol la"))
   (:text 70 58
     (5 309 "ꝑ n. ꝑ ♭.ꝑ ♮.")
     (325 218 "ꝑ ♭. ꝑ ♮.")
     (644 480 "per ♮.ꝑ n. ꝑ n. ꝑ ♭.")
     (1198 220 "ꝑ n. ꝑ ♭.")
     (1542 227 "ꝑ n. ꝑ ♮.")
     (1807 213 "ꝑ n.ꝑ ♭."))))
