`((:header
   (:filename "b1-c05-m8")
   (:alt-name "m1.010")
   (:comment "q021_s025, origin: 502")
   (:creator "Vicentino21 / Johannes Keller")
   (:title (:alt (:it "Mano enarmonica, con semitoni maggiori discendenti nel principio del tono,\\con il tono, in quattro parti diviso, per le sette lettere della mano.")
                 (:de "")
                 (:en "Enharmonic hand, with descending semitoni maggiori at the beginning of the tono,\\with the tono divided into four parts by the seven letters of the hand")))
   (:section-headings
    (s1 (:alt (:it "da A a G")
              (:de "")
              (:en "from A to G")))
    (s2 (:alt (:it "[da G a F]")
              (:de "")
              (:en "from G to F")))
    (s3 (:alt (:it "da F a E")
              (:de "")
              (:en "from F to E")))
    (s4 (:alt (:it "da E a D")
              (:de "")
              (:en "from E to D")))
    (s5 (:alt (:it "da D a C")
              (:de "")
              (:en "from D to C")))
    (s6 (:alt (:it "da C a B")
              (:de "")
              (:en "from C to B")))
    (s7 (:alt (:it "da B a A")
              (:de "")
              (:en "from B to A"))))
   (:section-captions
    (s1 (:alt (:it "mi e re per ascendere")
              (:de "")
              (:en "mi and re in ascent")))
    (s2 (:alt (:it "[re ascendente]")
              (:de "")
              (:en "[re in ascent]")))
    (s4 (:alt (:it "mi per ascendere")
              (:de "")
              (:en "mi in ascent")))
    (s5 (:alt (:it "re per ascendere")
              (:de "")
              (:en "re in ascent")))
    (s6 (:alt (:it "[per ascendere]")
              (:de "")
              (:en "[in ascent]")))))
  (:preamble-lilypond
   (:lyrics
    ;; JK: Im Auge zu behalten: die Silben werden standardmässig kleiner gesetzt als die "per
    ;; x:"-Angaben und die 'captions'. Das müsste in der lilypond-backend-Implementierung angepasst
    ;; werden, falls die Unterschiedlichkeit der Schriftgrössen nicht akzeptabel sein sollte.
    ;;
    ;; OPEN
    (s1 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } la sol fa la sol")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } la sol fa la sol")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in nat.:\" } la sol fa la sol")))
    (s2 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"[per nat:\" } sol fa la sol fa]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"[per nat:\" } sol fa la sol fa]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"[in nat:\" } sol fa la sol fa]")))
    (s3 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } fa mi la")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } fa mi la")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in nat.:\" } fa mi la")))
    (s3 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"[ascendente\" } fa mi mi]")
                 (:de "\\set stanza = \\markup{ \\normal-text \"[aufsteigend\" } fa mi mi]")
                 (:en "\\set stanza = \\markup{ \\normal-text \"[in ascent\" } fa mi mi]")))
    (s4 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } la sol fa mi re")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } la sol fa mi re")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } la sol fa mi re")))
    (s4 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"\" } la sol fa la sol")
                 (:de "\\set stanza = \\markup{ \\normal-text \"\" } la sol fa la sol")
                 (:en "\\set stanza = \\markup{ \\normal-text \"\" } la sol fa la sol")))
    (s5 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } la sol fa la sol")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } la sol fa la sol")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } la sol fa la sol")))
    (s5 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } sol fa la sol fa")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } sol fa la sol fa")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } sol fa la sol fa")))
    (s6 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } fa mi mi")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } fa mi mi")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in nat.:\" } fa mi mi")))
    (s7 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } fa mi la")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } fa mi la")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } fa mi la")))
    (s7 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"[ascendente]\" } fa mi mi")
                 (:de "\\set stanza = \\markup{ \\normal-text \"[aufsteigend]\" } fa mi mi")
                 (:en "\\set stanza = \\markup{ \\normal-text \"[in ascent]\" } fa mi mi")))))
  (:data
   (:text 70 58 (0 2198 "ᴍano ᴇnarmonica , con ſemitoni maggiori diſcendenti nel principio del tono,con il tono, in quattro"))
   (:text 70 58 (0 976 "parti diuiſo , per leſette lettere della ᴍano."))
   (:text 110 58
     (130 nil "da ᴀ.")
     (364 nil "à ɢ.")
     (525 nil
          (:alt (:diplomatic "")
                (:critical "da ɢ.")
                (:coord-barre "TZ3 TE3")
                (:coord-norm "G2 ÜS")
                (:comment "Dieser Text (»da ɢ.«) wurde ergänzt.")
                (:flag :ready) (:id 1)))
     (750 nil
          (:alt (:diplomatic "")
                (:critical "à ꜰ.")
                (:coord-barre "TZ3 TE3")
                (:coord-norm "G2 ÜS")
                (:comment "Dieser Text (»à ꜰ.«) wurde ergänzt.")
                (:flag :ready) (:id 2)))
     ((:alt (:diplomatic 516)
            (:critical 910)
            (:coord-barre "TZ3 TE5")
            (:coord-norm "–")
            (:comment "Dieser Text (»da ꜰ.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 3))
      nil "da ꜰ.")
     ((:alt (:diplomatic 660)
            (:critical 1030)
            (:coord-barre "TZ3 TE6")
            (:coord-norm "–")
            (:comment "Dieser Text (»à ᴇ.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 4))
      nil "à ᴇ.")
     ((:alt (:diplomatic 794)
            (:critical 1150)
            (:coord-barre "TZ3 TE7")
            (:coord-norm "–")
            (:comment "Dieser Text (»da ᴇ.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 5))
      nil "da ᴇ.")
     ((:alt (:diplomatic 1010)
            (:critical 1400)
            (:coord-barre "TZ3 TE8")
            (:coord-norm "–")
            (:comment "Dieser Text (»à ᴅ.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 6))
      nil "à ᴅ.")
     ((:alt (:diplomatic 1234)
            (:critical 1530)
            (:coord-barre "TZ3 TE9")
            (:coord-norm "–")
            (:comment "Dieser Text (»da ᴅ.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 7))
      nil "da ᴅ.")
     ((:alt (:diplomatic 1478)
            (:critical 1800)
            (:coord-barre "TZ3 TE10")
            (:coord-norm "–")
            (:comment "Dieser Text (»à ᴄ.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 8))
      nil "à ᴄ.")
     ((:alt (:diplomatic 1630)
            (:critical 1920)
            (:coord-barre "TZ3 TE11")
            (:coord-norm "–")
            (:comment "Dieser Text (»da ᴄ. à ʙ.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 9))
      234 "da ᴄ. à ʙ.")
     ((:alt (:diplomatic 1916)
            (:critical 2200)
            (:coord-barre "TZ3 TE12")
            (:coord-norm "–")
            (:comment "Dieser Text (»da ʙ. à ᴀ.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 10))
      238 "da ʙ. à ᴀ."))
   (:music
    (:alt (:diplomatic 2198)
          (:critical 2450)
          (:coord-barre "MZ")
          (:coord-norm "–")
          (:comment "Die Breite der Notenzeile wurde angepasst, um die Ergänzung von N6-N10 zu ermöglichen.")
          (:flag :ready) (:id 11))
    (:voice v1)
           (:section s1) (:f-clef) max7 fclef7 b22 sb9 fl9 sbd9 sh8 sb8 b22 sbd8 b22 sb8 bl

           (:alt (:diplomatic)
                 (:critical (:section s2) sb8 fl8 sbd8 sh7 sb7 sbd7 sb7 bl)
                 (:coord-barre "N6-N10")
                 (:coord-norm "G2 N1-N5")
                 (:comment "Der Schritt von G zu F existiert im Original nicht, ist aber inhaltlich plausibel.")
                 (:flag :ready) (:id 12))
           (:section s3) sb7 b22 sbd6 b22 sb6 bl
           (:section s4) sb6 fl6 sbd6 sh5 sb5 b22 sbd5 b22 sb5 bl
           (:section s5) (:newline) sb5 fl5 sbd5 sh4 sb4 b22 sbd4 b22 sb4 bl
           (:section s6) sb4 b22 sbd3 b22 sb3 bl
           (:section s7) fl3 sb3 b22 sbd2 b22 sb2 b22 bl)
   (:text 70 58
     (10 440 "ꝑ n. la.ſol.fa.la.ſol.")
     (454 420
          (:alt (:diplomatic "")
                (:critical "ꝑ n. ſol.fa.la.ſol.fa.")
                (:coord-barre "TZ4 TE2")
                (:coord-norm "G2 US")
                (:comment "Dieser Text (»ꝑ n. ſol.fa.la.ſol.fa.«) wurde ergänzt.")
                (:flag :ready) (:id 13)))
     ((:alt (:diplomatic 494)
            (:critical 890)
            (:coord-barre "TZ4 TE3")
            (:coord-norm "–")
            (:comment "Dieser Text (»ꝑ n.fa.mi.la.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 14))
      274 "ꝑ n.fa.mi.la.")
     ((:alt (:diplomatic 782)
            (:critical 1160)
            (:coord-barre "TZ4 TE4")
            (:coord-norm "–")
            (:comment "Dieser Text (»ꝑ ♮.la.ſol.fa.mi.re.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 15))
      400 "ꝑ ♮.la.ſol.fa.mi.re.")
     ((:alt (:diplomatic 1220)
            (:critical 1560)
            (:coord-barre "TZ4 TE5")
            (:coord-norm "–")
            (:comment "Dieser Text (»ꝑ ♭.laſolfalaſol.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 16))
      354 "ꝑ ♭.laſolfalaſol.")
     ((:alt (:diplomatic 1600)
            (:critical 1920)
            (:coord-barre "TZ4 TE6")
            (:coord-norm "–")
            (:comment "Dieser Text (»ꝑ n.fami.mi.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 17))
      268 "ꝑ n.fami.mi.")
     ((:alt (:diplomatic 1886)
            (:critical 2200)
            (:coord-barre "TZ4 TE7")
            (:coord-norm "–")
            (:comment "Dieser Text (»ꝑ ♭.fa.mi.la.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 18))
      290 "ꝑ ♭.fa.mi.la."))
   (:text 70 58
     (90 370 "mi.et re.ꝑ aſcen.")
     (474 nil
          (:alt (:diplomatic "")
                (:critical "re. ꝑ aſcen.")
                (:coord-barre "TZ5 TE2")
                (:coord-norm "–")
                (:comment "Dieser Text (»re. ꝑ aſcen.«) existiert im Original nicht.")
                (:flag :ready) (:id 19)))
     ((:alt (:diplomatic 524)
            (:critical 890)
            (:coord-barre "TZ5 TE3")
            (:coord-norm "–")
            (:comment "Dieser Text (»fa.mi.mi.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 20))
      218 "fa.mi.mi.")
     ((:alt (:diplomatic 824)
            (:critical 1160)
            (:coord-barre "TZ5 TE4")
            (:coord-norm "–")
            (:comment "Dieser Text (»la.ſol.fa.la.ſol.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 21))
      340 "la.ſol.fa.la.ſol.")
     ((:alt (:diplomatic 1172)
            (:critical 1560)
            (:coord-barre "TZ5 TE5")
            (:coord-norm "–")
            (:comment "Dieser Text (»ꝑ ♮.ſol.fa.la.ſol.fa.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 22))
      434 "ꝑ ♮.ſol.fa.la.ſol.fa.")
     ((:alt (:diplomatic 1972)
            (:critical 2200)
            (:coord-barre "TZ5 TE6")
            (:coord-norm "–")
            (:comment "Dieser Text (»fa.mi.mi.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 23))
      218 "fa.mi.mi."))
   (:text 70 58
     ((:alt (:diplomatic 838)
            (:critical 1160)
            (:coord-barre "TZ6 TE1")
            (:coord-norm "–")
            (:comment "Dieser Text (»mi. per aſcend.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 24))
      336 "mi. per aſcend.")
     ((:alt (:diplomatic 1264)
            (:critical 1560)
            (:coord-barre "TZ6 TE2")
            (:coord-norm "–")
            (:comment "Dieser Text (»re. ꝑ aſcend.«) wurde nach rechts verschoben.")
            (:flag :ready) (:id 25))
      294 "re. ꝑ aſcend."))))
