`((:header
   (:filename "b1-c19-m1")
   (:alt-name "m1.027")
   (:comment "q021_s037, origin: 666")
   (:creator "Vicentino21 / Johannes Keller")
   (:section-captions
    (s1 (:alt (:it "semitono maggiore\\naturale composto")
              (:de "")
              (:en "semitono maggiore\\naturale composto")))
    (s2 (:alt (:it "semitono maggiore\\accidentale incomposto")
              (:de "")
              (:en "semitono maggiore\\accidentale incomposto")))
    (s3 (:alt (:it "semitono maggiore\\accidentale composto")
              (:de "")
              (:en "semitono maggiore\\accidentale composto")))
    (s4 (:alt (:it "semitono maggiore\\accidentale incomposto")
              (:de "")
              (:en "semitono maggiore\\accidentale incomposto")))
    (s5 (:alt (:it "semitono maggiore\\naturale composto")
              (:de "")
              (:en "semitono maggiore\\naturale composto")))
    (s6 (:alt (:it "semitono maggiore\\naturale incomposto")
              (:de "")
              (:en "semitono maggiore\\naturale incomposto")))
    (s7 (:alt (:it "semitono maggiore\\accidentale incomposto")
              (:de "")
              (:en "semitono maggiore\\accidentale incomposto")))
    (s8 (:alt (:it "semitono maggiore\\naturale incomposto")
              (:de "")
              (:en "semitono maggiore\\naturale incomposto")))))
  (:data
   (:music 2205
           (:voice v1)
           (:section s1)
           cclef7 b22 sb2 b22 sbd2 b22 sb3 b22 bl
           (:section s2)
           b22 sb3 b38 fl4 b38 sb4 b22 bl
           (:section s3)
           sb4 b22 sbd4 b22 fl5 b22 sb5 bl
           (:section s4)
           b38 sb5 b22 fl6 b22 sb6 bl
           (:section s5)
           (:newline)
           sb6 b22 sbd6 b22 sb7 bl
           (:section s6)
           b38 sb7 b27 sb6 b38 bl
           (:section s7)
           sb5 b27 sh4 b22 sb4 bl
           (:section s8)
           b38 sb3 b38 sb2 b38 bl)
   (:text 70 58
     (38 nil "ſemit.mag.")
     (330 nil "ſemit.mag.")
     (640 nil "ſemit.mag.")
     (951 nil "ſemit.mag.")
     (1215 nil "ſem.mag.")
     (1457 nil "ſem.mag.")
     (1702 nil "ſem.mag.")
     (1948 nil "ſemi.mag."))
   (:text 70 58
     (54 nil "naturale")
     (339 nil "accident.")
     (630 nil "accidentale")
     (947 nil "accident.")
     (1223 nil "naturale")
     (1475 nil "naturale")
     (1714 nil "accident.")
     (1939 nil "naturale."))
   (:text 70 58
     (46 nil "comp.")
     (360 nil "incom.")
     (647 nil "comp.")
     (953 nil "incomp.")
     (1234 nil "comp.")
     (1483 nil "incomp.")
     (1716 nil "incomp.")
     (1942 nil "incomp."))))
