`((:header
   (:filename "b1-c26-m1")
   (:alt-name "m1.034")
   (:comment "q021_s042, origin: 974")
   (:creator "Vicentino21 / Johannes Keller")
   (:title (:alt (:it "Essempio dei gradi, di terza minore, composti, e incomposti")
                 (:de "")
                 (:en "Example of the steps of terza minore, composti and incomposti")))
   (:section-captions
    (s1 (:alt (:it "grado di 3\\minore\\naturale\\incomposto")
              (:de "")
              (:en "step of 3\\minore\\naturale\\incomposto")))
    (s2 (:alt (:it "grado di 3\\minore\\naturale\\incomposto")
              (:de "")
              (:en "step of 3\\minore\\naturale\\incomposto")))
    (s3 (:alt (:it "grado di 3\\minore\\naturale\\incomposto")
              (:de "")
              (:en "step of 3\\minore\\naturale\\incomposto")))
    (s4 (:alt (:it "grado di 3\\minore\\naturale\\incomposto")
              (:de "")
              (:en "step of 3\\minore\\naturale\\incomposto")))
    (s5 (:alt (:it "terza minore\\composto\\di tono\\e semitono")
              (:de "")
              (:en "terza minore\\composto\\of a tono\\and semitono")))
    (s6 (:alt (:it "terza minore\\composto\\di semitono\\e tono")
              (:de "")
              (:en "terza minore\\composto\\of a semitono\\and tono")))
    (s7 (:alt (:it "terza minore\\composto\\di semitono\\e tono")
              (:de "")
              (:en "terza minore\\composto\\of a semitono\\and tono")))
    (s8 (:alt (:it "terza minore\\composto\\di tono\\e semitono")
              (:de "")
              (:en "terza minore\\composto\\of a tono\\and semitono")))))
  (:data
   (:text 80 58
         (367 1446 "ᴇſſempio de i gradi,di ᴛerza minore,compoſti & incompoﬆi."))
   (:music 2231
           (:voice v1)
           (:section s1)
          cclef7 b27 sb1 b27 sb3 b27 bl
           (:section s2)
          b27 sb2 b27 sb4 b27 bl
           (:section s3)
          b27 sb7 b27 sb5 b27 bl
           (:section s4)
          b27 sb8 b27 sb6 b27 bl
           (:section s5)
          b22 sb1 b22 sb2 b22 sb3 b22 bl
           (:section s6)
          b27 sb2 b27 sb3 b27 sb4 b27 bl
           (:section s7)
          b22 sb7 b22 sb6 b27 sb5 bl
           (:section s8)
          b22 sb8 b22 sb7 b22 sb6 b22 bl)
   (:text 70 58
         (39 nil "grad.di 3.")
         (301 nil "gra.di 3.")
         (544 nil "gra. di 3.")
         (783 nil "gra. di 3.")
         (1048 nil "ᴛerza min.")
         (1341 nil "ᴛerza min.")
         (1626 nil "ᴛerza min.")
         (1930 nil "ᴛerza min."))
   (:text 70 58
         (36 nil "min. natu.")
         (296 nil "min. nat.")
         (530 nil "min.natu.")
         (777 nil "min. nat.")
         (1021 nil "com.di tono")
         (1305 nil "com. di ſem.")
         (1616 nil "com. di ſem.")
         (1923 nil "comp.di tono"))
   (:text 70 58
         (34 nil "incomp.")
         (295 nil "incomp.")
         (520 nil "incomp.")
         (759 nil "incomp.")
         (1006 nil "& ſemit.")
         (1297 nil "& tono")
         (1607 nil "& tono")
         (1907 nil "& ſemitono."))))
