`((:header
   (:filename "b1-c05-m1")
   (:alt-name "m1.003")
   (:comment "q021_s022, origin: 1002")
   (:creator "Vicentino21 / Johannes Keller")
   (:title (:alt (:it "Dimostratione della mano diatonica")
                 (:de "")
                 (:en "Illustration of the diatonic hand")))
   (:section-headings
    (s1 (:alt (:it "Alamire")
              (:de "Alamire")
              (:en "Alamire")))
    (s2 (:alt (:it "Bfabmi")
              (:de "Bfabmi")
              (:en "Bfabmi")))
    (s3 (:alt (:it "Csolfaut")
              (:de "Csolfaut")
              (:en "Csolfaut")))
    (s4 (:alt (:it "Dlasolre")
              (:de "Dlasolre")
              (:en "Dlasolre")))
    (s5 (:alt (:it "Elami")
              (:de "Elami")
              (:en "Elami")))
    (s6 (:alt (:it "Ffaut")
              (:de "Ffaut")
              (:en "Ffaut")))
    (s7 (:alt (:it "Gsolreut")
              (:de "Gsolreut")
              (:en "Gsolreut"))))
   (:section-captions
    (s1 (:alt (:it "per natura: la\\per ♭: mi\\per ♮: re")
              (:de "")
              (:en "per natura: la\\per ♭: mi\\per ♮: re")))
    (s2 (:alt (:it "per ♭: fa\\per ♮: mi")
              (:de "")
              (:en "per ♭: fa\\per ♮: mi")))
    (s3 (:alt (:it "per ♭: sol\\per ♮: fa\\per natura: ut")
              (:de "")
              (:en "per ♭: sol\\per ♮: fa\\per natura: ut")))
    (s4 (:alt (:it "per ♭: la\\per ♮: sol\\per natura: re")
              (:de "")
              (:en "per ♭: la\\per ♮: sol\\per natura: re")))
    (s5 (:alt (:it "per ♮: la\\per natura: mi")
              (:de "")
              (:en "per ♮: la\\per natura: mi")))
    (s6 (:alt (:it "per natura: fa\\per ♭: ut")
              (:de "")
              (:en "per natura: fa\\per ♭: ut")))
    (s7 (:alt (:it "per natura: sol\\per ♭: re\\per ♮: ut")
              (:de "")
              (:en "per natura: sol\\per ♭: re\\per ♮: ut")))))
  (:data
   (:text 70 58 (1253 875 "ᴅimoſtratione della ᴍano ᴅiatonica."))
   (:text 100 58
          (130 222 "ᴀ lamire")
          (504 220 "ʙ fa ♭ mi")
          (860 225 "ᴄ ſolfaut")
          (1157 223 "ᴅ laſolre")
          (1457 151 "ᴇ lami")
          (1687 152 "ꜰ faut")
          (1917 218 "ɢ ſolreut"))
   (:music 2200
           (:voice v1)
           (:section s1)
           b22 (:f-clef) max7 fclef7 b38
           (:alt (:diplomatic sb2)
                 (:barre sb10)
                 (:coord-barre "Erste Notenzeile, erste Note")
                 (:coord-norm "Section 1, erste Note")
                 (:comment "TEST: In-House-Korrektur, alle Exemplare.") (:flag :app) (:id 1))
           b38
           (:alt (:diplomatic sb2)
                 (:critical sb10)
                 (:coord-barre "Erste Notenzeile, zweite Note")
                 (:coord-norm "Section 1, zweite Note")
                 (:comment "TEST: Eingriff, um die Intervallfolge plausibel zu machen.")
                 (:flag :app) (:id 2))
           b38 sb2 b22 bl
           (:section s2)
           b22 fl3 (:key-signature nil nil nil nil nil nil :flat) b38 sb3 b38 nat3 b38 sb3 b22 bl
           (:section s3)
           b22 (:key-signature nil nil nil nil nil nil nil) sb4 b38 sb4 b38 sb4 b22 bl
           (:section s4)
           b22 sb5 b38 sb5 b38 sb5 b22 bl
           (:section s5)
           b22 sb6 b38 sb6 b22 bl
           (:section s6)
           b22 sb7 b38 sb7 b22 bl
           (:section s7)
           b22 sb8 b38 sb8 b38 sb8 b38 bl)
   (:text 70 58
          (167 nil "la") (263 nil "mi") (347 nil "re")
          (543 nil "fa") (713 nil "mi")
          (838 nil "ſol") (935 nil "fa") (1028 nil "ut")
          (1155 nil "la") (1232 nil "ſol") (1324 nil "re")
          (1478 nil "la") (1559 nil "mi")
          (1673 nil "fa") (1770 nil "ut")
          (1904 nil "ſol") (2001 nil "re") (2072 nil "ut"))
   (:text 60 58
          (153 nil "per nat.")
          (834 nil "per ♭.")
          (1156 nil "per ♭.")
          (1481 nil "per ♮.")
          (1713 nil "per nat.")
          (1926 nil "per nat."))
   (:text 60 58
          (153 nil "per ♭.")
          (511 nil "per ♭.")
          (835 nil "per ♮.")
          (1152 nil "per ♮.")
          (1471 nil "per nat.")
          (1701 nil "per ♭.")
          (1920 nil "per ♭."))
   (:text 100 58
          (150 nil "per ♮.")
          (508 nil "per ♮.")
          (834 nil "per natura")
          (1148 nil "per natura")
          (1921 nil "per ♮."))))
