`((:header
   (:filename "b1-c05-m5")
   (:alt-name "m1.007")
   (:comment "q021_s024, origin: 1052")
   (:creator "Vicentino21 / Johannes Keller")
   (:title (:alt (:it "Mano della divisione del tono in quattro diesis enarmonici ascendenti\\con lo semitono minore")
                 (:de "Hand mit der Unterteilung des tono in vier aufsteigenden diesis enarmonici mit dem semitono minore.")
                 (:en "Hand of the division of the tono into four ascending diesis enarmonici\\with the semitono minore")))
   (:section-headings
    (s1 (:alt (:it "da Alamire a Bmi")
              (:de "von Alamire zu Bmi")
              (:en "from Alamire to Bmi")))
    (s2 (:alt (:it "da Bmi a Csolfaut")
              (:de "von Bmi zu Csolfaut")
              (:en "from Bmi to Csolfaut")))
    (s3 (:alt (:it "da Bfa a Csolfaut")
              (:de "von Bfa zu Csolfaut")
              (:en "from Bfa to Csolfaut")))
    (s4 (:alt (:it "da Csolfaut a Dlasol")
              (:de "von Csolfaut zu Dlasol")
              (:en "from Csolfaut to Dlasol")))
    (s5 (:alt (:it "da Dlasolre a Elami")
              (:de "von Dlasolre zu Elami")
              (:en "from Dlasolre to Elami")))
    (s6 (:alt (:it "da Elami a F")
              (:de "von Elami zu F")
              (:en "from Elami to F")))
    (s7 (:alt (:it "da Ffaut a G.")
              (:de "von Ffaut zu G.")
              (:en "from Ffaut to G")))
    (s8 (:alt (:it "da Gsolreut a Alamire")
              (:de "von Gsolreut zu Alamire")
              (:en "from Gsolreut to Alamire"))))
   (:section-captions
    (s4 (:alt (:it "sol e fa discendono")
              (:de "sol und fa absteigend")
              (:en "sol and fa in descent")))
    (s5 (:alt (:it "la e sol discendono")
              (:de "la und sol absteigend")
              (:en "la and sol in descent")))
    (s6 (:alt (:it "la discende")
              (:la absteigend")
              (:en "la in descent")))))
  (:preamble-lilypond
   (:lyrics
    ;; JK: Im Auge zu behalten: die Silben werden standardmässig kleiner gesetzt als die "per
    ;; x:"-Angaben und die 'captions'. Das müsste in der lilypond-backend-Implementierung angepasst
    ;; werden, falls die Unterschiedlichkeit der Schriftgrössen nicht akzeptabel sein sollte.
    ;;
    ;; OPEN
    (s1 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } re mi fa re mi")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } re mi fa re mi")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } re mi fa re mi")))
    (s1 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } mi fa sol re mi")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } mi fa sol re mi")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } mi fa sol re mi")))
    (s2 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } mi fa re mi fa")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } mi fa re mi fa")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } mi fa re mi fa")))
    (s3 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } fa sol re mi fa")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } fa sol re mi fa")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } fa sol re mi fa")))
    (s4 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } ut re mi fa re")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } ut re mi fa re")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in nat.:\" } ut re mi fa re")))
    (s5 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } re mi fa re mi")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } re mi fa re mi")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in nat.:\" } re mi fa re mi")))
    (s6 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } mi mi fa")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } mi mi fa")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in nat.:\" } mi mi fa")))
    (s7 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } fa re mi fa sol")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } fa re mi fa sol")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in nat.:\" } fa re mi fa sol")))
    (s7 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } fa re mi fa re")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } fa re mi fa re")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } fa re mi fa re")))
    (s8 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } sol re mi fa re")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } sol re mi fa re")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in nat.:\" } sol re mi fa re")))
    (s8 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } re mi fa re mi")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } re mi fa re mi")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } re mi fa re mi")))
    (s8 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } ut re mi fa re")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } ut re mi fa re")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } ut re mi fa re")))
    ))
  (:data
   (:text 70 58 (115 1903 "ᴍano della diuiſione del tono in quattro ᴅieſis ᴇn. aſcendenti con lo ſemitono minore."))
   (:text 100 58
          (43 nil "da ᴀlamire à ʙ mi")
          (620 nil "da ʙ mi à ᴄ ſol fa ut")
          (1156 nil "da ʙ fa à ᴄ ſol fa ut")
          (1673 nil "da ᴄ ſol fa ut à ᴅ laſol"))
   (:music 2196
           (:voice v1)
           (:section s1)
           (:f-clef) max7 fclef7 sb2 b22 sbd2 b22 sh2 b22 sb2 b22 fl3 b22 sbd3 b22 sb3 bl
           (:section s2)
           sb3 b22 sbd3 b22 sh3 b22 sb3 b22
           (:alt (:diplomatic fl4 b22 sbd4)
                 (:critical fl4 b22 sbd4)
                 (:coord-barre "MZ1 N9")
                 (:coord-norm "S2 N4")
                 (:comment "Dieses Ċ♭ wird von Vicentino nicht kommentiert, kommt aber beispielsweise in b5-c52-m2-s12 vor, wo es eindeutig als klanglich austauschbar mit B♯ (_Csolfaut secondo in terzo ordine_) in Erscheinung tritt.")
                 (:flag :ready) (:id 1))
           b22 sb4 bl
           (:section s3)
           fl3 b22 sb3 b22 fl3 b22 sbd3 b22 nat3 b22 sb3 b22 sbd3 b22 sb4 bl
           (:section s4)
           sb4 b22 sbd4 b22 sh4 b22 sb4 b22 fl5 b22 sbd5 b22 sb5)
   (:text 70 58
          (25 507 "ꝑ ♮. re. mi fa. re. mi.")
          (593 530 "per ♮. mi. fa. re. mi. fa.")
          (1123 514 "ꝑ b. fa. ſol. re. mi. fa.")
          (1669 523 "per n. ut. re. mi. fa.re."))
   (:text 90 58
          (25 575 "per ♭. mi. fa. ſol. re. mi.")
          (1669 500 "ſol & fa. diſcendono."))
   (:text 110 58
          (10 550 "da ᴅ la ſol re à ᴇ la mi")
          (642 318 "da ᴇlami a ꜰ .")
          (1016 321 "da ꜰ faut à ɢ.")
          (1510 636 "da ɢ ſol re ut à ᴀ la mi re."))
   (:music 2190
           (:voice v1)
           (:section s5)
           (:newline)
           (:f-clef) max7 fclef7 b22 sb5 b22 sbd5 b22 sh5 b22 sb5 b22 fl6 b22 sbd6 b22 sb6 b22 bl
           (:section s6)
           b22 sb6 b22 sbd6 b22 sb7 b22 bl
           (:section s7)
           b22 sb7 b22 sbd7 b22 sh7 b22 sb7 b22 fl8 b22 sbd8 b22 sb8 b22 bl
           (:section s8)
           b22 sb8 b38 sbd8 b38 sh8 sb8 b22 fl9 b22 sbd9 b22 sb9 b22 bl b22)
   (:text 80 58
          (0 588 "per n. re. mi. fa. re. mi.")
          (654 310 "ꝑ n.mi.mi.fa.")
          (973 527 "per n. fa. re. mi. fa ſol.")
          (1533 570 "per nat. ſol re. mi. fa re."))
   (:text 80 58
          (168 464 "la.& ſol diſcendono")
          (664 243 "la diſcende")
          (982 527
               (:alt (:diplomatic "per ♭.fa.re.mi.fa.re.")
                     (:critical "per ♭.ut.re.mi.fa.re.")
                     (:coord-barre "TZ7 TE3")
                     (:coord-norm "G7 US Z2")
                     (:comment "Original: »per ♭.fa.re.mi.fa.re.«, wurde durch »per ♭.ut.re.mi.fa.re.« ersetzt.")
                     (:flag :ready) (:id 2)))
          (1529 557 "per ♭.re.mi.fa.re.mi."))
   (:text 70 58
          (1552 536 "per ♮.ut.re.mi.fa.re."))))
