`((:header
   (:filename "b1-c05-m6")
   (:alt-name "m1.008")
   (:comment "q021_s025, origin: 488")
   (:creator "Vicentino21 / Johannes Keller")
   (:title (:alt (:it "Mano enarmonica discendente con i semitoni minori, nel principio del tono per\\le sette lettere della mano, con il tono diviso in quattro parti: e come si ha da leggere")
                 (:de "Absteigende enharmonische Hand mit den semitoni minori zu Beginn des tono, durch\\die sieben Buchstaben der Hand, mit dem tono unterteilt in vier Teile, und wie es zu lesen ist.")
                 (:en "Descending enharmonic hand with semitoni minori in the beginning of the tono through\\the seven letters of the hand, with the tono divided into four parts: as they are to be read")))
   (:section-headings
    (s1 (:alt (:it "da A a G")
              (:de "von A zu G")
              (:en "from A to G")))
    (s2 (:alt (:it "da G a F")
              (:de "von G zu F")
              (:en "from G to F")))
    (s3 (:alt (:it "da F a E")
              (:de "von F zu E")
              (:en "from F to E")))
    (s4 (:alt (:it "da E a D")
              (:de "von E zu D")
              (:en "from E to D")))
    (s5 (:alt (:it "da D a C")
              (:de "von D zu C")
              (:en "from D to C")))
    (s6 (:alt (:it "da C a B")
              (:de "von C zu B")
              (:en "from C to B")))
    (s7 (:alt (:it "da B a A")
              (:de "von B zu A")
              (:en "from B to A"))))
   (:section-captions
    (s1 (:alt (:it "mi e re [se] ascendino")
              (:de "mi und re aufsteigend")
              (:en "mi and re in ascent")))
    (s2 (:alt (:it "re e ut [se] ascendeno")
              (:de "re und ut aufsteigend")
              (:en "re and ut in ascent")))
    (s3 (:alt (:it "per ascendere")
              (:de "aufsteigend")
              (:en "in ascent")))
    (s4 (:alt (:it "[re et] mi [se] ascende")
              (:de "mi aufsteigend")
              (:en "mi in ascent")))
    (s7 (:alt (:it "per discendere")
              (:de "absteigend")
              (:en "in descent")))))
  (:preamble-lilypond
   (:lyrics
    ;; JK: Im Auge zu behalten: die Silben werden standardmässig kleiner gesetzt als die "per
    ;; x:"-Angaben und die 'captions'. Das müsste in der lilypond-backend-Implementierung angepasst
    ;; werden, falls die Unterschiedlichkeit der Schriftgrössen nicht akzeptabel sein sollte.
    ;;
    ;; OPEN
    (s1 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } la sol fa la sol")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } la sol fa la sol")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in nat.:\" } la sol fa la sol")))
    (s2 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } sol fa la sol fa")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } sol fa la sol fa")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in nat.:\" } sol fa la sol fa")))
    (s3 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } fa mi la")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per nat.:\" } fa mi la")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in nat.:\" } fa mi la")))
    (s3 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"\" } fa mi mi")
                 (:de "\\set stanza = \\markup{ \\normal-text \"\" } fa mi mi")
                 (:en "\\set stanza = \\markup{ \\normal-text \"\" } fa mi mi")))
    (s4 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } la sol fa mi re")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } la sol fa mi re")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } la sol fa mi re")))
    (s4 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"\" } la sol fa la sol")
                 (:de "\\set stanza = \\markup{ \\normal-text \"\" } la sol fa la sol")
                 (:en "\\set stanza = \\markup{ \\normal-text \"\" } la sol fa la sol")))
    (s5 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } la sol fa la sol")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } la sol fa la sol")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } la sol fa la sol")))
    (s5 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } sol fa la sol fa")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } sol fa la sol fa")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } sol fa la sol fa")))
    (s6 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } fa mi mi")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } fa mi mi")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } fa mi mi")))
    (s7 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } mi mi fa mi re")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } mi mi fa mi re")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } mi mi fa mi re")))
    (s7 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } [mi] [mi] fa mi la")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } [mi] [mi] fa mi la")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } [mi] [mi] fa mi la")))
    ))
  (:data
   (:text 70 58 (0 2210 "ᴍano ᴇnarmonica diſcendente con i ſemitoni minori, nel principio del tono per le ſette lettere della"))
   (:text 70 58 (0 1484 "ᴍano, con il tono diuiſo in quattro parti:& come ſi à da leggere."))
   (:text 110 58
          (162 nil "da ᴀ.")
          (460 nil "à ɢ.")
          (734 nil "da ɢ.")
          (1036 nil "à ꜰ.")
          (1320 nil "da ꜰ.")
          (1524 nil "à ᴇ.")
          (1738 nil "da ᴇ.")
          (1960 nil "à ᴅ."))
   (:music 2210
           (:voice v1)
           (:section s1)
           (:f-clef) max7 fclef7 b38 sb9 b38 fl9 b38 sbd9 b38 fl9 b38 sb9 b38 sbd8 b38 sb8 bl
           (:section s2)
           sb8 b38 fl8 b38 sbd8 b38 fl8 b38 sb8 b38 sbd7 b38 sb7 bl
           (:section s3)
           b38 b22 sb7 b38 sbd6 b38 sb6 b38 b22 bl
           (:section s4)
           sb6 b22 fl6 sbd6 b22 fl6 sb6 sbd5 b22 sb5 bl)
   (:text 70 58
          (10 nil "ꝑ n.")
          (130 390 "la. ſol. fa. la. ſol.")
          (724 530 "per n. ſol. fa. la. ſol. fa.")
          (1302 412 "ꝑn.fa.mi.la.ꝑ diſ.")
          (1742 454 "ꝑ♮. la.ſol.fa.mi.re."))
   (:text 70 58
          (150 490 "mi.& re. aſcendino")
          (864 444 "re.& ut.aſcendeno")
          (1374 258 "fa.mi.mi.")
          (1842 350 "la.ſol.fa.la. ſol."))
   (:text 70 58
          (1382 218 "ꝑ aſcend.")
          (1870 262 "mi aſcende,"))
   (:text 100 58
          (176 nil "da ᴅ.")
          (500 nil "à ᴄ.")
          (782 nil "da ᴄ.")
          (986 nil "à ʙ.")
          (1198 nil "da ʙ.")
          (1502 nil "à ᴀ."))
   (:music 2210
           (:section s5)
           (:newline)
           (:f-clef) max7 fclef7 b38 sb5 b38 fl5 b38 sbd5 b38 fl5 b38 sb5 b38 sbd4 b38 sb4 b22 bl
           (:section s6)
           b38 sb4 b38 sbd3 b38 sb3 b38 bl
           (:section s7)
           b22 sb3 b38 fl3 b38 sbd3 b38 fl3 b38 sb3 b38 sbd2 b38 sb2 b38 bl
           b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38)
   (:text 70 58
          (10 nil "ꝑ ♭.")
          (156 468 "la. ſol. fa. la. ſol.")
          (744 358 "ꝑ ♮.fa.mi.mi.")
          (1142 580 "ꝑ ♮.mi. mi. fa. mi. re."))
   (:text 70 58
          (10 nil "ꝑ ♮.")
          (144 480 "ſol. fa. la. ſol. fa.")
          (1124 nil "ꝑ ♭.")
          (1452 446 "fa.mi.la.ꝑ diſcend."))))
