`((:header
   (:filename "b1-c05-m5")
   (:alt-name "m1.007")
   (:comment "q021_s024, origin: 1052")
   (:creator "Vicentino21 / Johannes Keller")
   (:title (:alt (:it "Mano della divisione del tono in quattro diesis enarmonici ascendenti\\con lo semitono minore")
                 (:de "")
                 (:en "Hand of the division of the tono into four ascending diesis enarmonici\\with the semitono minore")))
   (:section-headings
    (s1 (:alt (:it "da Alamire a Bmi")
              (:de "")
              (:en "from Alamire to Bmi")))
    (s2 (:alt (:it "da Bmi a Csolfaut")
              (:de "")
              (:en "from Bmi to Csolfaut")))
    (s3 (:alt (:it "da Bfa a Csolfaut")
              (:de "")
              (:en "from Bfa to Csolfaut")))
    (s4 (:alt (:it "da Csolfaut a Dlasol")
              (:de "")
              (:en "from Csolfaut to Dlasol")))
    (s5 (:alt (:it "da Dlasolre a Elami")
              (:de "")
              (:en "from Dlasolre to Elami")))
    (s6 (:alt (:it "da Elami a F")
              (:de "")
              (:en "from Elami to F")))
    (s7 (:alt (:it "da Ffaut a G.")
              (:de "")
              (:en "from Ffaut to G")))
    (s8 (:alt (:it "da Gsolreut a Alamire")
              (:de "")
              (:en "from Gsolreut to Alamire"))))
   (:section-captions
    (s1 (:alt (:it "per ♮: re-mi-fa-re-mi\\per ♭: mi-fa-sol-re-mi")
              (:de "")
              (:en "per ♮: re-mi-fa-re-mi\\per ♭: mi-fa-sol-re-mi")))
    (s2 (:alt (:it "per ♮: mi-fa-re-mi-fa")
              (:de "")
              (:en "per ♮: mi-fa-re-mi-fa")))
    (s3 (:alt (:it "per ♭: fa-sol-re-mi-fa")
              (:de "")
              (:en "per ♭: fa-sol-re-mi-fa")))
    (s4 (:alt (:it "per nat.: ut-re-mi-fa-re\\sol e fa discendono")
              (:de "")
              (:en "per nat.: ut-re-mi-fa-re\\sol and fa in descent")))
    (s5 (:alt (:it "per nat.: re-mi-fa-re-mi\\la e sol discendono")
              (:de "")
              (:en "per nat.: re-mi-fa-re-mi\\la and sol in descent")))
    (s6 (:alt (:it "per nat.: mi-mi-fa\\la discende")
              (:de "")
              (:en "per nat.: mi-mi-fa\\la in descent")))
    (s7 (:alt (:it "per nat.: fa-re-mi-fa-sol\\per ♭: fa-re-mi-fa-re")
              (:de "")
              (:en "per nat.: fa-re-mi-fa-sol\\per ♭: fa-re-mi-fa-re")
              (:comment "Original: »per ♭: fa-re-mi-fa-re«. Von Anne zu bestätigen.")
              ;;Kommentar Anne: Original ist gut, ich habe das italienische zurück korrigiert
              (:flag :redundant) (:id 3)))
    (s8 (:alt (:it "per nat.: sol-re-mi-fa-re\\per b: re-mi-fa-re-mi\\per ♮: ut-re-mi-fa-re")
              (:de "")
              (:en "per nat.: sol-re-mi-fa-re\\per b: re-mi-fa-re-mi\\per ♮: ut-re-mi-fa-re")))))
  (:data
   (:text 70 58 (115 1903 "ᴍano della diuiſione del tono in quattro ᴅieſis ᴇn. aſcendenti con lo ſemitono minore."))
   (:text 100 58
          (43 nil "da ᴀlamire à ʙ mi")
          (620 nil "da ʙ mi à ᴄ ſol fa ut")
          (1156 nil "da ʙ fa à ᴄ ſol fa ut")
          (1673 nil "da ᴄ ſol fa ut à ᴅ laſol"))
   (:music 2196
           (:voice v1)
           (:section s1)
           (:f-clef) max7 fclef7 sb2 b22 sbd2 b22 sh2 b22 sb2 b22 fl3 b22 sbd3 b22 sb3 bl
           (:section s2)
           sb3 b22 sbd3 b22 sh3 b22 sb3 b22
           (:alt (:diplomatic fl4 b22 sbd4)
                 (:critical fl4 b22 sbd4)
                 (:coord-barre "1. MZ, 9. N")
                 (:coord-norm "S2, 4. N")
                 (:comment "Dieses Ċ♭ wird von Vicentino nicht kommentiert, kommt aber beispielsweise in b5-c52-m2-s12 vor, wo es eindeutig als klanglich austauschbar mit B♯ (_Csolfaut secondo in terzo ordine_) in Erscheinung tritt.")
                 (:flag :ready) (:id 1))
           b22 sb4 bl
           (:section s3)
           fl3 b22 sb3 b22 fl3 b22 sbd3 b22 nat3 b22 sb3 b22 sbd3 b22 sb4 bl
           (:section s4)
           sb4 b22 sbd4 b22 sh4 b22 sb4 b22 fl5 b22 sbd5 b22 sb5)
   (:text 70 58
          (25 507 "ꝑ ♮. re. mi fa. re. mi.")
          (593 530 "per ♮. mi. fa. re. mi. fa.")
          (1123 514 "ꝑ b. fa. ſol. re. mi. fa.")
          (1669 523 "per n. ut. re. mi. fa.re."))
   (:text 90 58
          (25 575 "per ♭. mi. fa. ſol. re. mi.")
          (1669 500 "ſol & fa. diſcendono."))
   (:text 110 58
          (10 550 "da ᴅ la ſol re à ᴇ la mi")
          (642 318 "da ᴇlami a ꜰ .")
          (1016 321 "da ꜰ faut à ɢ.")
          (1510 636 "da ɢ ſol re ut à ᴀ la mi re."))
   (:music 2190
           (:voice v1)
           (:section s5)
           (:newline)
           (:f-clef) max7 fclef7 b22 sb5 b22 sbd5 b22 sh5 b22 sb5 b22 fl6 b22 sbd6 b22 sb6 b22 bl
           (:section s6)
           b22 sb6 b22 sbd6 b22 sb7 b22 bl
           (:section s7)
           b22 sb7 b22 sbd7 b22 sh7 b22 sb7 b22 fl8 b22 sbd8 b22 sb8 b22 bl
           (:section s8)
           b22 sb8 b38 sbd8 b38 sh8 sb8 b22 fl9 b22 sbd9 b22 sb9 b22 bl b22)
   (:text 80 58
          (0 588 "per n. re. mi. fa. re. mi.")
          (654 310 "ꝑ n.mi.mi.fa.")
          (973 527 "per n. fa. re. mi. fa ſol.")
          (1533 570 "per nat. ſol re. mi. fa re."))
   (:text 80 58
          (168 464 "la.& ſol diſcendono")
          (664 243 "la diſcende")
          (982 527
               (:alt (:diplomatic "per ♭.fa.re.mi.fa.re.")
                     (:critical "per ♭.ut.re.mi.fa.re.")
                     (:coord-barre "2. TZ unter 2. MZ, 3. TE")
                     (:coord-norm "S7, US, 2. Z")
                     (:comment "Original: »per ♭.fa.re.mi.fa.re.«.")
                     (:flag :ready) (:id 2)))
          (1529 557 "per ♭.re.mi.fa.re.mi."))
   (:text 70 58
          (1552 536 "per ♮.ut.re.mi.fa.re."))))
