`((:header
   (:filename "b1-c32-m1")
   (:alt-name "m1.040")
   (:comment "q021_s045, origin: 488")
   (:creator "Vicentino21 / Johannes Keller")
   (:title (:alt (:it "Essempio del salto della quarta naturale e de suoi gradi incomposto et composto")
                 (:de "")
                 (:en "")))
   (:section-headings
    (s1 (:alt (:it "prima quarta")
              (:de "")
              (:en "")))
    (s2 (:alt (:it "seconda quarta")
              (:de "")
              (:en "")))
    (s3 (:alt (:it "terza quarta")
              (:de "")
              (:en "")))
    (s4 (:alt (:it "prima quarta")
              (:de "")
              (:en "")))
    (s5 (:alt (:it "seconda quarta")
              (:de "")
              (:en "")))
    (s6 (:alt (:it "terza quarta")
              (:de "")
              (:en ""))))
   (:section-captions
    (s1 (:alt (:it "salto di quarta\\incomposta")
              (:de "")
              (:en "")))
    (s2 (:alt (:it "salto di quarta\\incomposta")
              (:de "")
              (:en "")))
    (s3 (:alt (:it "salto di quarta\\incomposta")
              (:de "")
              (:en "")))
    (s4 (:alt (:it "quarta composta\\de gradi")
              (:de "")
              (:en "")))
    (s5 (:alt (:it "quarta composta\\de gradi")
              (:de "")
              (:en "")))
    (s6 (:alt (:it "quarta composta\\de gradi")
              (:de "")
              (:en "")))))
  (:data
   (:text 140 58
          (172 1866 "ᴇſſempio del ꜱalto della Ɋuarta naturale,e du ſuoi gradi incompoſto et compoſto."))
   (:text 100 58
          (61 352 "ᴘrima Ɋuarta.")
          (432 nil "ꜱecōda Ɋuar.")
          (759 nil "ᴛerza Ɋuar.")
          (1093 nil "ᴘrima Ɋuarta")
          (1429 nil "ꜱecōda Ɋuarta")
          (1822 nil "ᴛerza Ɋuarta"))
   (:music 2200
           (:voice v1)
           (:section s1)
           (:f-clef) max7 fclef7 b22 sb2 b38 b38 sb5 b27 b27 bl
           (:section s2)
           b27 b38 sb3 b38 b38 sb6 b27 b38 bl
           (:section s3)
           b38 sb4 b38 b38 b22 sb7 b38 bl
           (:section s4)
           b38 sb2 b38 sb3 b38 sb4 b38 sb5 bl
           (:section s5)
           sb3 b38 sb4 b38 sb5 b38 sb6 bl
           (:section s6)
           b38 sb4 b38 sb5 b38 sb6 b38 sb7 bl)
   (:text 80 58
          (89 nil "ſalto di 4.")
          (394 nil "ſalto di 4.")
          (735 nil "ſalto di 4.")
          (1039 nil "quarta compò.")
          (1428 nil "quarta comp.")
          (1793 nil "quarta compoſta"))
   (:text 70 58
          (83 nil "incompoſta")
          (392 nil "incomp.")
          (715 nil "incomp.")
          (1033 nil "de gradi")
          (1422 nil "de gradi")
          (1797 nil "de gradi"))))
