`((:header
   (:filename "b1-c05-m4")
   (:alt-name "m1.006")
   (:comment "q021_s024, origin: 1057")
   (:creator "Vicentino21 / Johannes Keller")
   (:title (:alt (:it "Dimostratione della mano enarmonica diatonica,\\ascendente con le sette lettere della mano")
                 (:de "Darstellung der enharmonisch-diatonischen Hand,\\aufsteigend mit den sieben Buchstaben der Hand")
                 (:en "Illustration of the diatonic enharmonic hand,\\ascending with the seven letters of the hand")))
   (:section-headings
    (s1 (:alt (:it "Alamire")
              (:de "Alamire")
              (:en "Alamire")))
    (s2 (:alt (:it "Bmi")
              (:de "Bmi")
              (:en "Bmi")))
    (s3 (:alt (:it "Csolfaut")
              (:de "Csolfaut")
              (:en "Csolfaut")))
    (s4 (:alt (:it "Dlasolre")
              (:de "Dlasolre")
              (:en "Dlasolre")))
    (s5 (:alt (:it "Elami")
              (:de "Elami")
              (:en "Elami")))
    (s6 (:alt (:it "Ffaut")
              (:de "Ffaut")
              (:en "Ffaut")))
    (s7 (:alt (:it "Gsolreut")
              (:de "Gsolreut")
              (:en "Gsolreut")))))
  (:preamble-lilypond
   (:lyrics
    ;; JK: Im Auge zu behalten: die Silben werden standardmässig kleiner gesetzt als die "per
    ;; x:"-Angaben und die 'captions'. Das müsste in der lilypond-backend-Implementierung angepasst
    ;; werden, falls die Unterschiedlichkeit der Schriftgrössen nicht akzeptabel sein sollte.
    ;;
    ;; OPEN
    (s1 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ɴ:\" } la")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ɴ:\" } la")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ɴ:\" } la")))
    (s1 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } \\skip 1 mi")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } \\skip 1 mi")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } \\skip 1 mi")))
    (s1 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } \\skip 1 \\skip 1 re")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } \\skip 1 \\skip 1 re")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } \\skip 1 \\skip 1 re")))

    (s2 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } mi")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } mi")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } mi")))

    (s3 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } sol")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } sol")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } sol")))
    (s3 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ɴ:\" } \\skip 1 fa")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ɴ:\" } \\skip 1 fa")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ɴ:\" } \\skip 1 fa")))
    (s3 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } \\skip 1 \\skip 1 ut")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } \\skip 1 \\skip 1 ut")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } \\skip 1 \\skip 1 ut")))

    (s4 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } la")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } la")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } la")))
    (s4 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } \\skip 1 sol")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } \\skip 1 sol")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } \\skip 1 sol")))
    (s4 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ɴ:\" } \\skip 1 \\skip 1 re")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ɴ:\" } \\skip 1 \\skip 1 re")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ɴ:\" } \\skip 1 \\skip 1 re")))

    (s5 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } la")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } la")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } la")))
    (s5 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ɴ:\" } \\skip 1 mi")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ɴ:\" } \\skip 1 mi")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ɴ:\" } \\skip 1 mi")))

    (s6 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ɴ:\" } fa")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ɴ:\" } fa")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ɴ:\" } fa")))
    (s6 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } \\skip 1 ut")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } \\skip 1 ut")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } \\skip 1 ut")))

    (s7 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ɴ:\" } sol")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ɴ:\" } sol")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ɴ:\" } sol")))
    (s7 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } \\skip 1 re")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♭:\" } \\skip 1 re")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♭:\" } \\skip 1 re")))
    (s7 v1 (:alt (:it "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } \\skip 1 \\skip 1 ut")
                 (:de "\\set stanza = \\markup{ \\normal-text \"per ♮:\" } \\skip 1 \\skip 1 ut")
                 (:en "\\set stanza = \\markup{ \\normal-text \"in ♮:\" } \\skip 1 \\skip 1 ut")))
    ))
  (:data
   (:text 70 58 (86 2053 "ᴅimoſtratione della mano ᴇnarmonica ᴅiatonica, aſcendente con le ſette lettere della ᴍano."))
   (:text 90 58
     (43 nil "ᴀ la mi re")
     (459 nil "ʙ mi")
     (622 nil "ᴄ ſol fa ut")
     (983 nil "ᴅ la ſol re")
     (1320 nil "ᴇ la mi")
     (1565 nil "ꜰ fa ut")
     (1809 nil "ɢ ſol re ut"))
   (:music 2214
           (:voice v1)
           (:section s1)
           b38 (:f-clef) max7 fclef7 b22 sbd2 b38 sbd2 b38 sbd2 b38 bl
           (:section s2)
           b38 sbd3 b38 bl
           (:section s3)
           b38 sbd4 b38 sbd4 b38 sbd4 b38 bl
           (:section s4)
           b38 sbd5 b38 sbd5 b38 sbd5 b38 bl
           (:section s5)
           b22 sbd6 b38 sbd6 b22 bl
           (:section s6)
           b22 sbd7 b38 sbd7 b38 bl
           (:section s7)
           b22 sbd8 b38 sbd8 b38 sbd8 b38 bl b22)
   (:text 70 58
     (:alt (:diplomatic)
           (:critical)
           (:coord-barre "allg.")
           (:coord-norm "allg.")
           (:comment "Das Zeichen ɴ wird als Abkürzung für _natura_ verwendet.")
           (:flag :ready) (:id 1))
     (44 354 "ꝑ nat. ꝑ ♭. ꝑ ♮.")
     (478 139 "per ♮.")
     (646 307 "ꝑ ♭.ꝑ ♮. ꝑ n.")
     (994 297 "ꝑ ♭.ꝑ ♮.ꝑ n.")
     (1346 204 "ꝑ ♮. ꝑ n.")
     (1594 209 "ꝑ n. ꝑ b.")
     (1826 341 "per n.ꝑ ♭.ꝑ ♮."))
   (:text 70 58
     (169 nil "la mi re")
     (556 nil "mi")
     (695 nil "ſol fa ut")
     (1045 nil "la ſol re")
     (1386 nil "la mi")
     (1642 nil "fa ut")
     (1908 nil "ſol re ut"))))
