`((:header
   (:filename "b1-c05-m2")
   (:alt-name "m1.004")
   (:comment "")
   (:creator "Vicentino21 / Johannes Keller")
   (:title (:alt (:it "Dimostratione della mano cromatica, ascendente, con li semitoni minore,\\e con l'essempio")
                 (:de "Darstellung der aufsteigenden chromatischen Hand mit _semitoni minori_")
                 (:en "Demonstration of the ascending chromatic hand, with the _Semitoni minori_,\\ and with an example")))
   (:section-headings
    (s1 (:alt (:it "Alamire")
              (:de "A")
              (:en "A")))
    (s2 (:alt (:it "Bfa♭mi")
              (:de "B♭")
              (:en "B♭")))
    (s3 (:alt (:it "Csolfaut")
              (:de "C")
              (:en "C")))
    (s4 (:alt (:it "Dlasolre")
              (:de "D")
              (:en "D")))
    (s5 (:alt (:it "Elami")
              (:de "E")
              (:en "E")))
    (s6 (:alt (:it "Ffaut")
              (:de "F")
              (:en "F")))
    (s7 (:alt (:it "Gsolreut")
              (:de "G")
              (:en "G"))))
   (:section-captions
    (s1 (:alt (:it "per natura: la\\per ♭: mi\\per ♮: re")
              (:de "natürlich: la\\weich: mi\\hart: re")
              (:en "natural: la\\soft: mi\\hard: re")))
    (s2 (:alt (:it "per ♮: mi")
              (:de "hart: mi")
              (:en "hard: mi")))
    (s3 (:alt (:it "per natura: sol\\per ♭: fa\\per ♮: ut")
              (:de "natürlich: sol\\weich: fa\\hart: ut")
              (:en "natural: sol\\soft: fa\\hard: ut")))
    (s4 (:alt (:it "per ♭: la\\per ♮: sol\\per natura: re")
              (:de "weich: la\\hart: sol\\natürlich: re")
              (:en "soft: la\\hard: sol\\natural: re")))
    (s5 (:alt (:it "per ♮: la\\per natura: mi")
              (:de "hart: la\\natürlich: mi")
              (:en "hard: la\\natural: mi")))
    (s6 (:alt (:it "per natura: fa\\per ♭: ut")
              (:de "natürlich: fa\\weich: ut")
              (:en "natural: fa\\soft: ut")))
    (s7 (:alt (:it "per natura: sol\\per ♭: re\\per ♮: ut")
              (:de "natürlich: sol\\weich: re\\hart: ut")
              (:en "natural: sol\\soft: re\\hard: ut"))))
   (:voice-labels
    (:all v1 "")))
  (:data
   (:text 70 58
          (90 1974 "ᴅimoſtratione della ᴍano ᴄromatica, aſcendente, con li ꜱemitoni minori, e con l'eſſempio."))
   (:text 100 58
          (41 nil "ᴀ lamire")
          (366 nil "ʙ mi")
          (680 nil "ᴄ ſolfaut")
          (1002 nil "ᴅ laſolre")
          (1301 nil "ᴇ lami")
          (1613 nil "ꜰ faut")
          (1919 nil "ɢ ſolreut"))
   (:music 2193
           (:voice v1)
           (:section s1)
           b22 (:f-clef) max7 fclef7 b22 sb2 sh2 b22 sb2 b22 bl
           (:section s2)
           b22 sb3 b22 sh3 b22 sb3 b22 bl
           (:section s3)
           b22 sb4 b22 sh4 b22 sb4 b22 bl
           (:section s4)
           b22 sb5 b38 sh5 b38 sb5 b22 bl
           (:section s5)
           b22 sb6 b38 sh6 b38 sb6 b22 bl
           (:section s6)
           b22 sb7 b38 sh7 b38 sb7 b22 bl
           (:section s7)
           b22 sb8 b22 sh8 b22 sb8 b22 bl b38)
   (:text 60 58
          (43 nil "la") (121 nil "mi") (206 nil "re")
          (345 nil "mi")
          (653 nil "ſol") (740 nil "fa") (835 nil "ut")
          (959 nil "la") (1044 nil "ſol") (1141 nil "re")
          (1279 nil "la") (1363 nil "mi")
          (1567 nil "fa") (1676 nil "ut")
          (1902 nil "ſol") (1999 nil "re") (2075 nil "ut"))
   (:text 100 58
          (0 nil "per nat.ꝑ ♭.ꝑ ♮.")
          (431 nil "per ♮.")
          (569 nil "per n. ꝑ ♭. ꝑ ♮")
          (959 nil "ꝑ ♭. ꝑ ♮. ꝑ n.")
          (1309 nil "ꝑ ♮. ꝑ nat.")
          (1554 nil "per nat.ꝑ ♭.")
          (1855 nil "ꝑ n. ꝑ ♭. ꝑ ♮."))))
