`((:header
   (:filename "b1-c38-m1")
   (:alt-name "m1.047")
   (:comment "q021_s048, origin: 1066")
   (:creator "Vicentino21 / Johannes Keller")
   (:title (:alt (:it "Essempio di più di quinta imperfetta accidentale, composto e incomposto")
                 (:de "")
                 (:en "")))
   (:section-captions
    (s1 (:alt (:it "più di quinta\\imperfetta\\naturale\\composto")
              (:de "")
              (:en "")
              (:comment "»naturale« könnte hier in »accidentale« korrigiert werden, abhängig davon, ob man den _quarto ordine_ bzw. die Mischung aus _primo_ und _quarto ordine_ als _naturale_ oder _accidentale_ betrachtet. Siehe 5.43f.")
              (:flag :observe) (:id 1)))
    (s2 (:alt (:it "più di quinta\\imperfetta\\naturale\\incomposto")
              (:de "")
              (:en "")
              (:comment "»naturale« könnte hier in »accidentale« korrigiert werden, abhängig davon, ob man den _quarto ordine_ bzw. die Mischung aus _primo_ und _quarto ordine_ als _naturale_ oder _accidentale_ betrachtet. Siehe 5.43f.")
              (:flag :observe) (:id 2)))
    (s3 (:alt (:it "più di quinta\\imperfetta\\accidentale\\incomposto")
              (:de "")
              (:en "")))
    (s4 (:alt (:it "più di quinta\\imperfetta\\accidentale\\composto")
              (:de "")
              (:en "")))
    (s5 (:alt (:it "più di quinta\\imperfetta\\accidentale\\incomposto")
              (:de "")
              (:en "")))
    (s6 (:alt (:it "più di quinta\\imperfetta\\accidentale\\composto")
              (:de "")
              (:en "")
              (:comment "»accidentale« könnte hier in »naturale« korrigiert werden, abhängig davon, ob man den _quarto ordine_ bzw. die Mischung aus _primo_ und _quarto ordine_ als _naturale_ oder _accidentale_ betrachtet. Siehe 5.43f.")
              (:flag :observe) (:id 3)))
    (s7 (:alt (:it "più di quinta\\imperfetta\\accidentale\\incomposto")
              (:de "")
              (:en "")
              (:comment "»accidentale« könnte hier in »naturale« korrigiert werden, abhängig davon, ob man den _quarto ordine_ bzw. die Mischung aus _primo_ und _quarto ordine_ als _naturale_ oder _accidentale_ betrachtet. Siehe 5.43f.")
              (:flag :observe) (:id 4)))))
  (:preamble-lilypond
   (:clef-overrides
    (s2 v1 "treble_8")
    (s3 v1 "treble_8")
    (s4 v1 "treble_8")
    (s5 v1 "treble_8")
    (s6 v1 "treble_8")
    (s7 v1 "treble_8")
    (s8 v1 "treble_8")))

  (:data
   (:text 90 58
          (213 1734 "ᴇſſempio di più di Ɋuinta imperfetta accidentale,compoſto & incompoﬆo."))
   (:music 2232
           (:voice v1)
           (:section s1)
           (:f-clef) max7 fclef7 sb3 sb4 sb5 sb6 sbd7
           (:section s2)
           cclef5 b38 sb4 b38 sbd8 b38
           (:section s3)
           cclef5 b38 sh1 b38 sb1 b38 sbd5 bl
           (:section s4)
           sh2 sb2 sb3 sb4 sb5 sbd6 bl
           (:section s5)
           sb8 b38 fl4 b38 sbd4 b38 bl
           (:section s6)
           sb7 sb6 sb5 sb4 sbd3 bl
           (:section s7)
           b38 sb6 b38 sbd2 b38 bl)
   (:text 70 58
          (88 nil "più di quinta")
          (420 nil "più di quin.")
          (740 nil "più di quin.")
          (1041 nil "più di quinta")
          (1363 nil "più di quin.")
          (1640 nil "più di quinta")
          (1954 nil "più di quin."))
   (:text 80 58
     (81 nil (:alt (:diplomatic  "imper.natur.")
                   (:idealised "imper.natur.")
                   (:comment "»natur.« könnte hier in »accid.« korrigiert werden, abhängig davon, ob man den _quarto ordine_ bzw. die Mischung aus _primo_ und _quarto ordine_ als _naturale_ oder _accidentale_ betrachtet. Siehe 5.43f.")
                   (:flag :observe) (:id 5)))
     (425 nil (:alt (:diplomatic "imper. nat.")
                    (:idealised "imper. nat.")
                    (:comment "»nat.« könnte hier in »acc.« korrigiert werden, abhängig davon, ob man den _quarto ordine_ bzw. die Mischung aus _primo_ und _quarto ordine_ als _naturale_ oder _accidentale_ betrachtet. Siehe 5.43f.")
                    (:flag :observe) (:id 6)))
          (720 nil "imp. accid.")
          (1040 nil "imper.accid.")
          (1354 nil "imper.acci.")
     (1634 nil (:alt (:diplomatic "imper. acci.")
                     (:idealised "imper. acci.")
                     (:comment "»acci.« könnte hier in »natur.« korrigiert werden, abhängig davon, ob man den _quarto ordine_ bzw. die Mischung aus _primo_ und _quarto ordine_ als _naturale_ oder _accidentale_ betrachtet. Siehe 5.43f.")
                     (:flag :observe) (:id 7)))
     (1936 nil (:alt (:diplomatic "impe. accid.")
                     (:idealised "impe. accid.")
                     (:comment "»accid.« könnte hier in »natur.« korrigiert werden, abhängig davon, ob man den _quarto ordine_ bzw. die Mischung aus _primo_ und _quarto ordine_ als _naturale_ oder _accidentale_ betrachtet. Siehe 5.43f.")
                     (:flag :observe) (:id 8))))
   (:text 70 58
          (81 nil "comp.")
          (420 nil "incomp.")
          (738 nil "incomp.")
          (1056 nil "comp.")
          (1350 nil "incomp.")
          (1620 nil "comp.")
          (1938 nil "incomp."))))
