`((:header
   (:filename "b1-c11-m3")
   (:alt-name "m1.020")
   (:comment "q021_s031, origin: 498")
   (:creator "Vicentino21 / Johannes Keller")
   (:section-captions
    (s1 (:alt (:it "per ♮ incitato")
              (:de "per ♮ incitato")
              (:en "in ♮ incitato")))
    (s2 (:alt (:it "per ♭ molle")
              (:de "per ♭ molle")
              (:en "in ♭ molle")))
    (s3 (:alt (:it "per natura")
              (:de "per natura")
              (:en "in natural")))))
  (:preamble-lilypond
   (:lyrics
    (s1 v1 (:alt (:it "la sol fa la sol")
                 (:de "la sol fa la sol")
                 (:en "la sol fa la sol")))
    (s2 v1 (:alt (:it "la sol fa mi re")
                 (:de "la sol fa mi re")
                 (:en "la sol fa mi re")))
    (s3 v1 (:alt (:it "sol fa la sol fa mi mi")
                 (:de "sol fa la sol fa mi mi")
                 (:en "sol fa la sol fa mi mi")))
    ))
  (:data
   (:music 2200
           (:voice v1)
           (:section s1)
           cclef7 b38 sb5 b38 fl5 b38 sbd5 b22 sh4 b22 sb4 b38 sbd4 b38 sb4 b38
           (:section s2)
           cclef7 b38 fl6 (:key-signature nil nil nil nil nil nil :flat)
           b38 sb5 b38 fl5 b38 sbd5 b38 fl5 b38 sb5 b22 sbd4 b38 sb4 b22 bl
           (:section s3)
           (:key-signature nil nil nil nil nil nil nil)
           b22 sb4 b38 fl4 b38 sbd4 b22 fl4 b22 sb4 b38 sbd3 b38 sb3 b38 sbd2 b22 sb2)
   (:text 70 58
          (120 nil "la")
          (263 nil "ſol")
          (400 nil "fa")
          (493 nil "la")
          (572 nil "ſol")
          (858 nil "la")
          (1022 nil "ſol")
          (1188 nil "fa")
          (1281 nil "mi")
          (1365 nil "re")
          (1506 nil "ſol")
          (1670 nil "fa")
          (1813 nil "la")
          (1899 nil "ſol")
          (1990 nil "fa")
          (2064 nil "mi")
          (2135 nil "mi"))
   (:text 70 58
          (116 nil "per ♮. incitato")
          (850 nil "per ♭. molle")
          (1502 nil "per natura"))))
