`((:header
   (:filename "b5-c52-m2")
   (:alt-name "m5.057")
   (:comment "q021_s255, rotation: 0, origin: 548")
   (:creator "Vicentino21 / Johannes Keller")
   (:section-headings
    (s1 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s2 (:alt (:it "Semitono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s3 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s4 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))

    (s5 (:alt (:it "Semitono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s6 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s7 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))

    (s8 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
              (:de "")
              (:en "")))
    (s9 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
              (:de "")
              (:en "")))
    (s10 (:alt (:it "Semitono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en "")))
    (s11 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en "")))

    (s12 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en "")))
    (s13 (:alt (:it "Semitono cromatico \\accidentale\\[discendente]")
               (:de "")
               (:en "")))
    (s14 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en ""))))
   (:section-captions
    (s1 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
              (:de "")
              (:en "")))
    (s2 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis minore – diesis minore – diesis minore")
              (:de "")
              (:en "")))
    (s3 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
              (:de "")
              (:en "")))
    (s4 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
              (:de "")
              (:en "")))

    (s5 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis minore – diesis minore – diesis minore")
              (:de "")
              (:en "")))
    (s6 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
              (:de "")
              (:en "")))
    (s7 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
              (:de "")
              (:en "")))

    (s8 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
              (:de "")
              (:en "")))
    (s9 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
              (:de "")
              (:en "")))
    (s10 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis minore – diesis minore – diesis minore")
               (:de "")
               (:en "")))
    (s11 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
               (:de "")
               (:en "")))

    (s12 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
               (:de "")
               (:en "")))
    (s13 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis minore – diesis minore – diesis minore")
               (:de "")
               (:en "")))
    (s14 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
               (:de "")
               (:en "")))))
  (:data
   (:text 90 58
     (100 nil "Se.")
     (218 nil "mi.")
     (379 nil "se.")
     (488 nil "mag.")
     (688 nil "se.")
     (797 nil "mi. & ma.")
     (1143 nil "se.")
     (1252 nil "mi.")
     (1373 nil "se.")
     (1477 nil "mag.")
     (1695 nil "se.")
     (1811 nil "mi.")
     (1932 nil "se.")
     (2038 nil "mag."))
   (:music 2230
           (:voice v1)
           (:section s1) (:f-clef) max7 fclef7 b38 fl2 sbd2 b22 sb2 b22 sbd2 b22 sh2 sb2 b22 fl3 sbd3 b22 bl
           (:section s2) b22 fl3 sbd3 b22 sb3 b22 sbd3 sh3 sb3 b22 b38 bl
           (:section s3) b22 sh3 sb3 b22 sb4 b22 sbd4 b22 sh4 sb4 b22 fl5 sbd5 b22 bl
           (:section s4) (:newline) b22 fl5 sbd5 b22 sb5 b22 sbd5 sh5 sb5 fl6 sbd6 bl)
   (:text 70 58
     (48 nil "ᴅ.mi.d.mi.di.mi.d.ma.")

     (:alt (:diplomatic (593 nil "d.mi.d.mi.d.mi.d.mi."))
           (:idealised (593 nil "d.mi.d.mi.d.mi."))
           (:comment "Original: »d.mi.d.mi.d.mi.d.mi.«")
           (:flag :draft) (:id 7))
     (1118 nil "d.mi. d.mi. d.mi. d.ma.")
     (1704 nil "d.mi.d.mi.d.mi.d.ma."))
   (:text 110 58
     (102 nil "Tono")
     (281 nil "ᴄro.")
     (484 nil "acc.")
     (708 nil "Se.")
     (818 nil "cro.")
     (954 nil "acc.")
     (1163 nil "ᴛono")
     (1358 nil "cro.")
     (1536 nil "acc.")
     (1729 nil "Tono.")
     (1915 nil "cro.")
     (2040 nil "acc."))
   (:text 110 58
     (144 nil "Se.")
     (262 nil "mi.")
     (394 nil "& mag.")
     (818 nil "se.")
     (921 nil "mi.")
     (1087 nil "se.")
     (1193 nil "mag.")
     (1518 nil "se.")
     (1627 nil "mi.")
     (1787 nil "se.")
     (1936 nil "mag."))
   (:music 2220
           (:section s5) (:f-clef) max7 fclef7 b38 fl6 b22 sbd6 b38 sb6 b38 sbd6 b38 sh6 b22 sb6 b38 bl
           (:section s6) b38 sh6 b22 sb6 b38 sb7 b38 sbd7 b38 sh7 b22 sb7 b38 fl8 b22 sbd8 b38 bl
           (:section s7) (:newline) b38 fl8 b22 sbd8 b38 sb8 b38 sbd8 b22 sh8 sb8 b38 fl9 b22 sbd9 b38 bl b38 b38)
   (:text 90 58
     (91 nil "d.mi. d.mi. d.mi. d.mi.")
     (743 nil "d.mi. d.mi. d.mi. d.ma.")
     (1500 nil "d.mi. d.mi. d.mi. d.ma."))
   (:text 110 58
     (175 nil "se.")
     (327 nil "ᴄro.")
     (520 nil "acc.")
     (779 nil "ᴛono")
     (988 nil "ᴄro.")
     (1172 nil "acc.")
     (1529 nil "Tono")
     (1742 nil "ᴄro.")
     (1925 nil "acc."))
   (:text 110 58
     (180 nil "Se.")
     (305 nil "mi.")
     (466 nil "se.")
     (577 nil "ma.")
     (870 nil "se.")
     (984 nil "mi.")
     (1148 nil "se.")
     (1263 nil "ma.")
     (1516 nil "se.")
     (1625 nil "mi. & ma.")
     (1998 nil "se.")
     (2113 nil "mi."))
   (:music 2230
           (:section s8) (:f-clef) max7 fclef7 b38 fl9 b22 sbd9 b22 fl9 sb9 b22 sh8 sb8 b22 sbd8 b22 fl8 b22 sbd8 b22 bl
           (:section s9) b22 fl8 b22 sbd8 b22 fl8 b22 sb8 b22 sh8 sb8 b22 sbd7 b22 sh6 sb6 b22 bl
           (:section s10) (:newline) b22 sh6 sb6 b22 sbd6 b22 sb6 b22 fl6 b22 sbd6 b22 bl
           (:section s11) b22 fl6 sbd6 fl6 sb6 custos5)
   (:text 100 58
     (145 nil "ᴅ.mi. d.mi. d.mi. d.ma.")
     (811 nil "d.mi.d.mi. d.mi. d.ma.")
     (:alt (:diplomatic (1397 nil "d.mi.d.mi.d.mi.d.ma."))
           (:idealised (1397 nil "d.mi.d.mi.d.ma."))
           (:comment "Original: »d.mi.d.mi.d.mi.d.ma.«")
           (:flag :draft) (:id 8))
     (1973 nil "d.mi.d.mi."))
   (:text 120 58
     (182 nil "Tono")
     (400 nil "cro.")
     (577 nil "acc.")
     (868 nil "ᴛono")
     (1063 nil "Cro.")
     (1263 nil "acc.")
     (1523 nil "se.")
     (1636 nil "cro.")
     (1807 nil "acc.")
     (2034 nil "ᴛono"))
   (:text 100 58
     (134 nil "se.")
     (252 nil "ma.")
     (511 nil "se.")
     (620 nil "mi.")
     (739 nil "se.")
     (850 nil "mag.")
     (1143 nil "se.")
     (1252 nil "mi. & ma.")
     (1670 nil "se.")
     (1779 nil "mi.")
     (1898 nil "se.")
     (2007 nil "ma."))
   (:music 2232
           (:f-clef) max7 fclef7 b22 sh5 sb5 sbd5 fl5 sbd5 b22 bl
           (:section s12) b22 fl5 b22 sbd5 b22 fl5 b22 sb5 b22 sh4 sb4 sbd4 fl4 sbd4 b22 bl
           (:section s13) (:newline) b38
           (:alt (:diplomatic fl4 b22 sbd4)
                 (:idealised b38 b22 sbd4)
                 (:comment "Original: Die erste Note ist ein Ċ♭.")
                 (:flag :draft) (:id 1))
           b22
           (:alt (:diplomatic fl4 b22 sb4)
                 (:idealised b38 b22 sb4)
                 (:comment "Original: Die zweite Note ist ein C.")
                 (:flag :draft) (:id 2))
           b22 sh3 b22 sb3 b22 sbd3 b38 b38 bl
           (:section s14) b22
           (:alt (:diplomatic sbd3)
                 (:idealised fl3 sbd3)
                 (:comment "Original: Die erste Note ist ein Ḃ♮")
                 (:flag :draft) (:id 3))
           b22
           (:alt (:diplomatic sb3)
                 (:idealised fl3 sb3)
                 (:comment "Original: Die zweite Note ist ein B♮.")
                 (:flag :draft) (:id 4))
           b22
           (:alt (:diplomatic fl3 sbd3)
                 (:idealised sh2 sb2)
                 (:comment "Original: Die dritte Note ist ein Ḃ♭.")
                 (:flag :draft) (:id 5))
           (:alt (:diplomatic sh2 sb2)
                 (:idealised sbd2)
                 (:comment "Original: Die vierte Note ist ein A♯.")
                 (:flag :draft) (:id 6))
           fl2 sbd2 b38 bl)
   (:text 90 58
     (98 nil "di. mi. di.ma.")
     (466 nil "d.mi. d.mi. d.mi.d.ma.")
     (:alt (:diplomatic (1086 nil "d.mi. d.mi. di.mi. d.ma."))
           (:idealised (1086 nil "d.mi. d.mi. di.mi."))
           (:comment "Original: »d.mi. d.mi. di.mi. d.ma.«")
           (:flag :draft) (:id 9))
     (1720 nil "d.mi.d.mi.d.mi.d.ma."))
   (:text 70 58
     (94 nil "ᴄro.")
     (246 nil "acc.")
     (476 nil "ᴛono")
     (678 nil "cro.")
     (855 nil "acc.")
     (1159 nil "se.")
     (1266 nil "cro.")
     (1401 nil "acc.")
     (1644 nil "Tono")
     (1837 nil "cro.")
     (2007 nil "acc."))))
