`((:header
   (:filename "b5-c24-m1")
   (:alt-name "m5.020")
   (:comment "q021_s225, rotation: 0, origin: 509")
   (:creator "Vicentino21 / Johannes Keller")
   (:title "Queste sono tutte le consonanze di Elami acuto discendente,\\e di Elami grave ascendente")
   (:section-headings
    (s1 "Le cinque terze\\[discendenti]")
    (s2 " \\Quinta")
    (s3 "Le cinque seste\\[discendenti]")
    (s4 " \\Ottava")
    (s5 "Le quattro terze\\[ascendenti]")
    (s6 " \\Quinta")
    (s7 "Le quattro seste\\[ascendenti]")
    (s8 " \\Ottava"))
   (:section-captions
    (s1 "Terza minore / terza maggiore")
    (s3 "Sesta minore / sesta maggiore")
    (s5 "Terza minore / terza maggiore")
    (s7 "Sesta minore / sesta maggiore")))
  (:preamble-type-imitation
   (:width nil)
   (:height nil)
   (:background ,*score-bg-color*))
  (:data
   (:text 110 58
          (18 2209 "Queſte ſono tutte le conſonanze di Elami acuto diſcentende,& di Elami graue aſcendente."))
   (:text 110 58
          (57 nil "le cinque 3.")
          (537 nil "5.")
          (646 nil "le cinque 6.")
          (1059 nil "8.")
          (1252 nil "le quattro 3.")
          (1616 nil "5.")
          (1762 nil "la quattro 6.")
          (2123 nil "8."))
   (:music 2230
           (:voice v1)
           (:section s1)
           (:section s2)
           (:section s3)
           (:section s4)
           (:section s5)
           (:section s6)
           (:section s7)
           (:section s8))
   (:text 130 58
          (59 nil "3.min.")
          (305 nil "3.mag.")
          (668 nil "6.min.")
          (880 nil "6.mag.")
          (1239 nil "3.mi.")
          (1423 nil "3.mag.")
          (1702 nil (:alt (:diplomatic "3.min.")
                          (:idealised "6.min.")))
          (1919 nil (:alt (:diplomatic "3.mag.")
                          (:idealised "6.mag."))))
   (:music 2223
           (:section s1) (:newline)
           (:section s2)
           (:section s3)
           (:section s4)
           (:section s5)
           (:section s6)
           (:section s7)
           (:section s8))))
