`((:header
   (:filename "b5-c59-m1")
   (:alt-name "m")
   (:comment "q021_s268, rotation: 0.95, origin: 1000; q021_s269, rotation: 0.96, origin: 477; q021_s270, rotation: 0, origin: 964; q021_s271, rotation: 0, origin: 534")
   (:creator "Vicentino21 / Johannes Keller")
   (:title (:alt (:it "Esempio delle note scritte secondo\\l'uso naturale nelle tre chiavi")
                 (:de "")
                 (:en "")))
   (:section-headings
    ((:alt (:original-layout s1)
           (:alternative-layout s1)
           (:flag :layout) (:id 0))
     (:alt (:it "Primo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s2)
           (:alternative-layout s9)
           (:flag :layout) (:id 0))
     (:alt (:it "Secondo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s3)
           (:alternative-layout s17)
           (:flag :layout) (:id 0))
     (:alt (:it "Terzo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s4)
           (:alternative-layout s25)
           (:flag :layout) (:id 0))
     (:alt (:it "Quarto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s5)
           (:alternative-layout s33)
           (:flag :layout) (:id 0))
     (:alt (:it "Quinto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s6)
           (:alternative-layout s41)
           (:flag :layout) (:id 0))
     (:alt (:it "Sesto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s7)
           (:alternative-layout s49)
           (:flag :layout) (:id 0))
     (:alt (:it "Settimo ordine")
           (:de "")
           (:en "")))

    ((:alt (:original-layout s8)
           (:alternative-layout s2)
           (:flag :layout) (:id 0))
     (:alt (:it "Del primo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s9)
           (:alternative-layout s10)
           (:flag :layout) (:id 0))
     (:alt (:it "Del secondo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s10)
           (:alternative-layout s18)
           (:flag :layout) (:id 0))
     (:alt (:it "Del terzo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s11)
           (:alternative-layout s26)
           (:flag :layout) (:id 0))
     (:alt (:it "Del quarto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s12)
           (:alternative-layout s34)
           (:flag :layout) (:id 0))
     (:alt (:it "Del quinto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s13)
           (:alternative-layout s42)
           (:flag :layout) (:id 0))
     (:alt (:it "Del sesto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s14)
           (:alternative-layout s56)
           (:flag :layout) (:id 0))
     (:alt (:it "Del settimo ordine")
           (:de "")
           (:en "")))

    ((:alt (:original-layout s15)
           (:alternative-layout s3)
           (:flag :layout) (:id 0))
     (:alt (:it "Del primo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s16)
           (:alternative-layout s11)
           (:flag :layout) (:id 0))
     (:alt (:it "Del secondo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s17)
           (:alternative-layout s19)
           (:flag :layout) (:id 0))
     (:alt (:it "Del terzo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s18)
           (:alternative-layout s27)
           (:flag :layout) (:id 0))
     (:alt (:it "Del quarto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s19)
           (:alternative-layout s27)
           (:flag :layout) (:id 0))
     (:alt (:it "Del quinto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s20)
           (:alternative-layout s35)
           (:flag :layout) (:id 0))
     (:alt (:it "Del sesto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s21)
           (:alternative-layout s43)
           (:flag :layout) (:id 0))
     (:alt (:it "Del settimo ordine")
           (:de "")
           (:en "")))

    ((:alt (:original-layout s22)
           (:alternative-layout s4)
           (:flag :layout) (:id 0))
     (:alt (:it "Del primo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s23)
           (:alternative-layout s12)
           (:flag :layout) (:id 0))
     (:alt (:it "Del secondo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s24)
           (:alternative-layout s20)
           (:flag :layout) (:id 0))
     (:alt (:it "Del terzo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s25)
           (:alternative-layout s28)
           (:flag :layout) (:id 0))
     (:alt (:it "Del quarto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s26)
           (:alternative-layout s36)
           (:flag :layout) (:id 0))
     (:alt (:it "Del quinto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s27)
           (:alternative-layout s44)
           (:flag :layout) (:id 0))
     (:alt (:it "Del sesto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s28)
           (:alternative-layout s44)
           (:flag :layout) (:id 0))
     (:alt (:it "Del settimo ordine")
           (:de "")
           (:en "")))

    ((:alt (:original-layout s29)
           (:alternative-layout s5)
           (:flag :layout) (:id 0))
     (:alt (:it "Del primo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s30)
           (:alternative-layout s13)
           (:flag :layout) (:id 0))
     (:alt (:it "Del secondo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s31)
           (:alternative-layout s21)
           (:flag :layout) (:id 0))
     (:alt (:it "Del terzo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s32)
           (:alternative-layout s29)
           (:flag :layout) (:id 0))
     (:alt (:it "Del quarto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s33)
           (:alternative-layout s37)
           (:flag :layout) (:id 0))
     (:alt (:it "Del quinto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s34)
           (:alternative-layout s45)
           (:flag :layout) (:id 0))
     (:alt (:it "Del sesto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s35)
           (:alternative-layout s53)
           (:flag :layout) (:id 0))
     (:alt (:it "Del settimo ordine")
           (:de "")
           (:en "")))

    ((:alt (:original-layout s36)
           (:alternative-layout s6)
           (:flag :layout) (:id 0))
     (:alt (:it "Del primo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s37)
           (:alternative-layout s14)
           (:flag :layout) (:id 0))
     (:alt (:it "Del secondo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s38)
           (:alternative-layout s22)
           (:flag :layout) (:id 0))
     (:alt (:it "Del terzo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s39)
           (:alternative-layout s30)
           (:flag :layout) (:id 0))
     (:alt (:it "Del quarto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s40)
           (:alternative-layout s38)
           (:flag :layout) (:id 0))
     (:alt (:it "Del quinto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s41)
           (:alternative-layout s46)
           (:flag :layout) (:id 0))
     (:alt (:it "Del sesto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s42)
           (:alternative-layout s54)
           (:flag :layout) (:id 0))
     (:alt (:it "Del settimo ordine")
           (:de "")
           (:en "")))

    ((:alt (:original-layout s43)
           (:alternative-layout s7)
           (:flag :layout) (:id 0))
     (:alt (:it "Del primo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s44)
           (:alternative-layout s15)
           (:flag :layout) (:id 0))
     (:alt (:it "Del secondo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s45)
           (:alternative-layout s23)
           (:flag :layout) (:id 0))
     (:alt (:it "Del terzo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s46)
           (:alternative-layout s31)
           (:flag :layout) (:id 0))
     (:alt (:it "Del quarto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s47)
           (:alternative-layout s39)
           (:flag :layout) (:id 0))
     (:alt (:it "Del quinto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s48)
           (:alternative-layout s47)
           (:flag :layout) (:id 0))
     (:alt (:it "Del sesto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s49)
           (:alternative-layout s55)
           (:flag :layout) (:id 0))
     (:alt (:it "Del settimo ordine")
           (:de "")
           (:en "")))

    ((:alt (:original-layout s50)
           (:alternative-layout s8)
           (:flag :layout) (:id 0))
     (:alt (:it "Del primo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s51)
           (:alternative-layout s16)
           (:flag :layout) (:id 0))
     (:alt (:it "Del secondo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s52)
           (:alternative-layout s24)
           (:flag :layout) (:id 0))
     (:alt (:it "Del terzo ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s53)
           (:alternative-layout s32)
           (:flag :layout) (:id 0))
     (:alt (:it "Del quarto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s54)
           (:alternative-layout s40)
           (:flag :layout) (:id 0))
     (:alt (:it "Del quinto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s55)
           (:alternative-layout s48)
           (:flag :layout) (:id 0))
     (:alt (:it "Del sesto ordine")
           (:de "")
           (:en "")))
    ((:alt (:original-layout s56)
           (:alternative-layout s56)
           (:flag :layout) (:id 0))
     (:alt (:it "Del settimo ordine")
           (:de "")
           (:en "")))))
  (:data
   ;; Seite 1, fol. 134v, S. 268
   (:text 110 58
          (348 1511 "Eſſempio delle note ſcritte ſecondo lʼuſo naturale nelle tre chiaui."))
   (:text 110 58
          (334 nil "Primo ordine.")
          (1350 nil "Secondo ordine."))
   (:music 2223
           (:voice v1)
           (:section (:alt (:original-layout s1)
                           (:alternative-layout s1)
                           (:flag :layout) (:id 0)))
           gclef3 b38 sb0 b38 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b38 sb6 b38 sb7 b38 sb8 b38 sb9 b38 sb10 b38 b38
           (:section (:alt (:original-layout s2)
                           (:alternative-layout s9)
                           (:flag :layout) (:id 0)))
           gclef3 b22 fl5 (:key-signature nil nil nil nil nil nil :flat)
           sb0 b38 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b38 sb6 b38 sb7 b38 sb8 b38 sb9 b38 sb10 b22 bl)
   (:text 110 58
          (325 nil "Del primo ordine.")
          (1333 nil "ᴅel secondo ordine."))
   (:music 2227
           (:section (:alt (:original-layout s8)
                           (:alternative-layout s2)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout (:newline))
                 (:alternative-layout)
                 (:flag :layout) (:id 0))
           (:key-signature nil nil nil nil nil nil nil) cclef1 b22 sb0 b22 sh1 sb1 b22 sb2 b22 sb3 b22 sh4 sb4 b22 sh5 sb5 b22 sb6 b22 sb7 b22 sh8 sb8 b22 sb9 sb10 b38
           (:section (:alt (:original-layout s9)
                           (:alternative-layout s10)
                           (:flag :layout) (:id 0)))
           cclef1 b22 sb0 b22 sh1 b22 sb1 b22 sb2 b22 sb3 b22 sh4 b22 sb4 b22 sb5 b22 sb6 b22 sb7 b22 sh8 b22 sb8 b22 sb9 b22 sb10 bl)
   (:text 110 58
          (327 nil "Del primo ordine.")
          (1341 nil "Del secondo ordine."))
   (:music 2223
           (:section (:alt (:original-layout s15)
                           (:alternative-layout s3)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout (:newline))
                 (:alternative-layout)
                 (:flag :layout) (:id 0))
           cclef3 b22 fl29 (:key-signature nil nil nil nil nil nil :flat)
           b22 sb0 b22 sb1 b22 sb2 b22 sb3 b22 sb4 b22 sb5 b22 sb6 b38 sb7 b38 sb8 b38 sb9 b38 sb10 b22 b38
           (:section (:alt (:original-layout s16)
                           (:alternative-layout s11)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))

           cclef3 b22 fl2
           (:alt (:diplomatic fl4) (:idealised fl5)
                 (:comment "Original: ♭ steht eine Position tiefer.") (:flat :draft) (:id 2))
           (:key-signature nil nil :flat nil nil nil :flat)
           b38 sb0 b38 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b38 sb6 b38 sb7 b38 sb8 b38 sb9 b38 sb10 bl)
   (:text 110 58
          (339 nil "Del primo ordine.")
          (1341 nil "ᴅel secondo ordine."))
   (:music 2225
           (:section (:alt (:original-layout s22)
                           (:alternative-layout s4)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout (:newline))
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))
           (:key-signature nil nil nil nil nil nil nil)
           cclef5 b22 sb0 b22 sh1 b22 sb1 b22 sb2 b22 sb3 b22 sb4 b22 sh5 b22 sb5 b22 sb6 b38 sb7 b38 sh8 b22 sb8 b22 sb9 b22 sb10 b22
           (:section (:alt (:original-layout s23)
                           (:alternative-layout s12)
                           (:flag :layout) (:id 0)))
           cclef5 b22 sb0 b22 sh1 b22 sb1 b22 sb2 b22 sb3 b22 sb4 b22 sb5 b22 sb6 b38 sb7 b38 sh8 b38 sb8 b22 sb9 sb10 bl)
   (:text 110 58
          (334 nil "Del primo ordine.")
          (1320 nil "Del secondo ordine."))
   (:music 2215
           (:section (:alt (:original-layout s29)
                           (:alternative-layout s5)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout (:newline))
                 (:alternative-layout)
                 (:flag :layout) (:id 0))
           cclef7 b22 fl29
           (:alt (:diplomatic fl5) (:idealised fl6)
                 (:comment "Original: ♭ steht eine Position tiefer.")
                 (:flat :draft) (:id 3))
           (:key-signature nil nil :flat nil nil nil :flat)
           b22 sb0 b22 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b38 sb6 b38 sb7 b38 sb8 b38 sb9 b22 sb10 b22
           (:section (:alt (:original-layout s30)
                           (:alternative-layout s13)
                           (:flag :layout) (:id 0)))
           cclef7 fl29 fl5 fl6 (:key-signature nil nil :flat nil nil :flat :flat)
           b22 sb0 b38 sb1 b38 sb2 b38 sb3 b38 sb4 b22 sb5 b22 sb6 b38 sb7 b22 sb8 b22 sb9 b38 sb10 bl)
   (:text 110 58
          (343 nil "Del primo ordine.")
          (1345 nil "ᴅel secondo ordine."))
   (:music 2209
           (:section (:alt (:original-layout s36)
                           (:alternative-layout s6)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout (:newline))
                 (:alternative-layout)
                 (:flag :layout) (:id 0))
           (:f-clef) max5 fclef5 (:key-signature nil nil nil nil nil nil nil)
           b38 sb0 b38 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sh5 b22 sb5 b38 sb6 b38 sb7 b38 sb8 b38 sb9 b22 sb10 b22
           (:section (:alt (:original-layout s37)
                           (:alternative-layout s14)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))
           (:f-clef) max5 fclef5 b22 sb0 b38 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b38 sb6 b38 sb7 b38 sb8 b38 sb9 b22 sb10 bl)
   (:text 110 58
          (329 nil "Del primo ordine.")
          (1327 nil "ᴅel secondo ordine."))
   (:music 2204
           (:section (:alt (:original-layout s43)
                           (:alternative-layout s7)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout (:newline))
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))
           (:f-clef) max7 fclef7 b22 fl29 fl3 fl6 (:key-signature nil nil :flat nil nil :flat :flat)
           b22 sb0 b22 sb1 b22 sb2 b22 sb3 b22 sb4 b22 sb5 b22 sb6 b22 sb7 b22 sb8 b22 sb9 b22 sb10 b22
           (:section (:alt (:original-layout s44)
                           (:alternative-layout s15)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))

           (:f-clef) max7 fclef7 fl29 fl3 fl5 fl6 (:key-signature nil :flat :flat nil nil :flat :flat)
           b22 sb0 b22 sb1 b22 sb2 b22 sb3 b22 sb4 b22 sb5 b38 sb6 b38 sb7 b22 sb8 b22 sb9 b22 sb10 bl)
   (:text 110 58
          (332 nil "Del primo ordine.")
          (1309 nil "ᴅel secondo ordine."))
   (:music 2207
           (:section (:alt (:original-layout s50)
                           (:alternative-layout s8)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout (:newline))
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))
           (:f-clef) max9 fclef9 (:key-signature nil nil nil nil nil nil nil)
           b38 sb0 b38 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b38 sb6 b38 sb7 b22 sb8 b22 sb9 b38 sb10 b38
           (:section (:alt (:original-layout s51)
                           (:alternative-layout s16)
                           (:flag :layout) (:id 0)))
           (:f-clef) max9 fclef9 b22 fl5 (:key-signature nil nil nil nil nil nil :flat)
           b38 sb0 b38 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b38 sb6 b22 sb7 b22 sb8 b22 sb9 b38 sb10 b38 bl)

   (:vspace 200)

   ;; Seite 2, fol. 135r, S. 269
   (:text 110 58
          (345 nil "Terzo ordine.")
          (1332 nil "Quarto ordine."))
   (:music 2221
           (:section (:alt (:original-layout s3)
                           (:alternative-layout s17)
                           (:flag :layout) (:id 0)))
           (:key-signature nil nil nil nil nil nil nil)
           cclef1 b38 sb0 b38 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b38 sb6 b38 sb7 b38 sb8 b38 sb9 b38 sb10 b38 b22 b22
           (:section (:alt (:original-layout s4)
                           (:alternative-layout s25)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))

           cclef7 b38 sb0 b38 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b38 sb6 b38 sb7 b38 sb8 b38 sb9 b38 sb10 b38 bl)
   (:text 110 58
          (347 nil "ᴅel terzo ordine.")
          (1404 nil "Del quarto ordine."))
   (:music 2225
           (:section (:alt (:original-layout s10)
                           (:alternative-layout s18)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))

           gclef3 b22 sb0 b22 fl1 b22 sb1 b22 sb2 b22 sb3 b22 fl4 b22 sb4 b22 fl5 b22 sb5 sb6 sb7 b22 fl8 b22 sb8 b22 sb9 b22 sb10 b22
           (:section (:alt (:original-layout s11)
                           (:alternative-layout s26)
                           (:flag :layout) (:id 0)))
           gclef3 b22 sb0 b22 sb1 b22 sh2 sb2 b22 sb3 b22 sb4 b22 sb5 b22 sh6 b22 sb6 b22 sb7 b22 sb8 b22 sh9 b22 sb9 b22 sb10 bl)
   (:text 110 58
          (352 nil "ᴅel terzo ordine.")
          (1434 nil "ᴅel quarto ordine."))
   (:music 2223
           (:section (:alt (:original-layout s17)
                           (:alternative-layout s19)
                           (:flag :layout) (:id 0)))
           cclef3 b22 b22 sb0
           (:alt (:diplomatic sh0) (:idealised sh1)
                 (:comment "Original: ♯ steht eine Position tiefer.")
                 (:flag :draft) (:id 4))
           sb1 sb2 sh3 sb3 sb4 sb5 b22 sh6 sb6 b22 sh7 b22 sb7 b22 sb8 b22 sh9 sb9 b22 sh10 sb10 b38
           (:section (:alt (:original-layout s18)
                           (:alternative-layout s27)
                           (:flag :layout) (:id 0)))
           cclef3 b38 sb0 b38 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b38 sh6 b22 sb6 b22 sb7 b38 sb8 b22 sb9 b22 sb10 bl)
   (:text 110 58
          (342 nil "ᴅel terzo ordine.")
          (1398 nil "ᴅel quarto ordine."))
   (:music 2209
           (:section (:alt (:original-layout s24)
                           (:alternative-layout s20)
                           (:flag :layout) (:id 0)))
           cclef5 b38 fl4 (:key-signature nil nil nil nil nil nil :flat)
           b38 sb0 b38 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b38 sb6 b38 sb7 b38 sb8 b38 sb9 b38 sb10 b22
           (:section (:alt (:original-layout s25)
                           (:alternative-layout s28)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))
           cclef5 (:key-signature nil nil nil nil nil nil nil)
           b22 sb0 b22 sh1 sb1 b22 sh2 sb2 b22 sb3 b22 sb4 sh5 sb5 b22 sh6 sb6 b22 sb7 sh8 sb8 sh9 sb9 sb10 bl)
   (:text 110 58
          (335 nil "ᴅel terzo ordine.")
          (1405 nil "Del quarto ordine."))
   (:music 2206
           (:section (:alt (:original-layout s31)
                           (:alternative-layout s21)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))
           cclef7 sb0 fl1 sb1 fl2 sb2 b22 sb3 b22 fl4 sb4 b22 fl5 sb5 b22 fl6 sb6 b22 sb7 b22 fl8 sb8 b22 fl9 sb9 b22 sb10 b22
           (:section (:alt (:original-layout s32)
                           (:alternative-layout s29)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))

           cclef1 b22 sb0 b22 sh1 sb1 b22 sh2 b22 sb2 b22 sb3 b22 sh4 sb4 sh5 sb5 sh6 sb6 sb7 sh8 sb8 sh9 sb9 sb10 bl)
   (:text 110 58
          (332 nil "Del terzo ordine.")
          (1394 nil "Del quarto ordine."))
   (:music 2205
           (:section (:alt (:original-layout s38)
                           (:alternative-layout s22)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))

           (:f-clef) max5 fclef5 b22 fl18 fl4 (:key-signature nil nil :flat nil nil nil :flat)
           b22 sb0 b22 sb1 b38 sb2 b22 sb3 b22 sb4 b22 sb5 b22 sb6 b22 sb7 b22 sb8 b38 sb9 b22 sb10
           (:section (:alt (:original-layout s39)
                           (:alternative-layout s30)
                           (:flag :layout) (:id 0)))
           (:f-clef) max5 fclef5 (:key-signature nil nil nil nil nil nil nil)
           b22 sb0 sb1 sh2 sb2 b22 sb3 b22 sb4 b22 sh5 sb5 b22 sh6 b22 sb6 b22 sb7 b22 sb8 b22 sh9 b22 sb9 b22 sb10 b22 bl)
   (:text 110 58
          (341 nil "ᴅel terzo ordine.")
          (1393 nil "Del quarto ordine."))
   (:music 2209
           (:section (:alt (:original-layout s45)
                           (:alternative-layout s23)
                           (:flag :layout) (:id 0)))
           (:f-clef) max7 fclef7 b38 sb0 fl1 sb1 b22 fl2 sb2 b22 fl3 sb3 b22 sbd3 b22 fl5 sb5 b22 fl6 sb6 b22 sb7 b22 fl8 sb8 b22 fl9 sb9 fl10 sb10 b38
           (:section (:alt (:original-layout s46)
                           (:alternative-layout s31)
                           (:flag :layout) (:id 0)))
           (:f-clef) max7 fclef7 b22 fl310 (:key-signature nil nil nil nil nil nil :flat)
           b22 sb0 b22 sb1 b22 sb2 b22 sb3 b22 sb4 b22 sb5 b22 sb6 b22 sb7 b22 sb8 b22 sb9 b22 sb10 bl)
   (:text 110 58
          (345 nil "ᴅel terȥo ordine.")
          (1402 nil "Del quarto ordine."))
   (:music 2207
           (:section (:alt (:original-layout s52)
                           (:alternative-layout s24)
                           (:flag :layout) (:id 0)))
           (:f-clef) max9 fclef9 b22 (:key-signature nil nil nil nil nil nil nil)
           sb0 b22 fl1 b22 sb1 b22 sb2 b22 sb3 b22 fl4 b22 sb4 b22 fl5 sb5 b22 sb6 b22 sb7 b22 fl8 sb8 b22 sb9 b22 sb10 b38
           (:section (:alt (:original-layout s53)
                           (:alternative-layout s32)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))

           (:f-clef) max9 fclef9 sb0 b22 sb1 b22 sh2 b22 sb2 b22 sb3 b22 sb4 b22 sb5 b22 sh6 sb6 b22 sb7 b22 sb8 b22 sh9 sb9 sb10 bl)
   (:vspace 110)
   (:music 2213
           b125 b125 b125 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b22 b38 b125)
   (:vspace 110)
   (:music 2210
           b125 b125 b125 b125 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b38 b125 b125 b125 b38 b125)
   (:vspace 200)


   ;; Seite 3, fol. 135v, S. 270
   (:text 110 58
          (323 nil "Quinto ordine.")
          (1359 nil "Seſto ordine."))
   (:music 2237
           (:section (:alt (:original-layout s5)
                           (:alternative-layout s33)
                           (:flag :layout) (:id 0)))
           cclef3 b38 sb0 b38 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b38 sb6 b38 sb7 b38 sb8 b38 sb9 b38 sb10 b38 b38 b38
           (:section (:alt (:original-layout s6)
                           (:alternative-layout s41)
                           (:flag :layout) (:id 0)))
           cclef5 b38 sb0 b38 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b38 sb6 b38 sb7 b38 sb8 b38 sb9 b38 sb10 b22 b22 bl)
   (:text 110 58
          (329 nil "Del quinto ordine.")
          (1341 nil "ᴅel seſto ordine."))
   (:music 2232
           (:section (:alt (:original-layout s12)
                           (:alternative-layout s34)
                           (:flag :layout) (:id 0)))
           gclef3 b22 sb0 b22 sb1 b22 sh2 b22 sb2 b22 sb3 b22 sb4 b22 sb5 b22 sb6 b22 sb7 b22 sb8 b22 sh9 b22 sb9 b22 sb10 b38 b38
           (:section (:alt (:original-layout s13)
                           (:alternative-layout s42)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))
           gclef3 b22 sb0 b22 fl1 b22 sb1 b22 sb2 b22 sb3 b22 sb4 b22 fl5 b22 sb5 b22 sb6 b22 sb7 b22 fl8 b22 sb8 b22 sb9 b22 sb10 bl)
   (:text 110 58
          (335 nil "Del quinto ordine.")
          (1353 nil "Del seſto ordine."))
   (:music 2234
           (:section (:alt (:original-layout s19)
                           (:alternative-layout s35)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))
           cclef1 b22 fl0 b22 sb0 b22 sb1 b22 sb2 b22 fl3 b22 sb3 b22 sb4 b22 sb5 b22 fl6 b22 sb6 b22 fl7 b22 sb7 b22 sb8 b22 sb9 fl10 sb10 b22
           (:section (:alt (:original-layout s20)
                           (:alternative-layout s43)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))

           cclef1 sb0 b22 sb1 b22 sb2 b22 sb3 b22 sh4 b22 sb4 b22 sb5 b22 sb6 b22 sb7 b22 sb8 b22 sb9 b38 sb10 b38 bl)
   (:text 110 58
          (329 nil "Del quinto ordine.")
          (1352 nil "ᴅel seſto ordine."))
   (:music 2232
           (:section (:alt (:original-layout s26)
                           (:alternative-layout s36)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout x)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))
           cclef5 b22 sb0 b22 sh1 sb1 b22 sh2 sb2 b22 sb3 b22 sb4 sh5 sb5 b22 sb6 b22 sb7 b22 sh8 b22 sb8 b22 sh9 sb9 b22 sb10 b22
           (:section (:alt (:original-layout s27)
                           (:alternative-layout s44)
                           (:flag :layout) (:id 0)))
           cclef1 b22 sb0 b22 fl1 b22 sb1 b22 fl2 sb2 b22 sb3 b22 sb4 b22 fl5 sb5 b22 sb6 b22 sb7 b22 fl8 sb8 b22 fl9 sb9 sb10 bl)
   (:text 110 58
          (337 nil "Del quinto ordine.")
          (1350 nil "Del sesto ordine."))
   (:music 2228
           (:section (:alt (:original-layout s33)
                           (:alternative-layout s37)
                           (:flag :layout) (:id 0)))
           cclef7 b38 fl6 (:key-signature nil nil nil nil nil nil :flat)
           b22 sb0 b38 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b22 sb6 b22 sb7 b22 sb8 b22 sb9 b38 sb10 b38
           (:section (:alt (:original-layout s34)
                           (:alternative-layout s45)
                           (:flag :layout) (:id 0)))
           cclef7 b22 (:key-signature nil nil nil nil nil nil nil)
           sb0 b22 fl1 sb1 b22 fl2 sb2 b22 sb3 b22 sb4 b22 fl5 b22 sb5 b22 fl6 sb6 b22 sb7 b22 fl8 sb8 b22 fl9 sb9 b22 sb10 bl)
   (:text 110 58
          (334 nil "Del quinto ordine.")
          (1332 nil "ᴅel seſto ordine."))
   (:music 2214
           (:section (:alt (:original-layout s40)
                           (:alternative-layout s38)
                           (:flag :layout) (:id 0)))
           (:f-clef) max5 fclef5 b22 sb0 b22
           (:alt (:diplomatic sh2) (:idealised sh1)
                 (:comment "Original: ♯ steht eine Position höher.")
                 (:flag :draft) (:id 5))
           b22 sb1 b22 sb2 b22 sb3 b22 sb4 b22 sh5 b22 sb5 b22 sb6 b22 sb7 b22 sb8 b22 sh9 b22 sb9 sb10 b38
           (:section (:alt (:original-layout s41)
                           (:alternative-layout s46)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))
           (:f-clef) max5 fclef5 b22 fl18 (:key-signature nil nil nil nil nil nil :flat)
           b22 sb0 b22 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b22 sb6 b22 sb7 b22 sb8 b22 sb9 b22 sb10 bl)
   (:text 110 58
          (334 nil "Del quinto ordine.")
          (1337 nil "ᴅel seſto ordine."))
   (:music 2207
           (:section (:alt (:original-layout s47)
                           (:alternative-layout s39)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))

           (:f-clef) max7 fclef7 (:key-signature nil nil nil nil nil nil nil)
           b22 sb0 b22 sb1 b22 sb2 b22 fl3 b22 sb3 b22 sb4 b22 sb5 b22 fl6 sb6 b22 sb7 b22 sb8 b22 sb9 b22 fl10 sb10 b22
           (:section (:alt (:original-layout s48)
                           (:alternative-layout s47)
                           (:flag :layout) (:id 0)))
           (:f-clef) max7 fclef7 sb0 b22 fl1 sb1 fl2 sb2 b22 fl3 sb3 b22 sb4 b22 fl5 sb5 b22 fl6 sb6 b22 sb7 b22 fl8 sb8 fl9 sb9 b22 fl10 sb10 bl)
   (:text 110 58
          (330 nil "Del quinto ordine.")
          (1327 nil "ᴅel seſto ordine."))
   (:music 2207
           (:section (:alt (:original-layout s54)
                           (:alternative-layout s40)
                           (:flag :layout) (:id 0)))
           (:f-clef) max9 fclef9 b38 sb0 b22 sb1 b22 sh2 b22 sb2 b22 sb3 b22 sb4 b22 sb5 b22 sb6 b22 sb7 b38 sb8 b38 sh9 b22 sb9 b22 sb10 b22
           (:section (:alt (:original-layout s55)
                           (:alternative-layout s48)
                           (:flag :layout) (:id 0)))
           (:f-clef) max9 fclef9 b22 sb0 b22 fl1 sb1 b22 sb2 b22 sb3 b22 sb4 b22 fl5 b22 sb5 b22 sb6 b22 sb7 b22 fl8 b22 sb8 b22 sb9 sb10 bl)


   (:vspace 200)

   ;; Seite 4, fol. 136r, S. 271
   (:text 110 58
          (530 nil "Settimo ordine."))
   (:music 964
           (:section (:alt (:original-layout s7)
                           (:alternative-layout s49)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))
           (:f-clef) max7 fclef7 b22 sb0 b22 sb1 b22 sb2 b22 sb3 b22 sb4 b22 sb5 b22 sb6 b22 sb7 b22 sb8 b22 sb9 b22 sb10 bl)
   (:text 110 58
          (266 nil "Del settimo ordine."))
   (:music 977
           (:section (:alt (:original-layout s14)
                           (:alternative-layout s50)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))
           gclef3 b38 sb0 sb1 sh2 sb2 sh3 sb3 sb4 sb5 sh6 sb6 sb7 sb8 sh9 sb9 sh10 sb10 b22 bl)
   (:text 110 58
          (359 nil "Del settimo ordine."))
   (:music 1042
           (:section (:alt (:original-layout s21)
                           (:alternative-layout s51)
                           (:flag :layout) (:id 0)))
           cclef1 fl07 (:key-signature nil nil nil nil nil nil :flat)
           b38 b38 sb0 b22 sb1 b38 sb2 b38 sb3 b38 sb4 b38 sb5 b38 sb6 b38 sb7 b38 sb8 b22 sb9
           (:alt (:diplomatic b38) (:idealised sb10 bl)
                 (:comment "Original: Die letzte Note fehlt.")
                 (:flat :draft) (:id 6)))
   (:text 110 58
          (350 nil "Del settimo ordine."))
   (:music 1034
           (:section (:alt (:original-layout s28)
                           (:alternative-layout s52)
                           (:flag :layout) (:id 0)))
           cclef3 (:key-signature nil nil nil nil nil nil nil)
           b38 sb0 b22 sb1 b22 sb2 b22 sh3 b22 sb3 b38 sb4 b22 sb5 b22 sh6 sb6 sb7 sb8 sb9 sh10 sb10 b22 b22 (:alt (:idealised bl)))
   (:text 110 58
          (359 nil "Del settimo ordine."))
   (:music 1020
           (:section (:alt (:original-layout s35)
                           (:alternative-layout s53)
                           (:flag :layout) (:id 0)))
           (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))
           cclef5 fl07 b22 fl4 (:key-signature nil nil :flat nil nil nil :flat)
           sb0 b22 sb1 b22 sb2 b22 sb3 b22 sb4 b22 sb5 b22 sb6 b22 sb7 b22 sb8 b22 sb9 b22 sb10 b38 b38 (:alt (:idealised bl)))
   (:text 110 58
          (350 nil "Del settimo ordine."))
   (:music 1014
           (:section (:alt (:original-layout s42)
                           (:alternative-layout s54)
                           (:flag :layout) (:id 0)))
           cclef7 (:key-signature nil nil nil nil nil nil nil)
           b22 sb0 b22 sb1 b22 sb2 b22 sh3 sb3 b22 sb4 b22 sb5 b22 sb6 b22 sb7 b22 sb8 b22 sb9 b22 sh10 sb10 b38 (:alt (:idealised bl)))
   (:text 110 58
          (342 nil "Del settimo ordine."))
   (:music 1008
           (:section (:alt (:original-layout s49)
                           (:alternative-layout s55)
                           (:flag :layout) (:id 0)))
           (:f-clef) max5 fclef5 b22 sb0 sb1 sh2 sb2 sh3 sb3 sb4 sh5 sb5 sh6 sb6 sb7 sb8 sh9 sb9 sh10 sb10 b22 (:alt (:idealised bl)))
   (:text 110 58
          (349 nil "Del settimo ordine."))
   (:music 1041
           (:section (:alt (:original-layout s56)
                           (:alternative-layout s56)
                           (:flag :layout) (:id 0)))
                      (:alt (:original-layout)
                 (:alternative-layout (:newline))
                 (:flag :layout) (:id 0))
           (:f-clef) max9 fclef9 b22 sb0 sb1 sh2 sb2 sh3 sb3 sb4 sb5 sh6 sb6 sb7 b22 sh8 sb8 b22 sb9 b22 sh10 sb10 b38 (:alt (:idealised bl)))

   (:alt (:diplomatic
          (:vspace 110)
          (:music 1080
                  b125 b125 b125 b125 b125 b125 b125 b125 b125)
          (:text 70 58
            (98 900 "Qui finiſcono tutti glʼordini di tutte le"))
          (:text 70 58
            (0 1009 "chiaui ſcritte in tutte le righe di tutte le"))
          (:text 110 58
            (0 841 "parti della noſtra prattica ᴍuſicale."))
          (:music 1045
                  b125 b125 b125 b125 b125 b125 b125 b125 b22 b22 b38))
         (:idealised
          (:vspace 110)
          (:music 1080
                  b125 b125 b125 b125 b125 b125 b125 b125 b125)
          (:text 70 58
            (98 900 "Qui finiſcono tutti glʼordini di tutte le"))
          (:text 70 58
            (0 1009 "chiaui ſcritte in tutte le righe di tutte le"))
          (:text 110 58
            (0 841 "parti della noſtra prattica ᴍuſicale."))
          (:music 1045
                  b125 b125 b125 b125 b125 b125 b125 b125 b22 b22 b38))
         (:comment "Dieser Text (»Qui finiscono ...«) kann entweder im Notenbeispiel oder im Haupttext erscheinen. Ist zu diskutieren. Im Moment steht er in der diplomatischen und idealisierten Transkription, nicht aber in der normalisierten.")
         (:flag :observe) (:id 1))))
