`((:header
   (:filename "b5-c51-m1")
   (:alt-name "m5.054")
   (:comment "q021_s252, rotation: 0.82, origin: 685; q021_s251, rotation: 0, origin: 461")
   (:creator "Vicentino21 / Johannes Keller")
   (:section-headings
    (s1 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s2 (:alt (:it "Semitono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s3 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s4 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))

    (s5 (:alt (:it "Semitono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s6 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s7 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))

    (s8 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
              (:de "")
              (:en "")))
    (s9 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
              (:de "")
              (:en "")))
    (s10 (:alt (:it "Semitono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en "")))

    (s11 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en "")))
    (s12 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en "")))
    (s13 (:alt (:it "Semitono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en "")))
    (s14 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en ""))))
   (:section-captions
    (s1 (:alt (:it "Semitono maggiore:\\diesis maggiore – diesis minore\\Semitono minore:\\diesis minore – diesis minore")
              (:de "")
              (:en "")
              (:comment "Original: Die erste _diesis_ soll »dieses maggiore« sein.")
              (:flag :draft) (:id 1)))
    (s2 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis minore – diesis minore – diesis minore")
              (:de "")
              (:en "")))
    (s3 (:alt (:it "Semitono maggiore:\\diesis maggiore – diesis minore\\Semitono minore:\\diesis minore – diesis minore")
              (:de "")
              (:en "")))
    (s4 (:alt (:it "Semitono maggiore:\\diesis maggiore – diesis minore\\Semitono minore:\\diesis minore – diesis minore")
              (:de "")
              (:en "")))

    (s5 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis minore – diesis minore – diesis minore")
              (:de "")
              (:en "")))
    (s6 (:alt (:it "Semitono maggiore:\\diesis maggiore – diesis minore\\Semitono minore:\\diesis minore – diesis minore")
              (:de "")
              (:en "")))
    (s7 (:alt (:it "Semitono maggiore:\\diesis maggiore – diesis minore\\Semitono minore:\\diesis minore – diesis minore")
              (:de "")
              (:en "")))

    (s8 (:alt (:it "Semitono maggiore:\\diesis minore – diesis maggiore\\Semitono minore:\\diesis minore – diesis minore")
              (:de "")
              (:en "")))
    (s9 (:alt (:it "Semitono maggiore:\\diesis minore – diesis maggiore\\Semitono minore:\\diesis minore – diesis minore")
              (:de "")
              (:en "")))
    (s10 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis minore – diesis minore – diesis minore")
               (:de "")
               (:en "")))

    (s11 (:alt (:it "Semitono maggiore:\\diesis minore – diesis maggiore\\Semitono minore:\\diesis minore – diesis minore")
               (:de "")
               (:en "")))
    (s12 (:alt (:it "Semitono maggiore:\\diesis minore – diesis maggiore\\Semitono minore:\\diesis minore – diesis minore")
               (:de "")
               (:en "")))
    (s13 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis minore – diesis minore – diesis minore")
               (:de "")
               (:en "")))
    (s14 (:alt (:it "Semitono maggiore:\\diesis minore – diesis maggiore\\Semitono minore:\\diesis minore – diesis minore")
               (:de "")
               (:en "")))))
  (:data
   (:text 90 58
     (172 nil "se.ma.")
     (415 nil "se.mi.")
     (711 nil "se.mi.")
     (899 nil "et ma.")
     (1213 nil "se.ma.")
     (1424 nil "se.mi")
     (1718 nil "se ma.")
     (1950 nil "se. mi."))
   (:music 2234
           (:voice v1)
           (:section s1) (:f-clef) max7 fclef7 b38 sbd2 b22 fl3 b22 sb3 b22 fl3 b22 sbd3 b22 sb3 b22 sbd3 b22 bl
           (:section s2) b22 sbd3 b22 sh3 b22 sb3 b22
           (:alt (:diplomatic sb3) (:critical sb4)
                 (:comment "Original: Die dritte Note ist ein B♮.")
                 (:flag :draft) (:id 2))
           b22 sbd4 b22 bl
           (:section s3) b22 sbd4 b22 fl5 b22 sb5 b22 fl5 b22 sbd5 b22 sb5 b22 sbd5 b22 bl
           (:section s4) (:newline) sbd5 b22 fl6 b38 sb6 b22 fl6 b22 sbd6 b22 sb6 b22 sbd6 bl)
   (:text 70 58
     (85 nil "da.mi.d.mi.d.mi.d. mi.")
     (685 nil "di.mi.d.mi.d.mi.")
     (1114 nil "di.ma.d.mi.d.mi.d.mi.")
     (1662 nil "di.ma.d.mi.di.mi.di.mi."))
   (:text 110 58
     (87 nil "tono ᴄrom. accid")
     (707 nil "sem.ᴄrom.acc.")
     (1148 nil "tono ᴄro. accid.")
     (1682 nil "tono ᴄro. accid."))
   (:text 110 58
     (168 nil "se. mi. & ma.")
     (775 nil "se. ma.")
     (1102 nil "se. mi.")
     (1549 nil "se.ma.")
     (1902 nil "se.mi."))
   (:music 2225
           (:section s5) (:f-clef) max7 fclef7 b38 b22 sbd6 b22 b38 sh6 b22 b22 sb6 b38 sb7 b38 sbd7 bl
           (:section s6) sbd7 b22 b38 fl8 b38 b22 sb8 b38 b22 fl8 b38 b22 sbd8 b22 b38 sb8 b22 b38 sbd8 b38 bl
           (:section s7) (:newline) b38 sbd8 b38 b22 fl9 b22 b38 sb9 b38 fl9 b22 sbd9 b38 sb9 b38 sbd9 b22 b22 bl)
   (:text 90 58
     (:alt (:diplomatic (59 nil "di.mi.dimi. di.mi.di.mi."))
           (:critical (59 nil "di.mi.dimi. di.mi."))
           (:comment "Original: »di.mi.dimi. di.mi.di.mi.«")
           (:flag :draft) (:id 3))
     (661 nil "di. ma. di. mi. d.imi. di. mi.")
     (1504 nil "di. ma. di. mi. di.mi. d.mi."))
   (:text 110 58
     (98 nil "se. ᴄro. accid.")
     (778 nil "tono ᴄro. accid.")
     (1569 nil "tono Cro. accid."))
   (:text 110 58
     (170 nil "se. mag.")
     (452 nil "se.mi.")
     (932 nil "se.mag.")
     (1218 nil "se. mi.")
     (1711 nil "se. mi. et ma."))
   (:music 2223
           (:section s8) (:f-clef) max7 fclef7 b38 sbd9 b38 sb9 b38 fl9 b38 sb9 b38 sh8 b38 sb8 b38 sbd8 b38 b22 bl
           (:section s9) b38 sbd8 b22 b38 sb8 b22 b38 fl8 b38 b22 sb8 b22 b38 sh7 b38 b22 sb7 b38 sbd7 b38 bl
           (:section s10) (:newline) b38 sbd7 b22 b38 sb7 b22 b38 sh6 b38 sb6 b38 sbd6 b38 bl)
   (:text 100 58
     (91 nil "di.mi.di.ma.di.mi.di.mi.")
     (895 nil "di.mi. di.ma. di.mi. di.mi.")
     (1700 nil "di.mi. di.mi. di.mi."))
   (:text 120 58
     (171 nil "tono ᴄro. accid.")
     (960 nil "tono ᴄro. accid.")
     (1712 nil "sem. ᴄro. acc."))
   (:text 100 58
     (129 nil "se.mag.")
     (422 nil "se. mi.")
     (708 nil "se.mag.")
     (986 nil "se. mi.")
     (1274 nil "se.mi. et ma.")
     (1676 nil "se.")
     (1784 nil "mag.")
     (1949 nil "se.")
     (2056 nil "mi."))
   (:music 2215
           (:section s11) (:f-clef) max7 fclef7 b38 sbd6 b22 sb6 b22 fl6 sb6 sh5 sb5 b22 sbd5 b22 bl
           (:section s12) b22 sbd5 b22 sb5 b22 fl5 sb5 b22 sh4 b22 sb4 b22 sbd4 b38 bl
           (:section s13) (:newline) b38 sbd4 b22 sb4 b22 sh3 sb3 b22 sbd3 b22 bl
           (:section s14) b22 sbd3 b22 sb3 b22 fl3 sb3 b22 sh2 b22 sb2 b22 sbd2 b22 bl)
   (:text 90 58
     (34 nil "di.mi.di.ma.di.mi.di.mi.")
     (607 nil "di.mi.di.ma.d.imi.di.mi.")
     (1201 nil "di.mi. di.mi.di.mi.")
     (1646 nil
           (:alt (:diplomatic "d.mi.d.ma.d.mi.d.mi,")
                 (:critical "d.mi.d.ma.d.mi.d.mi.")
                 (:comment "Original: »d.mi.d.ma.d.mi.d.mi,«")
                 (:flag :draft) (:id 4))))
   (:text 70 58
     (118 nil "ᴛono")
     (284 nil "ᴄro.")
     (418 nil "acc.")
     (722 nil "tono")
     (865 nil "cro.")
     (997 nil "acc.")
     (1252 nil "se.")
     (1357 nil "cro.")
     (1491 nil "acc.")
     (1706 nil "tono")
     (1857 nil "cro.")
     (1990 nil "acc."))))
