`((:header
   (:filename "b5-c43-m1")
   (:alt-name "m5.042")
   (:comment "q021_s242, origin: 1061")
   (:creator "Vicentino21 / Johannes Keller")
   (:section-captions
    (s1 (:alt (:it "Semitono\\naturale")
              (:de "")
              (:en "")))
    (s2 (:alt (:it "Tono\\naturale")
              (:de "")
              (:en "")))
    (s3 (:alt (:it "Tono\\naturale")
              (:de "")
              (:en "")))
    (s4 (:alt (:it "Tono\\naturale")
              (:de "")
              (:en "")))
    (s5 (:alt (:it "Semitono\\naturale")
              (:de "")
              (:en "")))
    (s6 (:alt (:it "Tono\\naturale")
              (:de "")
              (:en "")))
    (s7 (:alt (:it "Tono\\naturale")
              (:de "")
              (:en "")))
    (s8 (:alt (:it "Tono\\naturale")
              (:de "")
              (:en "")))
    (s9 (:alt (:it "Tono\\naturale")
              (:de "")
              (:en "")))
    (s10 (:alt (:it "Semitono\\naturale")
               (:de "")
               (:en "")))
    (s11 (:alt (:it "Tono\\naturale")
               (:de "")
               (:en "")))
    (s12 (:alt (:it "Tono\\naturale")
               (:de "")
               (:en "")))
    (s13 (:alt (:it "Tono\\naturale")
               (:de "")
               (:en "")))
    (s14 (:alt (:it "Semitono\\naturale")
               (:en "")
               (:de "")))))
  (:data
   (:text 90 58
     (171 nil "se.")
     (355 nil "to.")
     (500 nil "to.")
     (687 nil "to.")
     (837 nil "se.")
     (991 nil "to.")
     (1128 nil "to.")
     (1241 nil "to.")
     (1393 nil "to.")
     (1544 nil "se.")
     (1691 nil "to.")
     (1844 nil "to.")
     (1966 nil (:alt (:diplomatic "se.")
                     (:critical "to.")
                     (:coord-barre "TZ1 TE13")
                     (:coord-norm "G13 US")
                     (:comment "Original: »se.«")
                     (:flag :ready) (:id 1)))
     (2118 nil (:alt (:diplomatic "to.")
                     (:critical "se.")
                     (:coord-barre "TZ1 TE14")
                     (:coord-norm "G14 US")
                     (:comment "Original: »to.«")
                     (:flag :ready) (:id 2))))
   (:music 2231
           (:voice v1)
           (:section s1) (:f-clef) max7 fclef7 b22 fl3 (:key-signature nil nil nil nil nil nil :flat) b22 sb2 sb3 bl
           (:section s2) sb3 b22 sb4 bl
           (:section s3) sb4 b22 sb5 bl
           (:section s4) sb5 b22 sb6 bl
           (:section s5) sb6 b22 sb7 bl
           (:section s6) sb7 sb8 bl
           (:section s7) sb8 sb9 bl
           (:section s8) (:newline) sb9 sb8 bl
           (:section s9) sb8 sb7 bl
           (:section s10) sb7 sb6 bl
           (:section s11) sb6 sb5 bl
           (:section s12) sb5 sb4 bl
           (:section s13) sb4 sb3 bl
           (:section s14) sb3 sb2 bl)
   (:vspace 20)
   (:text 70 58
     (168 nil "nat.")
     (346 nil "nat.")
     (507 nil "nat.")
     (682 nil "nat.")
     (846 nil "nat.")
     (975 nil "nat.")
     (1123 nil "nat.")
     (1254 nil "nat.")
     (1395 nil "nat.")
     (1521 nil "nat.")
     (1678 nil "nat.")
     (1820 nil "nat.")
     (1961 nil "nat.")
     (2091 nil "nat."))))
