`((:header
   (:filename "b5-c51-m2")
   (:alt-name "m5.055")
   (:comment "q021_s253, rotation: 0.69, origin: 446")
   (:creator "Vicentino21 / Johannes Keller")
   (:section-headings
    (s1 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s2 (:alt (:it "Semitono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s3 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s4 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))

    (s5 (:alt (:it "Semitono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s6 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s7 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))

    (s8 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
              (:de "")
              (:en "")))
    (s9 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
              (:de "")
              (:en "")))
    (s10 (:alt (:it "Semitono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en "")))
    (s11 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en "")))

    (s12 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en "")))
    (s13 (:alt (:it "Semitono cromatico \\accidentale\\[discendente]")
               (:de "")
               (:en "")))
    (s14 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en ""))))
   (:section-captions
    (s1 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
              (:de "")
              (:en "")))
    (s2 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis minore – diesis minore – diesis minore")
              (:de "")
              (:en "")))
    (s3 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\[diesis minore –] diesis maggiore")
              (:de "")
              (:en "")))
    (s4 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
              (:de "")
              (:en "")))

    (s5 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis minore – diesis minore – diesis minore")
              (:de "")
              (:en "")))
    (s6 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
              (:de "")
              (:en "")))
    (s7 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
              (:de "")
              (:en "")))

    (s8 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis maggiore – diesis minore")
              (:de "")
              (:en "")))
    (s9 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis maggiore – diesis minore")
              (:de "")
              (:en "")))
    (s10 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis minore – diesis minore – diesis minore")
               (:de "")
               (:en "")))
    (s11 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis maggiore – diesis minore")
               (:de "")
               (:en "")))

    (s12 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis maggiore – diesis minore")
               (:de "")
               (:en "")))
    (s13 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis minore – diesis minore – diesis minore")
               (:de "")
               (:en "")))
    (s14 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis maggiore – diesis minore")
               (:de "")
               (:en "")))))
  (:data
   (:text 90 58
     (181 nil "se.mi")
     (381 nil "se.")
     (502 nil "ma.")
     (692 nil "se.mi.")
     (883 nil "& ma.")
     (1236 nil "se.mi.")
     (1427 nil "se. ma.")
     (1692 nil "sem. min.")
     (1952 nil "se.mag."))
   (:music 2231
           (:voice v1)
           (:section s1) (:f-clef) max7 fclef7 b38 sbd2 sh2 sb2 fl3 sb3 b22 fl3 sbd3 sbd3 b22 bl
           (:section s2) b38 sbd3 b22 b22 sh3 b38 sb3 b22 b22 sb4 b22 b22 sbd4 b38 bl
           (:section s3) b38 sbd4 sh4 sb4 fl5 sb5 fl5 sbd5 sbd5 b38 bl
           (:section s4) (:newline) b38 sbd5 sh5 sb5 b22 fl6 sb6 fl6 sbd6 sbd6 b38 bl)
   (:text 70 58
     (55 nil "d.mi.d.mi.d.mi.d.ma.")
     (:alt (:diplomatic (593 nil "di.mi.di.mi.di.mi.di.mi."))
           (:critical (593 nil "di.mi.di.mi.di.mi."))
           (:comment "Original: »di.mi.di.mi.di.mi.di.mi.«")
           (:flag :draft) (:id 1))
     (1166 nil "d.mi.d.mi.d.mi.d.mi.")
     (1675 nil "d.mi.d.mi.di.mi.d.ma."))
   (:text 110 58
     (94 nil "tono")
     (259 nil "ᴄro.")
     (417 nil "acc.")
     (648 nil "sem.")
     (814 nil "ᴄro.")
     (980 nil "acc.")
     (1246 nil "tono")
     (1382 nil "cro.")
     (1516 nil "acc.")
     (1691 nil "tono")
     (1844 nil "ᴄro.")
     (2003 nil "accid."))
   (:text 110 58
     (169 nil "se.mi.")
     (357 nil "& mag.")
     (907 nil "se.mi.")
     (1098 nil "se. mag.")
     (1612 nil "se.")
     (1730 nil "mi.")
     (1885 nil "se.")
     (2007 nil "mag."))
   (:music 2250
           (:section s5) (:f-clef) max7 fclef7 b38 b22 sbd6 b38 b22 sh6 b22 sb6 b38 b22 sb7 b38 sbd7 b38 b22 bl
           (:section s6) b38 sbd7 b38 sh7 b22 sb7 b38 fl8 b22 sb8 b38 fl8 b22 sbd8 b38 sbd8 b38 bl
           (:section s7) (:newline) b38 sbd8 b38 sh8 b38 sb8 b38 fl9 b22 sb9 b22 fl9 b22 sbd9 b38 sbd9 b22 b22 bl)
   (:text 90 58
     (:alt (:diplomatic (100 nil "di.mi.di.mi.di.mi.di.mi."))
           (:critical (100 nil "di.mi.di.mi.di.mi."))
           (:comment "Original: »di.mi.di.mi.di.mi.di.mi.«")
           (:flag :draft) (:id 2))
     (791 nil "di.mi. di.mi. di.mi. di.ma.")
     (1566 nil "di.mi. di.mi. di.mi. di.ma."))
   (:text 110 58
     (175 nil "se.")
     (291 nil "ᴄro.")
     (441 nil "accid.")
     (827 nil "tono")
     (968 nil "ᴄro.")
     (1112 nil "accid.")
     (1605 nil "tono")
     (1770 nil "Cro.")
     (1945 nil "accid."))
   (:text 110 58
     (128 nil "se.")
     (239 nil "mi.")
     (403 nil "se.")
     (507 nil "mag.")
     (671 nil "se.")
     (776 nil "mi.")
     (935 nil "se.")
     (1087 nil "ma.")
     (1260 nil "se.")
     (1367 nil "mi. & ma.")
     (1689 nil "se.")
     (1798 nil "mi.")
     (1966 nil "se.")
     (2075 nil "ma."))
   (:music 2224
           (:section s8) (:f-clef) max7 fclef7 b22 sbd9 b22 sb9 fl9 sbd9 sh8 b22 sb8 b22 sbd8 b22 bl
           (:section s9) b22 sbd8 b22 sb8 b22 fl8 sbd8 b22 sh7 sb7 b22 sbd7 b22 bl
           (:section s10) (:newline) b22 sbd7 b22 sb7 b22 sh6 b22 sb6 b22 b22 sbd6 b22 b22 bl
           (:section s11) b22 sbd6 b22 sb6 fl6 sbd6 b22 sh5 b22 sb5 b22 sbd5 b22 bl)
   (:text 100 58
     (0 nil "d.mi.d.mi.d.ma.d. mi.")
     (559 nil "di.mi.d.mi.di.ma.d.mi.")
     (:alt (:diplomatic (1112 nil "d.mi.d.mi. d.mi.di.mi."))
           (:critical (1112 nil "d.mi.d.mi. d.mi."))
           (:comment "Original: »d.mi.d.mi. d.mi.di.mi.«")
           (:flag :draft) (:id 3))
     (:alt (:diplomatic (1653 nil "d.mi.di.mi.di.d.ma.d.mi."))
           (:critical (1653 nil "d.mi.di.mi.d.ma.d.mi."))
           (:comment "Original: »d.mi.di.mi.di.d.ma.d.mi.«")
           (:flag :draft) (:id 4)))
   (:text 120 58
     (91 nil "tono")
     (252 nil "ᴄro.")
     (412 nil "accid.")
     (:alt (:diplomatic (641 nil "sem."))
           (:critical (641 nil "tono"))
           (:comment "Original: »sem.«")
           (:flag :draft) (:id 5))
     (809 nil "ᴄro.")
     (964 nil "acc.")
     (1125 nil "se.")
     (1337 nil "ᴄro.")
     (1480 nil "acc.")
     (1696 nil "tono")
     (1852 nil "ᴄro.")
     (2012 nil "accid"))
   (:text 100 58
     (262 nil "se. min.")
     (530 nil "se ma.")
     (889 nil "sem.")
     (1039 nil "min.")
     (1189 nil "se.")
     (1309 nil "ma.")
     (1537 nil "se.")
     (1639 nil "min.")
     (1830 nil "se.")
     (1941 nil "mag."))
   (:music 2227
           (:section s12) (:f-clef) max7 fclef7 b38 b22 sbd5 b38 sb5 b38 fl5 b38 sbd5 b38 sh4 b38 sb4 b38 b22 sbd4 b38 b22 bl
           (:section s13) (:newline) b38 b22 sbd4 b38 sb4 b38 sh3 b38 sb3 b38 sbd3 b38 b38 bl
           (:section s14) b38 b38 sbd3 b38 sb3 b38 fl3 b38 sbd3 b38 sh2 b38 sb2 b38 sbd2 b38 b38 bl)
   (:text 90 58
     (175 nil "d.mi. d.mi. d.mag. d.mi.")
     ;; Von Bibelgruppe bestätigt
     (:alt (:diplomatic (937 nil "d.mi. d.mi.d.mi.d.mi."))
           (:critical (937 nil "d.mi. d.mi.d.mi."))
           (:comment "Original: »d.mi. d.mi.d.mi.d.mi.«")
           (:flag :draft) (:id 6))
     (1521 nil "d.mi. d.mi. d.ma. d.mi."))
   (:text 70 58
     (252 nil "tono")
     (411 nil "ᴄro.")
     (575 nil "accid.")
     (874 nil "se.")
     (983 nil "mi. & mag.")
     (1550 nil "tono")
     (1713 nil "ᴄro.")
     (1865 nil "accid."))))
