`((:header
   (:filename "b5-c50-m2")
   (:alt-name "m5.053")
   (:comment "q021_s251, rotation: 0, origin: 555; q021_s252, rotation: 0.82, origin: 939")
   (:creator "Vicentino21 / Johannes Keller")
   (:section-headings
    (s1 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s2 (:alt (:it "Semitono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s3 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s4 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))

    (s5 (:alt (:it "Semitono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s6 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s7 (:alt (:it "Tono cromatico\\accidentale\\[ascendente]")
              (:de "")
              (:en "")))
    (s8 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
              (:de "")
              (:en "")))

    (s9 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
              (:de "")
              (:en "")))
    (s10 (:alt (:it "Semitono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en "")))
    (s11 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en "")))
    (s12 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en "")))

    (s13 (:alt (:it "Semitono cromatico \\accidentale\\[discendente]")
               (:de "")
               (:en "")))
    (s14 (:alt (:it "Tono cromatico\\accidentale\\[discendente]")
               (:de "")
               (:en ""))))
   (:section-captions
    (s1 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
              (:de "")
              (:en "")))
    (s2 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis maggiore – diesis minore – diesis minore")
              (:de "")
              (:en "")))
    (s3 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\[diesis minore –] diesis maggiore")
              (:de "")
              (:en "")))
    (s4 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
              (:de "")
              (:en "")))

    (s5 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis minore – diesis minore – diesis minore")
              (:de "")
              (:en "")))
    (s6 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis maggiore – diesis minore")
              (:de "")
              (:en "")
              (:comment "Original: »Semitono maggiore: diesis maggiore – diesis minore\\Semitono minore:\\diesis minore – diesis minore«")
              (:flag :draft) (:id 7)))
    (s7 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis maggiore – diesis minore")
              (:de "")
              (:en "")
              (:comment "Original: »Semitono maggiore:\\diesis minore – diesis maggiore\\Semitono minore:\\diesis minore – diesis minore«")
              (:flag :draft) (:id 8)))
    (s8 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis maggiore – diesis minore")
              (:de "")
              (:en "")))

    (s9 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis minore – diesis maggiore")
              (:de "")
              (:en "")))
    (s10 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis minore – diesis minore – diesis minore")
               (:de "")
               (:en "")))
    (s11 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis maggiore – diesis minore")
               (:de "")
               (:en "")))

    (s12 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis maggiore – diesis minore")
               (:de "")
               (:en "")))
    (s13 (:alt (:it "Semitono minore /\\semitono maggiore:\\diesis minore – diesis minore – diesis minore")
               (:de "")
               (:en "")))
    (s14 (:alt (:it "Semitono minore:\\diesis minore – diesis minore\\Semitono maggiore:\\diesis maggiore – diesis minore")
               (:de "")
               (:en "")))))
  (:data
   (:text 90 58
     (168 nil "se.mi")
     (375 nil "se.ma.")
     (784 nil "se.mi. et ma.")
     (1165 nil "se.mi.")
     (1372 nil "se.ma.")
     (1695 nil "se. mi.")
     (1940 nil "se. ma."))
   (:music 2218
           (:voice v1)
           (:section s1) (:f-clef) max7 fclef7 b38 fl2 b22 sb2 b22 fl2 b22 sbd2 b22 sb2 b22 sbd2 b22 fl3 b22 sb3 bl
           (:section s2) fl3 b22 sb3 b22 fl3 b22 sbd3 b22 sb3 b22 sbd3 bl
           (:section s3) sbd3 b22 sh3 b22 sb3 sb4 b22 sbd4 fl5 b22 sb5 bl
           (:section s4) (:newline) fl5 b22 sb5 b22 fl5 b22 sbd5 b22 sb5 b22 sbd5 b22 fl6 b38 sb6 bl)
   (:text 70 58
     (102 nil "di.mi.d.mi.d.mi.d.ma.")
     (707 nil "di.mi.d.mi.di.mi.")
     (1163 nil "di.mi.d.mi.d.ma.")
     (1620 nil "di.mi.d.mi.di.mi. di.ma."))
   (:text 110 58
     (95 nil "tono ᴄrom. accid.")
     (732 nil "sem.ᴄrom.acc.")
     (1165 nil "tono ᴄro. accid.")
     (1691 nil "tono ᴄro. accid."))
   (:text 110 58
     (100 nil "se. mi. & ma.")
     (611 nil "se.ma.")
     (847 nil "se.mi.")
     (1159 nil "se.ma.")
     (1416 nil "se.mi.")
     (1784 nil "se. mi.")
     (1975 nil "se. ma."))
   (:music 2223
           (:section s5) (:f-clef) max7 fclef7 b22 fl6 b22 sb6 b22 fl6 sbd6 b22 sb6 b22 sbd6 bl
           (:section s6) sbd6 b22
           (:alt (:diplomatic sb7)
                 (:critical sh6 sb6)
                 (:comment "Original: Die zweite Note ist ein F.")
                 (:flag :draft) (:id 1))
           b22
           (:alt (:diplomatic sbd7)
                 (:critical sb7)
                 (:comment "Original: Die dritte Note ist ein Ḟ.")
                 (:flag :draft) (:id 2))
           b22
           (:alt (:diplomatic sh7 b22 sb7)
                 (:critical b38 b22 sbd7)
                 (:comment "Original: Die vierte Note ist ein F♯.")
                 (:flag :draft) (:id 3))
           b22 fl8 sb8 bl
           (:section s7) (:newline) fl8 b22 sb8 b22 fl8 b22 sbd8 b22
           (:alt (:diplomatic sbd8)
                 (:critical sb8)
                 (:comment "Original: Die dritte Note ist ein Ġ.")
                 (:flag :draft) (:id 4))
           b22
           (:alt (:diplomatic sh8 b22 sb8)
                 (:critical b38 b22 sbd8)
                 (:comment "Original: Die vierte Note ist ein G♯.")
                 (:flag :draft) (:id 5))
           b22 fl9 b22 sb9 bl
           (:section s8) b22
           (:alt (:diplomatic fl8) (:critical fl9)
                 (:comment "Original: Das erste ♭ steht eine Position tiefer.")
                 (:flag :draft) (:id 6))
           sb9 sh8 sb8 sbd8 fl8 sbd8 fl8 sb8 bl)
   (:text 90 58
     (63 nil "di. mi. di mi. di. mi.")
     (552 nil "di. ma.di.mi.d.mi.d.mi.")
     (1118 nil "di. mi. d.ma.di. mi.di.mi.")
     (1724 nil "d.mi.d.mi.d.ma.d.mi."))
   (:text 110 58
     (100 nil "se. ᴄro. accid.")
     (636 nil "tono Cro. accid.")
     (1177 nil "tono Cro. accid.")
     (1766 nil "tono ᴄro. accid."))
   (:text 110 58
     (102 nil "se. mi.")
     (313 nil "se. mag.")
     (609 nil "se.mi. et ma.")
     (1084 nil "se. mi.")
     (1324 nil "se. mag.")
     (1688 nil "se.mi.")
     (1927 nil "se. ma."))
   (:music 2212
           (:section s9) (:f-clef) max7 fclef7 b38 fl8 sb8 b22 sh7 sb7 sbd7 sb7 sbd6 bl
           (:section s10) (:newline) sbd6 b22 sb6 b22 fl6 b22 sbd6 b22 fl6 b22 sb6 bl
           (:section s11) fl6 b22 sb6 sh5 b22 sb5 sbd5 b22 fl5 b22 sbd5 b22 fl5 b22 sb5 bl
           (:section s12) fl5 b22 sb5 sh4 b22 sb4 b22 sbd4 sh3 b22 sb3 b22 sbd3 b22 bl)
   (:text 100 58
     (54 nil "d.mi.d.mi.d.mi.d.ma.")
     (570 nil (:alt (:diplomatic "d.mi.d.mi.d.mi.d.mi.")
                    (:critical "d.mi.d.mi.d.mi.")
                    (:comment "Original: »d.mi.d.mi.d.mi.d.mi.«.")))
     (1050 nil "di.mi.di.mi.di.ma.d.mi.")
     (1659 nil "di.mi.d.mi.di.ma.d.mi."))
   (:text 120 58
     (84 nil "tono ᴄro. acc.")
     (646 nil "se.ᴄro. acc.")
     (1096 nil "tono ᴄro. accid.")
     (1709 nil "tono ᴄrom. accid."))
   (:text 100 58
     (135 nil "se. min.")
     (374 nil "& mag.")
     (749 nil "sem. min. se.mag."))
   (:music 1216
           (:section s13) (:newline) (:f-clef) max7 fclef7 b22 sbd3 b22 sb3 b22 fl3 b22 sbd3 b22 fl3 b22 sb3 b22 bl
           (:section s14) fl3 b22 sb3 b22 sh2 b22 sb2 b22 sbd2 b22 fl2 b22 sbd2 b22 fl2 b22 sb2 bl)
   (:text 90 58
     (50 nil (:alt (:diplomatic "d.mi.d.mi.d.mi.d.mi.")
                   (:critical "d.mi.d.mi.d.mi.")
                   (:comment "Original: »d.mi.d.mi.d.mi.d.mi.«.")))
     (596 nil "di.mi. di.mi. di.ma. di.mi."))
   (:text 70 58
     (93 nil "sem. ᴄro. acc.")
     (685 nil "tono ᴄro. acc."))))
