(in-package :setzkasten)

(defparameter *score-margins* '(10 10 10 10))
(defparameter *score-bg-color* "white")
(defparameter *font-height* 58)

;; central processing function, one specific reading with one specific backend
(defun process-score (filename suffix extraction-arguments backend-instance)
  (with-open-file (encoding-stream (merge-pathnames *encoding-source*
                                                    (pathname (format nil "~a.lisp" filename)))
                                   :direction :input)
    (let ((score (eval (read encoding-stream))))
      (multiple-value-bind (simplified-score apparatus-string)
          (extract-apparatus score extraction-arguments)
        (with-open-file (apparatus-stream (merge-pathnames *apparatus-export-path*
                                                           (pathname (format nil "app-~a-~a.txt"
                                                                             filename suffix)))
                                          :direction :output
                                          :if-exists :supersede
                                          :if-does-not-exist :create)
          (format apparatus-stream "Auto-generated critical apparatus for file ~a-~a:~%~%~a"
                  filename suffix apparatus-string))
        (create-score-file backend-instance simplified-score suffix)))))

;; looping over mission, entry point to everything
(defun execute-mission (mission-list)
  (reset-file-list *vicentino-types-backend*)
  (dolist (item mission-list)
    (process-score (first item) (second item) (third item) (fourth item))))




;; Type print imitation backend

(defparameter *glyph-height* 230)

(defparameter *vicentino-types-backend* (make-instance 'type-imitation-backend))

(progn
  (read-configuration
   *vicentino-types-backend*
   "~/common-lisp/setzkasten/backend-configuration/vicentino-types-components.lisp"
   :components)
  (read-configuration
   *vicentino-types-backend*
   "~/common-lisp/setzkasten/backend-configuration/vicentino-types-glyphs.lisp"
   :glyphs)
  (read-configuration
   *vicentino-types-backend*
   "~/common-lisp/setzkasten/backend-configuration/vicentino-types-syntax.lisp"
   :syntax))

(defparameter *lilypond-backend-modern* (make-instance 'lilypond-backend
                                                       :clef-type :modern))
(defparameter *lilypond-backend-modern-meter* (make-instance 'lilypond-backend
                                                             :clef-type :modern
                                                             ;;:rest-type :mensural
                                                             :timep t))
;;(defparameter *lilypond-backend-original* (make-instance 'lilypond-backend :clef-type :original))
(defparameter *lilypond-backend-original* (make-instance 'lilypond-backend
                                                         :clef-type :mensural
                                                         :rest-type :mensural
                                                         :notehead-type :petrucci))

;; experimental: macro to create missions
;; (defun flatten-1 (tree)
;;   (cond ((null tree) nil)
;;         ((listp (first (first tree))) (append (flatten-1 (first tree))
;;                                             (flatten-1 (rest tree))))
;;         (t (cons (first tree) (rest tree)))))

;; (defmacro create-mission (mission-name file-list)
;;   `(defparameter ,mission-name
;;      (list ,@(flatten-1
;;                (mapcar
;;                 (lambda (score-name)
;;                   (list '(,score-name "a" '(:diplomatic) *vicentino-types-backend*)
;;                         '(,score-name "b" '(:idealised) *vicentino-types-backend*)
;;                         '(,score-name "c-modern" '(:idealised :it) *lilypond-backend-modern*)
;;                         '(,score-name "c-original" '(:idealised :it) *lilypond-backend-original*)
;;                         '(,score-name "d-modern" '(:idealised :de) *lilypond-backend-modern*)
;;                         '(,score-name "d-original" '(:idealised :de) *lilypond-backend-original*)
;;                         '(,score-name "e-modern" '(:idealised :en) *lilypond-backend-modern*)
;;                         '(,score-name "e-original" '(:idealised :en) *lilypond-backend-original*)))
;;                 file-list)))))

;; (create-mission *test-mission*
;;                 ("b2-c2-m1"
;;                  "b1-c5-m1"))

(defun execute-all ()
  (dolist (mission  (list
                     *book1-types*
                     *book2-types*
                     *book3-types*
                     *book5-types*
                     *book1-modern*
                     *book2-modern*
                     *book3-modern*
                     *book5-modern*
                     ;;*book1-original*
                     ;;*book2-original*
                     ;;*book3-original*
                     ;;*book5-original*
                     *special*
                     ))
    (execute-mission mission)))

(defparameter *debug*
  `(
    ))


(defparameter *working*
  `(
    ;; ("b3-c15-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c15-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c15-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c15-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c15-m3" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c15-m3" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c15-m4" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c15-m4" "c" (:idealised :it) ,*lilypond-backend-modern*)

    ;; ("b3-c16-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c16-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c16-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c16-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c16-m3" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c16-m3" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c16-m4" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c16-m4" "c" (:idealised :it) ,*lilypond-backend-modern*)

    ;; ("b3-c17-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c17-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c17-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c17-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c17-m3" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c17-m3" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c17-m4" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c17-m4" "c" (:idealised :it) ,*lilypond-backend-modern*)

    ("b3-c18-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c18-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c18-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c18-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c18-m3" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c18-m3" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c18-m4" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c18-m4" "c" (:idealised :it) ,*lilypond-backend-modern*)

    ;; ("b3-c5-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c6-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c7-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c8-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c9-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c10-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c11-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c12-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c39-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c39-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c40-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c40-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c41-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c41-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c42-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c42-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c49-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c49-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c49-m3" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c49-m4" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c49-m5" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c49-m6" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c49-m7" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c49-m8" "b" (:idealised) ,*vicentino-types-backend*)

    ;; ("b3-c5-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c6-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c7-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c8-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c9-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c10-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c11-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c12-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c39-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c39-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c40-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c40-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c41-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c41-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c42-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c42-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c49-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c49-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c49-m3" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c49-m4" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c49-m5" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c49-m6" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c49-m7" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ;; ("b3-c49-m8" "c" (:idealised :it) ,*lilypond-backend-modern*)

    ;; ("b3-c53-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ;; ("b3-c53-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ;; ("b3-c53-m1" "c" (:idealised :it) ,*lilypond-backend-modern-meter*)
    ;; ("b3-c53-m1" "d" (:idealised :de) ,*lilypond-backend-modern-meter*)
    ;; ("b3-c53-m1" "e" (:idealised :en) ,*lilypond-backend-modern-meter*)
    ))

(defparameter *book5-original*
  `(
    ("b5-c4-m1" "c-original" (:idealised :it) ,*lilypond-backend-original*)
    ("b5-c4-m1" "d-original" (:idealised :de) ,*lilypond-backend-original*)
    ("b5-c4-m1" "e-original" (:idealised :en) ,*lilypond-backend-original*)
    ("b5-c4-m2" "c-original" (:idealised :it) ,*lilypond-backend-original*)
    ("b5-c4-m2" "d-original" (:idealised :de) ,*lilypond-backend-original*)
    ("b5-c4-m2" "e-original" (:idealised :en) ,*lilypond-backend-original*)
    ("b5-c4-m3" "c-original" (:idealised :it) ,*lilypond-backend-original*)
    ("b5-c4-m3" "d-original" (:idealised :de) ,*lilypond-backend-original*)
    ("b5-c4-m3" "e-original" (:idealised :en) ,*lilypond-backend-original*)
    ("b5-c8-m1" "c-original" (:idealised :it) ,*lilypond-backend-original*)
    ("b5-c8-m1" "d-original" (:idealised :de) ,*lilypond-backend-original*)
    ("b5-c8-m1" "e-original" (:idealised :en) ,*lilypond-backend-original*)
    ("b5-c9-m1" "c-original" (:idealised :it) ,*lilypond-backend-original*)
    ("b5-c9-m1" "d-original" (:idealised :de) ,*lilypond-backend-original*)
    ("b5-c9-m1" "e-original" (:idealised :en) ,*lilypond-backend-original*)
    ("b5-c10-m1" "c-original" (:idealised :it) ,*lilypond-backend-original*)
    ("b5-c10-m1" "d-original" (:idealised :de :it) ,*lilypond-backend-original*)
    ("b5-c10-m1" "e-original" (:idealised :en :it) ,*lilypond-backend-original*)
    ("b5-c11-m1" "c-original" (:idealised :it) ,*lilypond-backend-original*)
    ("b5-c11-m1" "d-original" (:idealised :de) ,*lilypond-backend-original*)
    ("b5-c11-m1" "e-original" (:idealised :en) ,*lilypond-backend-original*)
    ("b5-c12-m1" "c-original" (:idealised :it) ,*lilypond-backend-original*)
    ("b5-c12-m1" "d-original" (:idealised :de) ,*lilypond-backend-original*)
    ("b5-c12-m1" "e-original" (:idealised :en) ,*lilypond-backend-original*)
    ("b5-c13-m1" "c-original" (:idealised :it) ,*lilypond-backend-original*)
    ("b5-c13-m1" "d-original" (:idealised :de) ,*lilypond-backend-original*)
    ("b5-c13-m1" "e-original" (:idealised :en) ,*lilypond-backend-original*)
    ("b5-c14-m1" "c-original" (:idealised :it) ,*lilypond-backend-original*)
    ("b5-c14-m1" "d-original" (:idealised :de) ,*lilypond-backend-original*)
    ("b5-c14-m1" "e-original" (:idealised :en) ,*lilypond-backend-original*)
    ("b5-c15-m1" "c-original" (:idealised :it) ,*lilypond-backend-original*)
    ("b5-c15-m1" "d-original" (:idealised :de) ,*lilypond-backend-original*)
    ("b5-c15-m1" "e-original" (:idealised :en) ,*lilypond-backend-original*)
    ("b5-c16-m1" "c-original" (:idealised :it) ,*lilypond-backend-original*)
    ("b5-c16-m1" "d-original" (:idealised :de) ,*lilypond-backend-original*)
    ("b5-c16-m1" "e-original" (:idealised :en) ,*lilypond-backend-original*)
    ))

(defparameter *book5-modern*
  `(
    ("b5-c4-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b5-c4-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b5-c4-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b5-c4-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b5-c4-m2" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b5-c4-m2" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b5-c4-m3" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b5-c4-m3" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b5-c4-m3" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b5-c8-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b5-c8-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b5-c8-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b5-c9-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b5-c9-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b5-c9-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b5-c10-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b5-c10-m1" "d" (:idealised :de :it) ,*lilypond-backend-modern*)
    ("b5-c10-m1" "e" (:idealised :en :it) ,*lilypond-backend-modern*)
    ("b5-c11-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b5-c11-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b5-c11-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b5-c12-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b5-c12-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b5-c12-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b5-c13-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b5-c13-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b5-c13-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b5-c14-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b5-c14-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b5-c14-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b5-c15-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b5-c15-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b5-c15-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b5-c16-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b5-c16-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b5-c16-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ))

(defparameter *book5-types*
  `(
    ("b5-c4-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b5-c4-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b5-c4-m2" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b5-c4-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ("b5-c4-m3" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b5-c4-m3" "b" (:idealised) ,*vicentino-types-backend*)
    ("b5-c8-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b5-c8-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b5-c9-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b5-c9-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b5-c10-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b5-c10-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b5-c11-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b5-c11-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b5-c12-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b5-c12-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b5-c13-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b5-c13-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b5-c14-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b5-c14-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b5-c15-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b5-c15-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b5-c16-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b5-c16-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ))

(defparameter *book3-original*
  `(

    ))

(defparameter *book3-modern*
  `(
    ("b3-c45-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c45-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c45-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c45-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c45-m2" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c45-m2" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c45-m3" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c45-m3" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c45-m3" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c46-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c46-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c46-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c46-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c46-m2" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c46-m2" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c46-m3" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c46-m3" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c46-m3" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c46-m4" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c46-m4" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c46-m4" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c46-m5" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c46-m5" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c46-m5" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c47-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c47-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c47-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c48-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c48-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c48-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c48-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c48-m2" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c48-m2" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c48-m3" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c48-m3" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c48-m3" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c49-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c49-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c49-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c49-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c49-m2" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c49-m2" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c49-m3" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c49-m3" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c49-m3" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c49-m4" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c49-m4" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c49-m4" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c49-m5" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c49-m5" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c49-m5" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c49-m6" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c49-m6" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c49-m6" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c49-m7" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c49-m7" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c49-m7" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c49-m8" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c49-m8" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c49-m8" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c50-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b3-c50-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b3-c50-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b3-c51-m1" "c" (:idealised :it) ,*lilypond-backend-modern-meter*)
    ("b3-c51-m1" "d" (:idealised :de) ,*lilypond-backend-modern-meter*)
    ("b3-c51-m1" "e" (:idealised :en) ,*lilypond-backend-modern-meter*)
    ("b3-c52-m1" "c" (:idealised :it) ,*lilypond-backend-modern-meter*)
    ("b3-c52-m1" "d" (:idealised :de) ,*lilypond-backend-modern-meter*)
    ("b3-c52-m1" "e" (:idealised :en) ,*lilypond-backend-modern-meter*)
    ))

(defparameter *book3-types*
  `(
    ("b3-c45-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c45-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c45-m2" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c45-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c45-m3" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c45-m3" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c46-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c46-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c46-m2" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c46-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c46-m3" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c46-m3" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c46-m4" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c46-m4" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c46-m5" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c46-m5" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c47-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c47-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c48-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c48-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c48-m2" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c48-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c48-m3" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c48-m3" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c49-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c49-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c49-m2" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c49-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c49-m3" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c49-m3" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c49-m4" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c49-m4" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c49-m5" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c49-m5" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c49-m6" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c49-m6" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c49-m7" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c49-m7" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c49-m8" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c49-m8" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c50-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c50-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c51-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c51-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b3-c52-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b3-c52-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ))

(defparameter *book2-original*
  `(
    ("b2-c2-m1" "c-original" (:idealised :it) ,*lilypond-backend-original*)
    ("b2-c2-m1" "d-original" (:idealised :de) ,*lilypond-backend-original*)
    ("b2-c2-m1" "e-original" (:idealised :en) ,*lilypond-backend-original*)
    ("b2-c2-m2" "c-original" (:idealised :it) ,*lilypond-backend-original*)
    ("b2-c2-m2" "d-original" (:idealised :de) ,*lilypond-backend-original*)
    ("b2-c2-m2" "e-original" (:idealised :en) ,*lilypond-backend-original*)
    ("b2-c3-m1" "c-original" (:idealised :it) ,*lilypond-backend-original*)
    ("b2-c3-m1" "d-original" (:idealised :de) ,*lilypond-backend-original*)
    ("b2-c3-m1" "e-original" (:idealised :en) ,*lilypond-backend-original*)
    ))

(defparameter *book2-modern*
  `(
    ("b2-c2-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b2-c2-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b2-c2-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b2-c2-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b2-c2-m2" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b2-c2-m2" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b2-c3-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b2-c3-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b2-c3-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b2-c3-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b2-c3-m2" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b2-c3-m2" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ))

(defparameter *book2-types*
  `(
    ("b2-c2-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b2-c2-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b2-c2-m2" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b2-c2-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ("b2-c3-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b2-c3-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b2-c3-m2" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b2-c3-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ))

(defparameter *book1-original*
  `(
    ("b1-c5-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c5-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c5-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c5-m2" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c5-m2" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c5-m2" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c5-m3" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c5-m3" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c5-m3" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c5-m4" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c5-m4" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c5-m4" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c5-m5" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c5-m5" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c5-m5" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c5-m6" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c5-m6" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c5-m6" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c5-m7" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c5-m7" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c5-m7" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c5-m8" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c5-m8" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c5-m8" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c6-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c6-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c6-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c7-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c7-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c7-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c8-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c8-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c8-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c8-m2" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c8-m2" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c8-m2" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c9-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c9-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c9-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c10-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c10-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c10-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c10-m2" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c10-m2" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c10-m2" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c11-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c11-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c11-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c11-m2" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c11-m2" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c11-m2" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c11-m3" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c11-m3" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c11-m3" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c12-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c12-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c12-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c13-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c13-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c13-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c15-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c15-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c15-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c16-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c16-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c16-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c17-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c17-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c17-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c18-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c18-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c18-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c19-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c19-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c19-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c20-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c20-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c20-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c21-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c21-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c21-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c22-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c22-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c22-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c23-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c23-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c23-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c24-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c24-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c24-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c25-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c25-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c25-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c26-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c26-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c26-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c27-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c27-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c27-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c28-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c28-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c28-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c29-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c29-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c29-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c30-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c30-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c30-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c31-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c31-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c31-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c32-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c32-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c32-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c33-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c33-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c33-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c34-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c34-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c34-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c35-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c35-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c35-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c36-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c36-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c36-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c37-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c37-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c37-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c37-m2" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c37-m2" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c37-m2" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c38-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c38-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c38-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c39-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c39-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c39-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c39-m2" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c39-m2" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c39-m2" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c40-m1" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c40-m1" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c40-m1" "e-orig" (:idealised :en) ,*lilypond-backend-original*)
    ("b1-c40-m2" "c-orig" (:idealised :it) ,*lilypond-backend-original*)
    ("b1-c40-m2" "d-orig" (:idealised :de) ,*lilypond-backend-original*)
    ("b1-c40-m2" "e-orig" (:idealised :en) ,*lilypond-backend-original*)))

(defparameter *book1-modern*
  `(
    ("b1-c5-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c5-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c5-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c5-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c5-m2" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c5-m2" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c5-m3" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c5-m3" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c5-m3" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c5-m4" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c5-m4" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c5-m4" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c5-m5" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c5-m5" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c5-m5" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c5-m6" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c5-m6" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c5-m6" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c5-m7" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c5-m7" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c5-m7" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c5-m8" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c5-m8" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c5-m8" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c6-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c6-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c6-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c7-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c7-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c7-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c8-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c8-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c8-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c8-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c8-m2" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c8-m2" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c9-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c9-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c9-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c10-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c10-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c10-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c10-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c10-m2" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c10-m2" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c11-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c11-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c11-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c11-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c11-m2" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c11-m2" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c11-m3" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c11-m3" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c11-m3" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c12-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c12-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c12-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c13-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c13-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c13-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c15-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c15-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c15-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c16-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c16-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c16-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c17-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c17-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c17-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c18-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c18-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c18-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c19-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c19-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c19-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c20-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c20-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c20-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c21-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c21-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c21-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c22-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c22-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c22-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c23-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c23-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c23-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c24-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c24-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c24-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c25-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c25-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c25-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c26-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c26-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c26-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c27-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c27-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c27-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c28-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c28-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c28-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c29-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c29-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c29-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c30-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c30-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c30-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c31-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c31-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c31-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c32-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c32-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c32-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c33-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c33-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c33-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c34-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c34-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c34-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c35-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c35-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c35-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c36-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c36-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c36-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c37-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c37-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c37-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c37-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c37-m2" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c37-m2" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c38-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c38-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c38-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c39-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c39-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c39-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c39-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c39-m2" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c39-m2" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c40-m1" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c40-m1" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c40-m1" "e" (:idealised :en) ,*lilypond-backend-modern*)
    ("b1-c40-m2" "c" (:idealised :it) ,*lilypond-backend-modern*)
    ("b1-c40-m2" "d" (:idealised :de) ,*lilypond-backend-modern*)
    ("b1-c40-m2" "e" (:idealised :en) ,*lilypond-backend-modern*)))


(defparameter *book1-types*
  `(
    ("b1-c40-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c40-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c40-m2" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c40-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c39-m2" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c39-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c39-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c39-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c38-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c38-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c37-m2" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c37-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c37-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c37-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c36-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c36-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c35-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c35-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c34-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c34-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c33-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c33-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c32-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c32-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c31-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c31-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c30-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c30-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c29-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c29-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c28-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c28-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c27-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c27-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c26-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c26-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c25-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c25-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c24-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c24-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c23-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c23-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c22-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c22-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c21-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c21-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c20-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c20-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c19-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c19-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c18-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c18-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c17-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c17-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c16-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c16-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c15-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c15-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c13-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c13-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c12-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c12-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c11-m3" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c11-m3" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c11-m2" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c11-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c11-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c11-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c10-m2" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c10-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c10-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c10-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c9-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c9-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c8-m2" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c8-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c8-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c8-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c7-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c7-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c6-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c6-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c5-m8" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c5-m8" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c5-m7" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c5-m7" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c5-m6" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c5-m6" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c5-m5" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c5-m5" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c5-m4" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c5-m4" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c5-m3" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c5-m3" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c5-m2" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c5-m2" "b" (:idealised) ,*vicentino-types-backend*)
    ("b1-c5-m1" "a" (:diplomatic) ,*vicentino-types-backend*)
    ("b1-c5-m1" "b" (:idealised) ,*vicentino-types-backend*)
    ))

(defparameter *special*
  `(
    ("single-note-a1" "orig" () ,*vicentino-types-backend*)
    ("single-note-a2" "orig" () ,*vicentino-types-backend*)
    ("single-note-a3" "orig" () ,*vicentino-types-backend*)
    ("single-note-a4" "orig" () ,*vicentino-types-backend*)
    ("single-note-a5" "orig" () ,*vicentino-types-backend*)
    ("single-note-a6" "orig" () ,*vicentino-types-backend*)
    ("single-note-g1" "orig" () ,*vicentino-types-backend*)
    ("single-note-g2" "orig" () ,*vicentino-types-backend*)
    ("single-note-g3" "orig" () ,*vicentino-types-backend*)
    ("single-note-g4" "orig" () ,*vicentino-types-backend*)
    ("single-note-g5" "orig" () ,*vicentino-types-backend*)
    ("single-note-g6" "orig" () ,*vicentino-types-backend*)
    ("single-note-f1" "orig" () ,*vicentino-types-backend*)
    ("single-note-f3" "orig" () ,*vicentino-types-backend*)
    ("single-note-f4" "orig" () ,*vicentino-types-backend*)
    ("single-note-e1" "orig" () ,*vicentino-types-backend*)
    ("single-note-e2" "orig" () ,*vicentino-types-backend*)
    ("single-note-e3" "orig" () ,*vicentino-types-backend*)
    ("single-note-e4" "orig" () ,*vicentino-types-backend*)
    ("single-note-e5" "orig" () ,*vicentino-types-backend*)
    ("single-note-e6" "orig" () ,*vicentino-types-backend*)
    ("single-note-d1" "orig" () ,*vicentino-types-backend*)
    ("single-note-d2" "orig" () ,*vicentino-types-backend*)
    ("single-note-d3" "orig" () ,*vicentino-types-backend*)
    ("single-note-d4" "orig" () ,*vicentino-types-backend*)
    ("single-note-d5" "orig" () ,*vicentino-types-backend*)
    ("single-note-d6" "orig" () ,*vicentino-types-backend*)
    ("single-note-c1" "orig" () ,*vicentino-types-backend*)
    ("single-note-c3" "orig" () ,*vicentino-types-backend*)
    ("single-note-c4" "orig" () ,*vicentino-types-backend*)
    ("single-note-b1" "orig" () ,*vicentino-types-backend*)
    ("single-note-b2" "orig" () ,*vicentino-types-backend*)
    ("single-note-b3" "orig" () ,*vicentino-types-backend*)
    ("single-note-b4" "orig" () ,*vicentino-types-backend*)
    ("single-note-b5" "orig" () ,*vicentino-types-backend*)
    ("single-note-b6" "orig" () ,*vicentino-types-backend*)
    ("single-note-doubtful-cb" "orig" () ,*vicentino-types-backend*)
    ("single-note-doubtful-fb" "orig" () ,*vicentino-types-backend*)
    ("single-note-doubtful-fsharpdot" "orig" () ,*vicentino-types-backend*)
    ("single-note-doubtful-gsharpdot" "orig" () ,*vicentino-types-backend*)
    ("single-note-doubtful-asharpdot" "orig" () ,*vicentino-types-backend*)
    ("single-note-doubtful-csharpdot" "orig" () ,*vicentino-types-backend*)
    ("single-note-doubtful-dsharpdot" "orig" () ,*vicentino-types-backend*)

    ("single-note-a1" "modern" () ,*lilypond-backend-modern*)
    ("single-note-a2" "modern" () ,*lilypond-backend-modern*)
    ("single-note-a3" "modern" () ,*lilypond-backend-modern*)
    ("single-note-a4" "modern" () ,*lilypond-backend-modern*)
    ("single-note-a5" "modern" () ,*lilypond-backend-modern*)
    ("single-note-a6" "modern" () ,*lilypond-backend-modern*)
    ("single-note-g1" "modern" () ,*lilypond-backend-modern*)
    ("single-note-g2" "modern" () ,*lilypond-backend-modern*)
    ("single-note-g3" "modern" () ,*lilypond-backend-modern*)
    ("single-note-g4" "modern" () ,*lilypond-backend-modern*)
    ("single-note-g5" "modern" () ,*lilypond-backend-modern*)
    ("single-note-g6" "modern" () ,*lilypond-backend-modern*)
    ("single-note-f1" "modern" () ,*lilypond-backend-modern*)
    ("single-note-f3" "modern" () ,*lilypond-backend-modern*)
    ("single-note-f4" "modern" () ,*lilypond-backend-modern*)
    ("single-note-e1" "modern" () ,*lilypond-backend-modern*)
    ("single-note-e2" "modern" () ,*lilypond-backend-modern*)
    ("single-note-e3" "modern" () ,*lilypond-backend-modern*)
    ("single-note-e4" "modern" () ,*lilypond-backend-modern*)
    ("single-note-e5" "modern" () ,*lilypond-backend-modern*)
    ("single-note-e6" "modern" () ,*lilypond-backend-modern*)
    ("single-note-d1" "modern" () ,*lilypond-backend-modern*)
    ("single-note-d2" "modern" () ,*lilypond-backend-modern*)
    ("single-note-d3" "modern" () ,*lilypond-backend-modern*)
    ("single-note-d4" "modern" () ,*lilypond-backend-modern*)
    ("single-note-d5" "modern" () ,*lilypond-backend-modern*)
    ("single-note-d6" "modern" () ,*lilypond-backend-modern*)
    ("single-note-c1" "modern" () ,*lilypond-backend-modern*)
    ("single-note-c3" "modern" () ,*lilypond-backend-modern*)
    ("single-note-c4" "modern" () ,*lilypond-backend-modern*)
    ("single-note-b1" "modern" () ,*lilypond-backend-modern*)
    ("single-note-b2" "modern" () ,*lilypond-backend-modern*)
    ("single-note-b3" "modern" () ,*lilypond-backend-modern*)
    ("single-note-b4" "modern" () ,*lilypond-backend-modern*)
    ("single-note-b5" "modern" () ,*lilypond-backend-modern*)
    ("single-note-b6" "modern" () ,*lilypond-backend-modern*)

    ("single-note-doubtful-cb" "modern" () ,*lilypond-backend-modern*)
    ("single-note-doubtful-fb" "modern" () ,*lilypond-backend-modern*)
    ("single-note-doubtful-fsharpdot" "modern" () ,*lilypond-backend-modern*)
    ("single-note-doubtful-gsharpdot" "modern" () ,*lilypond-backend-modern*)
    ("single-note-doubtful-asharpdot" "modern" () ,*lilypond-backend-modern*)
    ("single-note-doubtful-csharpdot" "modern" () ,*lilypond-backend-modern*)
    ("single-note-doubtful-dsharpdot" "modern" () ,*lilypond-backend-modern*)
    ))
