(defun jk/unicode-entry (id)
  (interactive "M")
  (pcase id
    ("ls" (insert "ſ"))
    ("per" (insert "ꝑ"))
    ("amp" (insert "&"))
    ("ss" (insert "ß"))
    ("ae" (insert "æ"))
    ("aaa" (insert "ā"))
    ("eee" (insert "ē"))
    ("iii" (insert "ī"))
    ("ooo" (insert "ō"))
    ("uuu" (insert "ū"))
    ("st" (insert "ﬆ"))
    ("cg" (insert "ɢ"))
    ("ci" (insert "ɪ"))
    ("cn" (insert "ɴ"))
    ("cr" (insert "ʀ"))
    ("cy" (insert "ʏ"))
    ("cb" (insert "ʙ"))
    ("ch" (insert "ʜ"))
    ("cl" (insert "ʟ"))
    ("ca" (insert "ᴀ"))
    ("cc" (insert "ᴄ"))
    ("cd" (insert "ᴅ"))
    ("ce" (insert "ᴇ"))
    ("cm" (insert "ᴍ"))
    ("co" (insert "ᴏ"))
    ("cp" (insert "ᴘ"))
    ("ct" (insert "ᴛ"))
    ("cv" (insert "ᴠ"))
    ("-" (insert "⸗"))
    ("cf" (insert "ꜰ"))
    ("cs" (insert "ꜱ"))
    ("q" (insert "Ɋ"))
    ("z" (insert "ȥ"))
    ("apo" (insert "ʼ"))))


(global-set-key (kbd "C-M-k") 'jk/unicode-entry)
